// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import "testing"

// TestTrinity_Window validates window function functionality per DO-178C trace.
func TestTrinity_Window(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityWindowTests())
}

func buildTrinityWindowTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genWindowRankTests()...)
	tests = append(tests, genWindowValueTests()...)
	tests = append(tests, genWindowFrameTests()...)
	tests = append(tests, genWindowAggregateTests()...)
	return tests
}

// windowSetup is the shared schema for most window tests.
func windowSetup() []string {
	return []string{
		"CREATE TABLE w(id INTEGER PRIMARY KEY, dept TEXT, name TEXT, salary INTEGER)",
		"INSERT INTO w VALUES(1,'eng','Alice',90000)",
		"INSERT INTO w VALUES(2,'eng','Bob',85000)",
		"INSERT INTO w VALUES(3,'eng','Carol',92000)",
		"INSERT INTO w VALUES(4,'sales','Dave',70000)",
		"INSERT INTO w VALUES(5,'sales','Eve',75000)",
		"INSERT INTO w VALUES(6,'sales','Frank',72000)",
		"INSERT INTO w VALUES(7,'hr','Grace',65000)",
		"INSERT INTO w VALUES(8,'hr','Heidi',68000)",
	}
}

// ---------------------------------------------------------------------------
// ROW_NUMBER, RANK, DENSE_RANK, NTILE
// ---------------------------------------------------------------------------

func genWindowRankTests() []sqlTestCase {
	ws := windowSetup()
	return []sqlTestCase{
		{
			name:  "REQ-WIN-001_row_number_global",
			setup: ws,
			query: "SELECT name, ROW_NUMBER() OVER (ORDER BY salary DESC) AS rn FROM w ORDER BY rn LIMIT 3",
			wantRows: [][]interface{}{
				{"Carol", int64(1)}, {"Alice", int64(2)}, {"Bob", int64(3)},
			},
		},
		{
			name:  "REQ-WIN-002_row_number_partition",
			setup: ws,
			query: "SELECT dept, name, ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC) AS rn FROM w WHERE dept='eng' ORDER BY rn",
			wantRows: [][]interface{}{
				{"eng", "Carol", int64(1)}, {"eng", "Alice", int64(2)}, {"eng", "Bob", int64(3)},
			},
		},
		{
			name: "REQ-WIN-003_rank_with_ties",
			setup: []string{
				"CREATE TABLE wr(name TEXT, score INTEGER)",
				"INSERT INTO wr VALUES('A',100)", "INSERT INTO wr VALUES('B',90)",
				"INSERT INTO wr VALUES('C',90)", "INSERT INTO wr VALUES('D',80)",
			},
			query: "SELECT name, RANK() OVER (ORDER BY score DESC) AS rnk FROM wr ORDER BY name",
			wantRows: [][]interface{}{
				{"A", int64(1)}, {"B", int64(2)}, {"C", int64(2)}, {"D", int64(4)},
			},
		},
		{
			name: "REQ-WIN-004_dense_rank_with_ties",
			setup: []string{
				"CREATE TABLE wdr(name TEXT, score INTEGER)",
				"INSERT INTO wdr VALUES('A',100)", "INSERT INTO wdr VALUES('B',90)",
				"INSERT INTO wdr VALUES('C',90)", "INSERT INTO wdr VALUES('D',80)",
			},
			query: "SELECT name, DENSE_RANK() OVER (ORDER BY score DESC) AS drnk FROM wdr ORDER BY name",
			wantRows: [][]interface{}{
				{"A", int64(1)}, {"B", int64(2)}, {"C", int64(2)}, {"D", int64(3)},
			},
		},
		{
			name:  "REQ-WIN-005_rank_partition",
			setup: ws,
			query: "SELECT dept, name, RANK() OVER (PARTITION BY dept ORDER BY salary DESC) AS rnk FROM w WHERE dept IN ('eng','hr') ORDER BY dept, rnk",
			wantRows: [][]interface{}{
				{"eng", "Carol", int64(1)}, {"eng", "Alice", int64(2)}, {"eng", "Bob", int64(3)},
				{"hr", "Heidi", int64(1)}, {"hr", "Grace", int64(2)},
			},
		},
		{
			name:  "REQ-WIN-006_dense_rank_partition",
			setup: ws,
			query: "SELECT dept, name, DENSE_RANK() OVER (PARTITION BY dept ORDER BY salary DESC) AS drnk FROM w WHERE dept='sales' ORDER BY drnk",
			wantRows: [][]interface{}{
				{"sales", "Eve", int64(1)}, {"sales", "Frank", int64(2)}, {"sales", "Dave", int64(3)},
			},
		},
		{
			name:  "REQ-WIN-007_ntile_2",
			setup: ws,
			query: "SELECT name, NTILE(2) OVER (ORDER BY salary DESC) AS tile FROM w ORDER BY salary DESC",
			wantRows: [][]interface{}{
				{"Carol", int64(1)}, {"Alice", int64(1)}, {"Bob", int64(1)}, {"Eve", int64(1)},
				{"Frank", int64(2)}, {"Dave", int64(2)}, {"Heidi", int64(2)}, {"Grace", int64(2)},
			},
		},
		{
			name: "REQ-WIN-008_ntile_3",
			setup: []string{
				"CREATE TABLE wn3(v INTEGER)",
				"INSERT INTO wn3 VALUES(1)", "INSERT INTO wn3 VALUES(2)", "INSERT INTO wn3 VALUES(3)",
				"INSERT INTO wn3 VALUES(4)", "INSERT INTO wn3 VALUES(5)", "INSERT INTO wn3 VALUES(6)",
			},
			query: "SELECT v, NTILE(3) OVER (ORDER BY v) AS tile FROM wn3 ORDER BY v",
			wantRows: [][]interface{}{
				{int64(1), int64(1)}, {int64(2), int64(1)},
				{int64(3), int64(2)}, {int64(4), int64(2)},
				{int64(5), int64(3)}, {int64(6), int64(3)},
			},
		},
		{
			name:  "REQ-WIN-009_ntile_partition",
			setup: ws,
			query: "SELECT dept, name, NTILE(2) OVER (PARTITION BY dept ORDER BY salary) AS tile FROM w WHERE dept='eng' ORDER BY salary",
			wantRows: [][]interface{}{
				{"eng", "Bob", int64(1)}, {"eng", "Alice", int64(1)}, {"eng", "Carol", int64(2)},
			},
		},
		{
			name:     "REQ-WIN-010_row_number_no_order",
			setup:    []string{"CREATE TABLE wrn(v TEXT)", "INSERT INTO wrn VALUES('a')", "INSERT INTO wrn VALUES('b')", "INSERT INTO wrn VALUES('c')"},
			query:    "SELECT COUNT(DISTINCT rn) FROM (SELECT ROW_NUMBER() OVER () AS rn FROM wrn)",
			wantRows: [][]interface{}{{int64(3)}},
		},
	}
}

// ---------------------------------------------------------------------------
// LAG, LEAD, FIRST_VALUE, LAST_VALUE, NTH_VALUE
// ---------------------------------------------------------------------------

func genWindowValueTests() []sqlTestCase {
	seqSetup := []string{
		"CREATE TABLE wv(id INTEGER PRIMARY KEY, val INTEGER)",
		"INSERT INTO wv VALUES(1,10)", "INSERT INTO wv VALUES(2,20)",
		"INSERT INTO wv VALUES(3,30)", "INSERT INTO wv VALUES(4,40)",
		"INSERT INTO wv VALUES(5,50)",
	}
	return []sqlTestCase{
		{
			name:  "REQ-WIN-020_lag_default",
			setup: seqSetup,
			query: "SELECT id, val, LAG(val) OVER (ORDER BY id) AS prev FROM wv ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(10), nil},
				{int64(2), int64(20), int64(10)},
				{int64(3), int64(30), int64(20)},
				{int64(4), int64(40), int64(30)},
				{int64(5), int64(50), int64(40)},
			},
		},
		{
			name:  "REQ-WIN-021_lag_offset_2",
			setup: seqSetup,
			query: "SELECT id, LAG(val, 2) OVER (ORDER BY id) AS prev2 FROM wv ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), nil}, {int64(2), nil},
				{int64(3), int64(10)}, {int64(4), int64(20)}, {int64(5), int64(30)},
			},
		},
		{
			name:  "REQ-WIN-022_lag_offset_default_value",
			setup: seqSetup,
			query: "SELECT id, LAG(val, 1, -1) OVER (ORDER BY id) AS prev FROM wv ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(-1)}, {int64(2), int64(10)},
				{int64(3), int64(20)}, {int64(4), int64(30)}, {int64(5), int64(40)},
			},
		},
		{
			name:  "REQ-WIN-023_lead_default",
			setup: seqSetup,
			query: "SELECT id, val, LEAD(val) OVER (ORDER BY id) AS nxt FROM wv ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(10), int64(20)},
				{int64(2), int64(20), int64(30)},
				{int64(3), int64(30), int64(40)},
				{int64(4), int64(40), int64(50)},
				{int64(5), int64(50), nil},
			},
		},
		{
			name:  "REQ-WIN-024_lead_offset_2",
			setup: seqSetup,
			query: "SELECT id, LEAD(val, 2) OVER (ORDER BY id) AS nxt2 FROM wv ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(30)}, {int64(2), int64(40)}, {int64(3), int64(50)},
				{int64(4), nil}, {int64(5), nil},
			},
		},
		{
			name:  "REQ-WIN-025_lead_default_value",
			setup: seqSetup,
			query: "SELECT id, LEAD(val, 1, 0) OVER (ORDER BY id) AS nxt FROM wv ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(20)}, {int64(2), int64(30)}, {int64(3), int64(40)},
				{int64(4), int64(50)}, {int64(5), int64(0)},
			},
		},
		{
			name:  "REQ-WIN-026_first_value",
			setup: seqSetup,
			query: "SELECT id, FIRST_VALUE(val) OVER (ORDER BY id) AS fv FROM wv ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(10)}, {int64(2), int64(10)}, {int64(3), int64(10)},
				{int64(4), int64(10)}, {int64(5), int64(10)},
			},
		},
		{
			name:  "REQ-WIN-027_first_value_partition",
			setup: windowSetup(),
			query: "SELECT dept, name, FIRST_VALUE(name) OVER (PARTITION BY dept ORDER BY salary DESC) AS top FROM w WHERE dept IN ('eng','hr') ORDER BY dept, salary DESC",
			wantRows: [][]interface{}{
				{"eng", "Carol", "Carol"}, {"eng", "Alice", "Carol"}, {"eng", "Bob", "Carol"},
				{"hr", "Heidi", "Heidi"}, {"hr", "Grace", "Heidi"},
			},
		},
		{
			name:  "REQ-WIN-028_last_value_full_frame",
			setup: seqSetup,
			query: "SELECT id, LAST_VALUE(val) OVER (ORDER BY id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS lv FROM wv ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(50)}, {int64(2), int64(50)}, {int64(3), int64(50)},
				{int64(4), int64(50)}, {int64(5), int64(50)},
			},
		},
		{
			name:  "REQ-WIN-029_nth_value_2",
			setup: seqSetup,
			query: "SELECT id, NTH_VALUE(val, 2) OVER (ORDER BY id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS nv FROM wv ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(20)}, {int64(2), int64(20)}, {int64(3), int64(20)},
				{int64(4), int64(20)}, {int64(5), int64(20)},
			},
		},
		{
			name:  "REQ-WIN-030_nth_value_3",
			setup: seqSetup,
			query: "SELECT id, NTH_VALUE(val, 3) OVER (ORDER BY id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS nv FROM wv ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(30)}, {int64(2), int64(30)}, {int64(3), int64(30)},
				{int64(4), int64(30)}, {int64(5), int64(30)},
			},
		},
		{
			name:  "REQ-WIN-031_lag_partition",
			setup: windowSetup(),
			query: "SELECT dept, name, LAG(name) OVER (PARTITION BY dept ORDER BY salary) AS prev FROM w WHERE dept='sales' ORDER BY salary",
			wantRows: [][]interface{}{
				{"sales", "Dave", nil}, {"sales", "Frank", "Dave"}, {"sales", "Eve", "Frank"},
			},
		},
		{
			name:  "REQ-WIN-032_lead_partition",
			setup: windowSetup(),
			query: "SELECT dept, name, LEAD(name) OVER (PARTITION BY dept ORDER BY salary) AS nxt FROM w WHERE dept='sales' ORDER BY salary",
			wantRows: [][]interface{}{
				{"sales", "Dave", "Frank"}, {"sales", "Frank", "Eve"}, {"sales", "Eve", nil},
			},
		},
	}
}

// ---------------------------------------------------------------------------
// Window frames: ROWS BETWEEN ...
// ---------------------------------------------------------------------------

func genWindowFrameTests() []sqlTestCase {
	seqSetup := []string{
		"CREATE TABLE wf(id INTEGER PRIMARY KEY, val INTEGER)",
		"INSERT INTO wf VALUES(1,10)", "INSERT INTO wf VALUES(2,20)",
		"INSERT INTO wf VALUES(3,30)", "INSERT INTO wf VALUES(4,40)",
		"INSERT INTO wf VALUES(5,50)",
	}
	return []sqlTestCase{
		{
			name:  "REQ-WIN-040_rows_unbounded_preceding_current",
			setup: seqSetup,
			query: "SELECT id, SUM(val) OVER (ORDER BY id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running FROM wf ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(10)}, {int64(2), int64(30)}, {int64(3), int64(60)},
				{int64(4), int64(100)}, {int64(5), int64(150)},
			},
		},
		{
			name:  "REQ-WIN-041_rows_1_preceding_1_following",
			setup: seqSetup,
			query: "SELECT id, SUM(val) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS s FROM wf ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(30)}, {int64(2), int64(60)}, {int64(3), int64(90)},
				{int64(4), int64(120)}, {int64(5), int64(90)},
			},
		},
		{
			name:  "REQ-WIN-042_rows_current_row_only",
			setup: seqSetup,
			query: "SELECT id, SUM(val) OVER (ORDER BY id ROWS BETWEEN CURRENT ROW AND CURRENT ROW) AS s FROM wf ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(10)}, {int64(2), int64(20)}, {int64(3), int64(30)},
				{int64(4), int64(40)}, {int64(5), int64(50)},
			},
		},
		{
			name:  "REQ-WIN-043_rows_unbounded_both",
			setup: seqSetup,
			query: "SELECT id, SUM(val) OVER (ORDER BY id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS s FROM wf ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(150)}, {int64(2), int64(150)}, {int64(3), int64(150)},
				{int64(4), int64(150)}, {int64(5), int64(150)},
			},
		},
		{
			name:  "REQ-WIN-044_rows_2_preceding_current",
			setup: seqSetup,
			query: "SELECT id, SUM(val) OVER (ORDER BY id ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS s FROM wf ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(10)}, {int64(2), int64(30)}, {int64(3), int64(60)},
				{int64(4), int64(90)}, {int64(5), int64(120)},
			},
		},
		{
			name:  "REQ-WIN-045_avg_over_frame",
			setup: seqSetup,
			query: "SELECT id, AVG(val) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS a FROM wf ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), float64(15)}, {int64(2), float64(20)}, {int64(3), float64(30)},
				{int64(4), float64(40)}, {int64(5), float64(45)},
			},
		},
		{
			name:  "REQ-WIN-046_count_over_frame",
			setup: seqSetup,
			query: "SELECT id, COUNT(*) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS c FROM wf ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(2)}, {int64(2), int64(3)}, {int64(3), int64(3)},
				{int64(4), int64(3)}, {int64(5), int64(2)},
			},
		},
		{
			name:  "REQ-WIN-047_min_over_frame",
			setup: seqSetup,
			query: "SELECT id, MIN(val) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS mn FROM wf ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(10)}, {int64(2), int64(10)}, {int64(3), int64(20)},
				{int64(4), int64(30)}, {int64(5), int64(40)},
			},
		},
		{
			name:  "REQ-WIN-048_max_over_frame",
			setup: seqSetup,
			query: "SELECT id, MAX(val) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS mx FROM wf ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(20)}, {int64(2), int64(30)}, {int64(3), int64(40)},
				{int64(4), int64(50)}, {int64(5), int64(50)},
			},
		},
	}
}

// ---------------------------------------------------------------------------
// Aggregate window functions: SUM, COUNT, AVG over partitions
// ---------------------------------------------------------------------------

func genWindowAggregateTests() []sqlTestCase {
	ws := windowSetup()
	return []sqlTestCase{
		{
			name:  "REQ-WIN-060_sum_over_partition",
			setup: ws,
			query: "SELECT dept, name, SUM(salary) OVER (PARTITION BY dept) AS dept_total FROM w WHERE dept='eng' ORDER BY name",
			wantRows: [][]interface{}{
				{"eng", "Alice", int64(267000)}, {"eng", "Bob", int64(267000)}, {"eng", "Carol", int64(267000)},
			},
		},
		{
			name:  "REQ-WIN-061_count_over_partition",
			setup: ws,
			query: "SELECT dept, COUNT(*) OVER (PARTITION BY dept) AS cnt FROM w ORDER BY dept, name",
			wantRows: [][]interface{}{
				{"eng", int64(3)}, {"eng", int64(3)}, {"eng", int64(3)},
				{"hr", int64(2)}, {"hr", int64(2)},
				{"sales", int64(3)}, {"sales", int64(3)}, {"sales", int64(3)},
			},
		},
		{
			name:  "REQ-WIN-062_avg_over_partition",
			setup: ws,
			query: "SELECT dept, name, AVG(salary) OVER (PARTITION BY dept) AS avg_sal FROM w WHERE dept='hr' ORDER BY name",
			wantRows: [][]interface{}{
				{"hr", "Grace", float64(66500)}, {"hr", "Heidi", float64(66500)},
			},
		},
		{
			name:  "REQ-WIN-063_sum_over_no_partition",
			setup: ws,
			query: "SELECT name, SUM(salary) OVER () AS grand_total FROM w ORDER BY name LIMIT 1",
			wantRows: [][]interface{}{
				{"Alice", int64(617000)},
			},
		},
		{
			name:  "REQ-WIN-064_running_sum",
			setup: ws,
			query: "SELECT name, salary, SUM(salary) OVER (ORDER BY salary) AS running FROM w WHERE dept='eng' ORDER BY salary",
			wantRows: [][]interface{}{
				{"Bob", int64(85000), int64(85000)},
				{"Alice", int64(90000), int64(175000)},
				{"Carol", int64(92000), int64(267000)},
			},
		},
		{
			name:  "REQ-WIN-065_running_count",
			setup: ws,
			query: "SELECT name, COUNT(*) OVER (ORDER BY salary) AS rc FROM w WHERE dept='sales' ORDER BY salary",
			wantRows: [][]interface{}{
				{"Dave", int64(1)}, {"Frank", int64(2)}, {"Eve", int64(3)},
			},
		},
		{
			name:  "REQ-WIN-066_running_avg",
			setup: ws,
			query: "SELECT name, salary, AVG(salary) OVER (ORDER BY salary ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_avg FROM w WHERE dept='eng' ORDER BY salary",
			wantRows: [][]interface{}{
				{"Bob", int64(85000), float64(85000)},
				{"Alice", int64(90000), float64(87500)},
				{"Carol", int64(92000), float64(89000)},
			},
		},
		{
			name:  "REQ-WIN-067_min_over_partition",
			setup: ws,
			query: "SELECT dept, MIN(salary) OVER (PARTITION BY dept) AS mn FROM w ORDER BY dept, name",
			wantRows: [][]interface{}{
				{"eng", int64(85000)}, {"eng", int64(85000)}, {"eng", int64(85000)},
				{"hr", int64(65000)}, {"hr", int64(65000)},
				{"sales", int64(70000)}, {"sales", int64(70000)}, {"sales", int64(70000)},
			},
		},
		{
			name:  "REQ-WIN-068_max_over_partition",
			setup: ws,
			query: "SELECT dept, MAX(salary) OVER (PARTITION BY dept) AS mx FROM w ORDER BY dept, name",
			wantRows: [][]interface{}{
				{"eng", int64(92000)}, {"eng", int64(92000)}, {"eng", int64(92000)},
				{"hr", int64(68000)}, {"hr", int64(68000)},
				{"sales", int64(75000)}, {"sales", int64(75000)}, {"sales", int64(75000)},
			},
		},
		{
			name:  "REQ-WIN-069_multiple_windows_one_query",
			skip:  "SUM(salary) OVER () returns running sum instead of grand total when combined with ROW_NUMBER() OVER (ORDER BY ...) — different OVER clauses share accumulator state",
			setup: ws,
			query: "SELECT name, ROW_NUMBER() OVER (ORDER BY salary DESC) AS rn, SUM(salary) OVER () AS total FROM w ORDER BY salary DESC LIMIT 3",
			wantRows: [][]interface{}{
				{"Carol", int64(1), int64(617000)},
				{"Alice", int64(2), int64(617000)},
				{"Bob", int64(3), int64(617000)},
			},
		},
		{
			name:  "REQ-WIN-070_group_concat_over_partition",
			setup: ws,
			query: "SELECT dept, GROUP_CONCAT(name, ',') OVER (PARTITION BY dept ORDER BY name ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS names FROM w WHERE dept='hr' ORDER BY name LIMIT 1",
			wantRows: [][]interface{}{
				{"hr", "Grace,Heidi"},
			},
		},
		{
			name: "REQ-WIN-071_percent_rank",
			setup: []string{
				"CREATE TABLE wpr(v INTEGER)",
				"INSERT INTO wpr VALUES(10)", "INSERT INTO wpr VALUES(20)",
				"INSERT INTO wpr VALUES(30)", "INSERT INTO wpr VALUES(40)",
			},
			query: "SELECT v, PERCENT_RANK() OVER (ORDER BY v) AS pr FROM wpr ORDER BY v",
			wantRows: [][]interface{}{
				{int64(10), float64(0)},
				{int64(20), float64(1.0 / 3.0)},
				{int64(30), float64(2.0 / 3.0)},
				{int64(40), float64(1)},
			},
		},
		{
			name: "REQ-WIN-072_cume_dist",
			setup: []string{
				"CREATE TABLE wcd(v INTEGER)",
				"INSERT INTO wcd VALUES(10)", "INSERT INTO wcd VALUES(20)",
				"INSERT INTO wcd VALUES(30)", "INSERT INTO wcd VALUES(40)",
			},
			query: "SELECT v, CUME_DIST() OVER (ORDER BY v) AS cd FROM wcd ORDER BY v",
			wantRows: [][]interface{}{
				{int64(10), float64(0.25)}, {int64(20), float64(0.5)},
				{int64(30), float64(0.75)}, {int64(40), float64(1)},
			},
		},
	}
}
