// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import (
	"fmt"
	"testing"
)

// TestTrinity_Insert exercises single/multi-row INSERT, column list,
// INSERT...SELECT, OR REPLACE/IGNORE/ABORT, AUTOINCREMENT, and errors.
func TestTrinity_Insert(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityInsertTests())
}

func buildTrinityInsertTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genTrinityInsertBasicTests()...)
	tests = append(tests, genTrinityInsertMultiRowTests()...)
	tests = append(tests, genTrinityInsertSelectTests()...)
	tests = append(tests, genTrinityInsertConflictTests()...)
	tests = append(tests, genTrinityInsertAutoincTests()...)
	tests = append(tests, genTrinityInsertErrorTests()...)
	return tests
}

func genTrinityInsertBasicTests() []sqlTestCase {
	values := []struct {
		desc string
		cols string
		vals string
		want []interface{}
	}{
		{"all_cols", "id, name, age", "1, 'Alice', 30", []interface{}{int64(1), "Alice", int64(30)}},
		{"partial_cols", "id, name", "2, 'Bob'", []interface{}{int64(2), "Bob", nil}},
		{"no_col_list", "", "3, 'Carol', 25", []interface{}{int64(3), "Carol", int64(25)}},
		{"null_value", "id, name, age", "4, NULL, NULL", []interface{}{int64(4), nil, nil}},
		{"expr_value", "id, name, age", "5, 'Dave', 10 + 20", []interface{}{int64(5), "Dave", int64(30)}},
		{"string_concat", "id, name, age", "6, 'Ed' || 'ward', 40", []interface{}{int64(6), "Edward", int64(40)}},
		{"negative_value", "id, name, age", "7, 'Fay', -5", []interface{}{int64(7), "Fay", int64(-5)}},
		{"zero_value", "id, name, age", "8, 'Gus', 0", []interface{}{int64(8), "Gus", int64(0)}},
	}
	var tests []sqlTestCase
	for i, v := range values {
		name := fmt.Sprintf("REQ-INSERT-%03d_insert_%s", i+1, v.desc)
		insertSQL := "INSERT INTO t1 VALUES(" + v.vals + ")"
		if v.cols != "" {
			insertSQL = fmt.Sprintf("INSERT INTO t1(%s) VALUES(%s)", v.cols, v.vals)
		}
		tests = append(tests, sqlTestCase{
			name: name,
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, name TEXT, age INTEGER)",
				insertSQL,
			},
			query:    fmt.Sprintf("SELECT * FROM t1 WHERE id = %d", i+1),
			wantRows: [][]interface{}{v.want},
		})
	}
	return tests
}

func genTrinityInsertMultiRowTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-INSERT-010_multi_row_count",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO t1 VALUES(1,'a'),(2,'b'),(3,'c')",
			},
			query:    "SELECT COUNT(*) FROM t1",
			wantRows: [][]interface{}{{int64(3)}}},
		{name: "REQ-INSERT-011_multi_row_verify",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO t1 VALUES(1,'a'),(2,'b'),(3,'c')",
			},
			query:    "SELECT v FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{"a"}, {"b"}, {"c"}}},
		{name: "REQ-INSERT-012_multi_row_five",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v INTEGER)",
				"INSERT INTO t1 VALUES(1,10),(2,20),(3,30),(4,40),(5,50)",
			},
			query:    "SELECT SUM(v) FROM t1",
			wantRows: [][]interface{}{{int64(150)}}},
		{name: "REQ-INSERT-013_multi_row_with_null",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO t1 VALUES(1,'a'),(2,NULL),(3,'c')",
			},
			query:    "SELECT v FROM t1 WHERE id = 2",
			wantRows: [][]interface{}{{nil}}},
		{name: "REQ-INSERT-014_multi_row_order",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO t1 VALUES(3,'c'),(1,'a'),(2,'b')",
			},
			query:    "SELECT v FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{"a"}, {"b"}, {"c"}}},
		{name: "REQ-INSERT-015_multi_row_real",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v REAL)",
				"INSERT INTO t1 VALUES(1,1.1),(2,2.2),(3,3.3)",
			},
			query:    "SELECT v FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{1.1}, {2.2}, {3.3}}},
	}
}

func genTrinityInsertSelectTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-INSERT-020_insert_select_all",
			setup: []string{
				"CREATE TABLE src(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO src VALUES(1,'x'),(2,'y'),(3,'z')",
				"CREATE TABLE dst(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO dst SELECT * FROM src",
			},
			query:    "SELECT COUNT(*) FROM dst",
			wantRows: [][]interface{}{{int64(3)}}},
		{name: "REQ-INSERT-021_insert_select_where",
			setup: []string{
				"CREATE TABLE src(id INTEGER PRIMARY KEY, v INTEGER)",
				"INSERT INTO src VALUES(1,10),(2,20),(3,30)",
				"CREATE TABLE dst(id INTEGER PRIMARY KEY, v INTEGER)",
				"INSERT INTO dst SELECT * FROM src WHERE v > 15",
			},
			query:    "SELECT id FROM dst ORDER BY id",
			wantRows: [][]interface{}{{int64(2)}, {int64(3)}}},
		{name: "REQ-INSERT-022_insert_select_expr",
			setup: []string{
				"CREATE TABLE src(id INTEGER PRIMARY KEY, v INTEGER)",
				"INSERT INTO src VALUES(1,10),(2,20),(3,30)",
				"CREATE TABLE dst(id INTEGER PRIMARY KEY, v INTEGER)",
				"INSERT INTO dst SELECT id, v * 2 FROM src",
			},
			query:    "SELECT v FROM dst ORDER BY id",
			wantRows: [][]interface{}{{int64(20)}, {int64(40)}, {int64(60)}}},
		{name: "REQ-INSERT-023_insert_select_count",
			setup: []string{
				"CREATE TABLE src(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO src VALUES(1,'a'),(2,'b')",
				"CREATE TABLE dst(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO dst SELECT * FROM src",
			},
			query:    "SELECT v FROM dst ORDER BY id",
			wantRows: [][]interface{}{{"a"}, {"b"}}},
		{name: "REQ-INSERT-024_insert_select_agg",
			setup: []string{
				"CREATE TABLE src(id INTEGER PRIMARY KEY, v INTEGER)",
				"INSERT INTO src VALUES(1,10),(2,20),(3,30)",
				"CREATE TABLE dst(total INTEGER)",
				"INSERT INTO dst SELECT SUM(v) FROM src",
			},
			query:    "SELECT total FROM dst",
			wantRows: [][]interface{}{{int64(60)}}},
		{name: "REQ-INSERT-025_insert_select_limit",
			setup: []string{
				"CREATE TABLE src(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO src VALUES(1,'a'),(2,'b'),(3,'c'),(4,'d')",
				"CREATE TABLE dst(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO dst SELECT * FROM src ORDER BY id LIMIT 2",
			},
			query:    "SELECT v FROM dst ORDER BY id",
			wantRows: [][]interface{}{{"a"}, {"b"}}},
	}
}

func genTrinityInsertConflictTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-INSERT-030_or_replace",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO t1 VALUES(1,'old')",
				"INSERT OR REPLACE INTO t1 VALUES(1,'new')",
			},
			query:    "SELECT v FROM t1 WHERE id = 1",
			wantRows: [][]interface{}{{"new"}}},
		{name: "REQ-INSERT-031_or_ignore",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO t1 VALUES(1,'keep')",
				"INSERT OR IGNORE INTO t1 VALUES(1,'ignored')",
			},
			query:    "SELECT v FROM t1 WHERE id = 1",
			wantRows: [][]interface{}{{"keep"}}},
		{name: "REQ-INSERT-032_or_abort",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO t1 VALUES(1,'first')",
			},
			exec:    "INSERT OR ABORT INTO t1 VALUES(1,'dupe')",
			wantErr: true},
		{name: "REQ-INSERT-033_replace_count",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO t1 VALUES(1,'a')",
				"INSERT OR REPLACE INTO t1 VALUES(1,'b')",
			},
			query:    "SELECT COUNT(*) FROM t1",
			wantRows: [][]interface{}{{int64(1)}}},
		{name: "REQ-INSERT-034_ignore_unique",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT UNIQUE)",
				"INSERT INTO t1 VALUES(1,'x')",
				"INSERT OR IGNORE INTO t1 VALUES(2,'x')",
			},
			query:    "SELECT COUNT(*) FROM t1",
			wantRows: [][]interface{}{{int64(1)}}},
		{name: "REQ-INSERT-035_replace_unique_col",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT UNIQUE)",
				"INSERT INTO t1 VALUES(1,'a')",
				"INSERT INTO t1 VALUES(2,'b')",
				"INSERT OR REPLACE INTO t1 VALUES(3,'a')",
			},
			query:    "SELECT id, v FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{int64(2), "b"}, {int64(3), "a"}}},
		{name: "REQ-INSERT-036_ignore_preserves_existing",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO t1 VALUES(1,'original')",
				"INSERT OR IGNORE INTO t1 VALUES(1,'replacement')",
			},
			query:    "SELECT v FROM t1 WHERE id = 1",
			wantRows: [][]interface{}{{"original"}}},
	}
}

func genTrinityInsertAutoincTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-INSERT-040_autoincrement_basic",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY AUTOINCREMENT, v TEXT)",
				"INSERT INTO t1(v) VALUES('a')",
				"INSERT INTO t1(v) VALUES('b')",
			},
			query:    "SELECT id FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}},
		},
		{name: "REQ-INSERT-041_autoincrement_after_delete",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY AUTOINCREMENT, v TEXT)",
				"INSERT INTO t1(v) VALUES('a')",
				"INSERT INTO t1(v) VALUES('b')",
				"DELETE FROM t1 WHERE id = 2",
				"INSERT INTO t1(v) VALUES('c')",
			},
			query:    "SELECT id FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{int64(1)}, {int64(3)}},
		},
		{name: "REQ-INSERT-042_autoincrement_gap",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY AUTOINCREMENT, v TEXT)",
				"INSERT INTO t1(v) VALUES('a')",
				"INSERT INTO t1(v) VALUES('b')",
				"INSERT INTO t1(v) VALUES('c')",
				"DELETE FROM t1 WHERE id = 2",
				"INSERT INTO t1(v) VALUES('d')",
			},
			query:    "SELECT id, v FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{int64(1), "a"}, {int64(3), "c"}, {int64(4), "d"}},
		},
	}
}

func genTrinityInsertErrorTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-INSERT-050_duplicate_pk",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO t1 VALUES(1,'a')",
			},
			exec:    "INSERT INTO t1 VALUES(1,'b')",
			wantErr: true},
		{name: "REQ-INSERT-051_not_null_violation",
			setup:   []string{"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT NOT NULL)"},
			exec:    "INSERT INTO t1(id, v) VALUES(1, NULL)",
			wantErr: true},
		{name: "REQ-INSERT-052_unique_violation",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT UNIQUE)",
				"INSERT INTO t1 VALUES(1,'x')",
			},
			exec:    "INSERT INTO t1 VALUES(2,'x')",
			wantErr: true},
		{name: "REQ-INSERT-053_too_many_values",
			setup:   []string{"CREATE TABLE t1(id INTEGER, v TEXT)"},
			exec:    "INSERT INTO t1 VALUES(1, 'a', 'extra')",
			wantErr: true},
		{name: "REQ-INSERT-054_nonexistent_table",
			exec:    "INSERT INTO nonexistent VALUES(1)",
			wantErr: true},
		{name: "REQ-INSERT-055_type_mismatch_col_count",
			setup:   []string{"CREATE TABLE t1(id INTEGER PRIMARY KEY, a TEXT, b TEXT)"},
			exec:    "INSERT INTO t1(id, a) VALUES(1, 'x', 'y')",
			wantErr: true},
		{name: "REQ-INSERT-056_check_constraint",
			setup:   []string{"CREATE TABLE t1(id INTEGER PRIMARY KEY, age INTEGER CHECK(age >= 0))"},
			exec:    "INSERT INTO t1 VALUES(1, -1)",
			wantErr: true},
		{name: "REQ-INSERT-057_too_few_values",
			setup:   []string{"CREATE TABLE t1(id INTEGER, a TEXT, b TEXT NOT NULL)"},
			exec:    "INSERT INTO t1(id, a) VALUES(1, 'x')",
			wantErr: true,
			errLike: "NOT NULL"},
	}
}
