// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import (
	"fmt"
	"testing"
)

// TestTrinity_Update exercises UPDATE SET, UPDATE with WHERE, UPDATE with
// expressions, DELETE with WHERE, DELETE all, and error cases.
func TestTrinity_Update(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityUpdateTests())
}

func buildTrinityUpdateTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genTrinityUpdateBasicTests()...)
	tests = append(tests, genTrinityUpdateExprTests()...)
	tests = append(tests, genTrinityDeleteTests()...)
	tests = append(tests, genTrinityUpdateErrorTests()...)
	return tests
}

var trinityUpdateSetup = []string{
	"CREATE TABLE t1(id INTEGER PRIMARY KEY, name TEXT, age INTEGER, score REAL)",
	"INSERT INTO t1 VALUES(1, 'Alice', 30, 95.5)",
	"INSERT INTO t1 VALUES(2, 'Bob', 25, 87.0)",
	"INSERT INTO t1 VALUES(3, 'Carol', 35, 92.0)",
	"INSERT INTO t1 VALUES(4, 'Dave', 25, 78.5)",
	"INSERT INTO t1 VALUES(5, 'Eve', 30, 88.0)",
}

func genTrinityUpdateBasicTests() []sqlTestCase {
	type updateCase struct {
		desc   string
		update string
		query  string
		want   [][]interface{}
	}
	cases := []updateCase{
		{"set_single_col",
			"UPDATE t1 SET name = 'Alicia' WHERE id = 1",
			"SELECT name FROM t1 WHERE id = 1",
			[][]interface{}{{"Alicia"}}},
		{"set_multi_col",
			"UPDATE t1 SET name = 'Robert', age = 26 WHERE id = 2",
			"SELECT name, age FROM t1 WHERE id = 2",
			[][]interface{}{{"Robert", int64(26)}}},
		{"set_all_rows",
			"UPDATE t1 SET score = 100.0",
			"SELECT DISTINCT score FROM t1",
			[][]interface{}{{100.0}}},
		{"set_with_where_gt",
			"UPDATE t1 SET score = 0.0 WHERE age > 28",
			"SELECT id FROM t1 WHERE score = 0.0 ORDER BY id",
			[][]interface{}{{int64(1)}, {int64(3)}, {int64(5)}}},
		{"set_with_where_eq",
			"UPDATE t1 SET age = 26 WHERE age = 25",
			"SELECT id FROM t1 WHERE age = 26 ORDER BY id",
			[][]interface{}{{int64(2)}, {int64(4)}}},
		{"set_to_null",
			"UPDATE t1 SET name = NULL WHERE id = 1",
			"SELECT name FROM t1 WHERE id = 1",
			[][]interface{}{{nil}}},
		{"set_where_in",
			"UPDATE t1 SET score = 99.0 WHERE id IN (1, 3, 5)",
			"SELECT id, score FROM t1 WHERE score = 99.0 ORDER BY id",
			[][]interface{}{{int64(1), 99.0}, {int64(3), 99.0}, {int64(5), 99.0}}},
		{"set_where_between",
			"UPDATE t1 SET name = 'X' WHERE age BETWEEN 25 AND 30",
			"SELECT COUNT(*) FROM t1 WHERE name = 'X'",
			[][]interface{}{{int64(4)}}},
		{"set_where_like",
			"UPDATE t1 SET age = 99 WHERE name LIKE 'A%'",
			"SELECT age FROM t1 WHERE id = 1",
			[][]interface{}{{int64(99)}}},
		{"set_no_match",
			"UPDATE t1 SET name = 'Nobody' WHERE id = 999",
			"SELECT COUNT(*) FROM t1 WHERE name = 'Nobody'",
			[][]interface{}{{int64(0)}}},
		{"set_where_or",
			"UPDATE t1 SET score = 0.0 WHERE id = 1 OR id = 5",
			"SELECT id FROM t1 WHERE score = 0.0 ORDER BY id",
			[][]interface{}{{int64(1)}, {int64(5)}}},
		{"set_where_not",
			"UPDATE t1 SET age = 99 WHERE NOT age = 25",
			"SELECT COUNT(*) FROM t1 WHERE age = 99",
			[][]interface{}{{int64(3)}}},
		{"set_multiple_all",
			"UPDATE t1 SET name = 'Z', age = 0, score = 0.0",
			"SELECT DISTINCT name, age, score FROM t1",
			[][]interface{}{{"Z", int64(0), 0.0}}},
	}
	var tests []sqlTestCase
	for i, c := range cases {
		tests = append(tests, sqlTestCase{
			name:     fmt.Sprintf("REQ-UPDATE-%03d_%s", i+1, c.desc),
			setup:    append(append([]string{}, trinityUpdateSetup...), c.update),
			query:    c.query,
			wantRows: c.want,
		})
	}
	return tests
}

func genTrinityUpdateExprTests() []sqlTestCase {
	type exprCase struct {
		desc   string
		update string
		query  string
		want   [][]interface{}
	}
	cases := []exprCase{
		{"increment",
			"UPDATE t1 SET age = age + 1 WHERE id = 1",
			"SELECT age FROM t1 WHERE id = 1",
			[][]interface{}{{int64(31)}}},
		{"decrement",
			"UPDATE t1 SET age = age - 5 WHERE id = 3",
			"SELECT age FROM t1 WHERE id = 3",
			[][]interface{}{{int64(30)}}},
		{"multiply",
			"UPDATE t1 SET score = score * 2 WHERE id = 4",
			"SELECT score FROM t1 WHERE id = 4",
			[][]interface{}{{157.0}}},
		{"string_concat",
			"UPDATE t1 SET name = name || '_updated' WHERE id = 2",
			"SELECT name FROM t1 WHERE id = 2",
			[][]interface{}{{"Bob_updated"}}},
		{"case_expr",
			"UPDATE t1 SET score = CASE WHEN age >= 30 THEN 100.0 ELSE 50.0 END",
			"SELECT id, score FROM t1 ORDER BY id",
			[][]interface{}{{int64(1), 100.0}, {int64(2), 50.0}, {int64(3), 100.0}, {int64(4), 50.0}, {int64(5), 100.0}}},
		{"coalesce_expr",
			"UPDATE t1 SET name = COALESCE(NULL, name, 'default') WHERE id = 1",
			"SELECT name FROM t1 WHERE id = 1",
			[][]interface{}{{"Alice"}}},
		{"abs_expr",
			"UPDATE t1 SET age = ABS(age - 100) WHERE id = 1",
			"SELECT age FROM t1 WHERE id = 1",
			[][]interface{}{{int64(70)}}},
		{"set_from_subquery",
			"UPDATE t1 SET score = (SELECT MAX(score) FROM t1) WHERE id = 4",
			"SELECT score FROM t1 WHERE id = 4",
			[][]interface{}{{95.5}}},
		{"modulo_expr",
			"UPDATE t1 SET age = age % 10 WHERE id = 3",
			"SELECT age FROM t1 WHERE id = 3",
			[][]interface{}{{int64(5)}}},
		{"nested_case",
			"UPDATE t1 SET name = CASE WHEN age = 25 THEN 'young' WHEN age = 30 THEN 'mid' ELSE 'senior' END",
			"SELECT name FROM t1 ORDER BY id",
			[][]interface{}{{"mid"}, {"young"}, {"senior"}, {"young"}, {"mid"}}},
		{"length_expr",
			"UPDATE t1 SET age = LENGTH(name) WHERE id = 1",
			"SELECT age FROM t1 WHERE id = 1",
			[][]interface{}{{int64(5)}}},
		{"replace_func",
			"UPDATE t1 SET name = REPLACE(name, 'o', '0') WHERE id = 2",
			"SELECT name FROM t1 WHERE id = 2",
			[][]interface{}{{"B0b"}}},
	}
	var tests []sqlTestCase
	for i, c := range cases {
		tests = append(tests, sqlTestCase{
			name:     fmt.Sprintf("REQ-UPDATE-%03d_%s", i+20, c.desc),
			setup:    append(append([]string{}, trinityUpdateSetup...), c.update),
			query:    c.query,
			wantRows: c.want,
		})
	}
	return tests
}

func genTrinityDeleteTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-UPDATE-030_delete_by_id",
			setup:    append(append([]string{}, trinityUpdateSetup...), "DELETE FROM t1 WHERE id = 3"),
			query:    "SELECT COUNT(*) FROM t1",
			wantRows: [][]interface{}{{int64(4)}}},
		{name: "REQ-UPDATE-031_delete_where_gt",
			setup:    append(append([]string{}, trinityUpdateSetup...), "DELETE FROM t1 WHERE age > 28"),
			query:    "SELECT id FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{int64(2)}, {int64(4)}}},
		{name: "REQ-UPDATE-032_delete_all",
			setup:    append(append([]string{}, trinityUpdateSetup...), "DELETE FROM t1"),
			query:    "SELECT COUNT(*) FROM t1",
			wantRows: [][]interface{}{{int64(0)}}},
		{name: "REQ-UPDATE-033_delete_where_in",
			setup:    append(append([]string{}, trinityUpdateSetup...), "DELETE FROM t1 WHERE id IN (1, 3, 5)"),
			query:    "SELECT id FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{int64(2)}, {int64(4)}}},
		{name: "REQ-UPDATE-034_delete_where_like",
			setup:    append(append([]string{}, trinityUpdateSetup...), "DELETE FROM t1 WHERE name LIKE '%e'"),
			query:    "SELECT id FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{int64(2)}, {int64(3)}}},
		{name: "REQ-UPDATE-035_delete_no_match",
			setup:    append(append([]string{}, trinityUpdateSetup...), "DELETE FROM t1 WHERE id = 999"),
			query:    "SELECT COUNT(*) FROM t1",
			wantRows: [][]interface{}{{int64(5)}}},
		{name: "REQ-UPDATE-036_delete_where_and",
			setup:    append(append([]string{}, trinityUpdateSetup...), "DELETE FROM t1 WHERE age = 25 AND score < 80"),
			query:    "SELECT id FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}, {int64(3)}, {int64(5)}}},
		{name: "REQ-UPDATE-037_delete_where_between",
			setup:    append(append([]string{}, trinityUpdateSetup...), "DELETE FROM t1 WHERE score BETWEEN 88.0 AND 95.5"),
			query:    "SELECT id FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{int64(2)}, {int64(4)}}},
		{name: "REQ-UPDATE-038_delete_then_count",
			setup: append(append([]string{}, trinityUpdateSetup...),
				"DELETE FROM t1 WHERE age = 30",
				"DELETE FROM t1 WHERE age = 25"),
			query:    "SELECT COUNT(*) FROM t1",
			wantRows: [][]interface{}{{int64(1)}}},
		{name: "REQ-UPDATE-039_delete_where_or",
			setup:    append(append([]string{}, trinityUpdateSetup...), "DELETE FROM t1 WHERE id = 1 OR id = 5"),
			query:    "SELECT id FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{int64(2)}, {int64(3)}, {int64(4)}}},
		{name: "REQ-UPDATE-039b_delete_where_not",
			setup:    append(append([]string{}, trinityUpdateSetup...), "DELETE FROM t1 WHERE NOT id = 3"),
			query:    "SELECT id FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{int64(3)}}},
		{name: "REQ-UPDATE-039c_delete_where_null",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO t1 VALUES(1, 'a')",
				"INSERT INTO t1 VALUES(2, NULL)",
				"INSERT INTO t1 VALUES(3, 'c')",
				"DELETE FROM t1 WHERE v IS NULL",
			},
			query:    "SELECT id FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{int64(1)}, {int64(3)}}},
		{name: "REQ-UPDATE-039d_delete_subquery",
			skip: "pre-existing: DELETE with subquery not yet implemented",
			setup: append(append([]string{}, trinityUpdateSetup...),
				"DELETE FROM t1 WHERE score < (SELECT AVG(score) FROM t1)"),
			query:    "SELECT id FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{int64(1)}, {int64(3)}, {int64(5)}}},
	}
}

func genTrinityUpdateErrorTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-UPDATE-040_update_nonexistent_table",
			exec:    "UPDATE nonexistent SET v = 1",
			wantErr: true},
		{name: "REQ-UPDATE-041_update_nonexistent_col",
			setup:   trinityUpdateSetup,
			exec:    "UPDATE t1 SET nonexistent = 1",
			wantErr: true},
		{name: "REQ-UPDATE-042_delete_nonexistent_table",
			exec:    "DELETE FROM nonexistent",
			wantErr: true},
		{name: "REQ-UPDATE-043_not_null_violation",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT NOT NULL)",
				"INSERT INTO t1 VALUES(1, 'a')",
			},
			exec:    "UPDATE t1 SET v = NULL WHERE id = 1",
			wantErr: true},
		{name: "REQ-UPDATE-044_check_constraint",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, age INTEGER CHECK(age >= 0))",
				"INSERT INTO t1 VALUES(1, 10)",
			},
			exec:    "UPDATE t1 SET age = -1 WHERE id = 1",
			wantErr: true},
		{name: "REQ-UPDATE-045_unique_violation",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT UNIQUE)",
				"INSERT INTO t1 VALUES(1, 'a')",
				"INSERT INTO t1 VALUES(2, 'b')",
			},
			exec:    "UPDATE t1 SET v = 'a' WHERE id = 2",
			wantErr: true},
		{name: "REQ-UPDATE-046_delete_where_type_mismatch",
			setup:    trinityUpdateSetup,
			exec:     "DELETE FROM t1 WHERE id = 'not_a_number'",
			query:    "SELECT COUNT(*) FROM t1",
			wantRows: [][]interface{}{{int64(5)}}},
		{name: "REQ-UPDATE-047_update_pk_duplicate",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO t1 VALUES(1, 'a')",
				"INSERT INTO t1 VALUES(2, 'b')",
			},
			exec:    "UPDATE t1 SET id = 1 WHERE id = 2",
			wantErr: true},
	}
}
