// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import (
	"fmt"
	"testing"
)

// TestTrinity_Select exercises SELECT forms, WHERE predicates, ORDER BY,
// LIMIT/OFFSET, DISTINCT, GROUP BY/HAVING, and subqueries.
func TestTrinity_Select(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinitySelectTests())
}

func buildTrinitySelectTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genTrinitySelectBasicTests()...)
	tests = append(tests, genTrinitySelectWhereTests()...)
	tests = append(tests, genTrinitySelectOrderByTests()...)
	tests = append(tests, genTrinitySelectLimitOffsetTests()...)
	tests = append(tests, genTrinitySelectDistinctTests()...)
	tests = append(tests, genTrinitySelectGroupByHavingTests()...)
	tests = append(tests, genTrinitySelectSubqueryTests()...)
	return tests
}

var trinitySelectSetup = []string{
	"CREATE TABLE t1(id INTEGER PRIMARY KEY, name TEXT, age INTEGER, score REAL)",
	"INSERT INTO t1 VALUES(1, 'Alice', 30, 95.5)",
	"INSERT INTO t1 VALUES(2, 'Bob', 25, 87.0)",
	"INSERT INTO t1 VALUES(3, 'Carol', 35, 92.0)",
	"INSERT INTO t1 VALUES(4, 'Dave', 25, 78.5)",
	"INSERT INTO t1 VALUES(5, 'Eve', 30, 88.0)",
}

func genTrinitySelectBasicTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-SELECT-001_basic_star", setup: trinitySelectSetup,
			query:    "SELECT * FROM t1 WHERE id = 1",
			wantRows: [][]interface{}{{int64(1), "Alice", int64(30), 95.5}}},
		{name: "REQ-SELECT-002_named_cols", setup: trinitySelectSetup,
			query:    "SELECT name, age FROM t1 WHERE id = 2",
			wantRows: [][]interface{}{{"Bob", int64(25)}}},
		{name: "REQ-SELECT-003_alias", setup: trinitySelectSetup,
			query:    "SELECT name AS n, age AS a FROM t1 WHERE id = 1",
			wantRows: [][]interface{}{{"Alice", int64(30)}}},
		{name: "REQ-SELECT-004_expr_col", setup: trinitySelectSetup,
			query:    "SELECT age + 1 FROM t1 WHERE id = 1",
			wantRows: [][]interface{}{{int64(31)}}},
		{name: "REQ-SELECT-005_literal_values",
			query:    "SELECT 42, 'hello', 3.14",
			wantRows: [][]interface{}{{int64(42), "hello", 3.14}}},
		{name: "REQ-SELECT-006_count_star", setup: trinitySelectSetup,
			query:    "SELECT COUNT(*) FROM t1",
			wantRows: [][]interface{}{{int64(5)}}},
		{name: "REQ-SELECT-007_empty_table",
			setup:    []string{"CREATE TABLE t1(id INTEGER)"},
			query:    "SELECT * FROM t1",
			wantRows: [][]interface{}{}},
		{name: "REQ-SELECT-008_select_null",
			query:    "SELECT NULL",
			wantRows: [][]interface{}{{nil}}},
		{name: "REQ-SELECT-009_coalesce", setup: trinitySelectSetup,
			query:    "SELECT COALESCE(NULL, name) FROM t1 WHERE id = 1",
			wantRows: [][]interface{}{{"Alice"}}},
	}
}

func genTrinitySelectWhereTests() []sqlTestCase {
	type whereCase struct {
		desc  string
		where string
		ids   []int64
	}
	cases := []whereCase{
		{"eq", "age = 30", []int64{1, 5}},
		{"ne", "age != 30", []int64{2, 3, 4}},
		{"lt", "age < 30", []int64{2, 4}},
		{"gt", "age > 30", []int64{3}},
		{"le", "age <= 25", []int64{2, 4}},
		{"ge", "age >= 35", []int64{3}},
		{"and", "age = 25 AND score > 80", []int64{2}},
		{"or", "age = 35 OR age = 25", []int64{2, 3, 4}},
		{"not", "NOT age = 30", []int64{2, 3, 4}},
		{"between", "age BETWEEN 26 AND 34", []int64{1, 5}},
		{"in_list", "age IN (25, 35)", []int64{2, 3, 4}},
		{"is_not_null", "name IS NOT NULL", []int64{1, 2, 3, 4, 5}},
		{"like", "name LIKE 'A%'", []int64{1}},
		{"glob_pattern", "name GLOB 'B*'", []int64{2}},
	}
	var tests []sqlTestCase
	for i, c := range cases {
		name := fmt.Sprintf("REQ-SELECT-%03d_where_%s", i+10, c.desc)
		var rows [][]interface{}
		for _, id := range c.ids {
			rows = append(rows, []interface{}{id})
		}
		tests = append(tests, sqlTestCase{
			name:     name,
			setup:    trinitySelectSetup,
			query:    fmt.Sprintf("SELECT id FROM t1 WHERE %s ORDER BY id", c.where),
			wantRows: rows,
		})
	}
	return tests
}

func genTrinitySelectOrderByTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-SELECT-030_order_asc", setup: trinitySelectSetup,
			query:    "SELECT id FROM t1 ORDER BY age ASC, id ASC",
			wantRows: [][]interface{}{{int64(2)}, {int64(4)}, {int64(1)}, {int64(5)}, {int64(3)}}},
		{name: "REQ-SELECT-031_order_desc", setup: trinitySelectSetup,
			query:    "SELECT id FROM t1 ORDER BY age DESC, id ASC",
			wantRows: [][]interface{}{{int64(3)}, {int64(1)}, {int64(5)}, {int64(2)}, {int64(4)}}},
		{name: "REQ-SELECT-032_order_by_expr", setup: trinitySelectSetup,
			query:    "SELECT id FROM t1 ORDER BY score - age LIMIT 1",
			wantRows: [][]interface{}{{int64(4)}}},
		{name: "REQ-SELECT-033_order_by_col_number", setup: trinitySelectSetup,
			query:    "SELECT name, age FROM t1 ORDER BY 2 ASC, 1 ASC LIMIT 2",
			wantRows: [][]interface{}{{"Bob", int64(25)}, {"Dave", int64(25)}}},
		{name: "REQ-SELECT-034_order_multi_col", setup: trinitySelectSetup,
			query:    "SELECT name FROM t1 ORDER BY age ASC, score DESC",
			wantRows: [][]interface{}{{"Bob"}, {"Dave"}, {"Alice"}, {"Eve"}, {"Carol"}}},
		{name: "REQ-SELECT-035_order_nulls",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, v TEXT)",
				"INSERT INTO t1 VALUES(1, 'b')",
				"INSERT INTO t1 VALUES(2, NULL)",
				"INSERT INTO t1 VALUES(3, 'a')",
			},
			query:    "SELECT id FROM t1 ORDER BY v ASC",
			wantRows: [][]interface{}{{int64(2)}, {int64(3)}, {int64(1)}}},
	}
}

func genTrinitySelectLimitOffsetTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-SELECT-040_limit", setup: trinitySelectSetup,
			query:    "SELECT id FROM t1 ORDER BY id LIMIT 3",
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}, {int64(3)}}},
		{name: "REQ-SELECT-041_limit_offset", setup: trinitySelectSetup,
			query:    "SELECT id FROM t1 ORDER BY id LIMIT 2 OFFSET 2",
			wantRows: [][]interface{}{{int64(3)}, {int64(4)}}},
		{name: "REQ-SELECT-042_limit_exceeds", setup: trinitySelectSetup,
			query:    "SELECT id FROM t1 ORDER BY id LIMIT 100",
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}, {int64(3)}, {int64(4)}, {int64(5)}}},
		{name: "REQ-SELECT-043_offset_past_end", setup: trinitySelectSetup,
			query:    "SELECT id FROM t1 ORDER BY id LIMIT 10 OFFSET 5",
			wantRows: [][]interface{}{}},
		{name: "REQ-SELECT-044_limit_zero", setup: trinitySelectSetup,
			query:    "SELECT id FROM t1 ORDER BY id LIMIT 0",
			wantRows: [][]interface{}{}},
		{name: "REQ-SELECT-045_offset_one", setup: trinitySelectSetup,
			query:    "SELECT id FROM t1 ORDER BY id LIMIT 1 OFFSET 1",
			wantRows: [][]interface{}{{int64(2)}}},
	}
}

func genTrinitySelectDistinctTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-SELECT-050_distinct_values", setup: trinitySelectSetup,
			query:    "SELECT DISTINCT age FROM t1 ORDER BY age",
			wantRows: [][]interface{}{{int64(25)}, {int64(30)}, {int64(35)}}},
		{name: "REQ-SELECT-051_distinct_no_dupes", setup: trinitySelectSetup,
			query:    "SELECT DISTINCT id FROM t1 ORDER BY id",
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}, {int64(3)}, {int64(4)}, {int64(5)}}},
		{name: "REQ-SELECT-052_distinct_multi_col", setup: trinitySelectSetup,
			query:    "SELECT DISTINCT age, name FROM t1 WHERE age = 25 ORDER BY name",
			wantRows: [][]interface{}{{int64(25), "Bob"}, {int64(25), "Dave"}}},
		{name: "REQ-SELECT-053_distinct_null",
			setup: []string{
				"CREATE TABLE t1(v TEXT)",
				"INSERT INTO t1 VALUES('a')",
				"INSERT INTO t1 VALUES(NULL)",
				"INSERT INTO t1 VALUES('a')",
				"INSERT INTO t1 VALUES(NULL)",
			},
			query:    "SELECT DISTINCT v FROM t1 ORDER BY v",
			wantRows: [][]interface{}{{nil}, {"a"}}},
	}
}

func genTrinitySelectGroupByHavingTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-SELECT-060_group_by_count", setup: trinitySelectSetup,
			query:    "SELECT age, COUNT(*) FROM t1 GROUP BY age ORDER BY age",
			wantRows: [][]interface{}{{int64(25), int64(2)}, {int64(30), int64(2)}, {int64(35), int64(1)}}},
		{name: "REQ-SELECT-061_group_by_sum", setup: trinitySelectSetup,
			query:    "SELECT age, SUM(score) FROM t1 GROUP BY age ORDER BY age",
			wantRows: [][]interface{}{{int64(25), 165.5}, {int64(30), 183.5}, {int64(35), 92.0}}},
		{name: "REQ-SELECT-062_having_filter", skip: "pre-existing: HAVING clause edge case", setup: trinitySelectSetup,
			query:    "SELECT age, COUNT(*) AS cnt FROM t1 GROUP BY age HAVING cnt > 1 ORDER BY age",
			wantRows: [][]interface{}{{int64(25), int64(2)}, {int64(30), int64(2)}}},
		{name: "REQ-SELECT-063_group_by_avg", setup: trinitySelectSetup,
			query:    "SELECT age, AVG(score) FROM t1 GROUP BY age ORDER BY age",
			wantRows: [][]interface{}{{int64(25), 82.75}, {int64(30), 91.75}, {int64(35), 92.0}}},
		{name: "REQ-SELECT-064_group_by_min_max", setup: trinitySelectSetup,
			query:    "SELECT age, MIN(score), MAX(score) FROM t1 GROUP BY age ORDER BY age",
			wantRows: [][]interface{}{{int64(25), 78.5, 87.0}, {int64(30), 88.0, 95.5}, {int64(35), 92.0, 92.0}}},
		{name: "REQ-SELECT-065_having_sum", skip: "pre-existing: HAVING clause edge case", setup: trinitySelectSetup,
			query:    "SELECT age, SUM(score) AS total FROM t1 GROUP BY age HAVING total > 170 ORDER BY age",
			wantRows: [][]interface{}{{int64(30), 183.5}}},
		{name: "REQ-SELECT-066_group_by_expr", setup: trinitySelectSetup,
			query:    "SELECT age > 28 AS senior, COUNT(*) FROM t1 GROUP BY senior ORDER BY senior",
			wantRows: [][]interface{}{{int64(0), int64(2)}, {int64(1), int64(3)}}},
	}
}

func genTrinitySelectSubqueryTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-SELECT-070_scalar_subquery", setup: trinitySelectSetup,
			query:    "SELECT name FROM t1 WHERE age = (SELECT MAX(age) FROM t1)",
			wantRows: [][]interface{}{{"Carol"}}},
		{name: "REQ-SELECT-071_in_subquery", setup: trinitySelectSetup,
			query:    "SELECT name FROM t1 WHERE age IN (SELECT DISTINCT age FROM t1 WHERE age < 30) ORDER BY name",
			wantRows: [][]interface{}{{"Bob"}, {"Dave"}}},
		{name: "REQ-SELECT-072_exists_subquery", setup: trinitySelectSetup,
			query:    "SELECT name FROM t1 AS a WHERE EXISTS (SELECT 1 FROM t1 AS b WHERE b.age = a.age AND b.id != a.id) ORDER BY name",
			wantRows: [][]interface{}{{"Alice"}, {"Bob"}, {"Dave"}, {"Eve"}}},
		{name: "REQ-SELECT-073_from_subquery", setup: trinitySelectSetup,
			query:    "SELECT s.name FROM (SELECT * FROM t1 WHERE age > 28) AS s ORDER BY s.name",
			wantRows: [][]interface{}{{"Alice"}, {"Carol"}, {"Eve"}}},
		{name: "REQ-SELECT-074_not_in_subquery", setup: trinitySelectSetup,
			query:    "SELECT name FROM t1 WHERE age NOT IN (SELECT age FROM t1 WHERE age = 25) ORDER BY name",
			wantRows: [][]interface{}{{"Alice"}, {"Carol"}, {"Eve"}}},
		{name: "REQ-SELECT-075_not_exists", setup: trinitySelectSetup,
			query:    "SELECT name FROM t1 AS a WHERE NOT EXISTS (SELECT 1 FROM t1 AS b WHERE b.age = a.age AND b.id != a.id) ORDER BY name",
			wantRows: [][]interface{}{{"Carol"}}},
		{name: "REQ-SELECT-076_correlated_subquery", setup: trinitySelectSetup,
			query:    "SELECT name, (SELECT COUNT(*) FROM t1 AS b WHERE b.age = a.age) AS peers FROM t1 AS a WHERE id = 3",
			wantRows: [][]interface{}{{"Carol", int64(1)}}},
		{name: "REQ-SELECT-077_subquery_comparison", setup: trinitySelectSetup,
			query:    "SELECT name FROM t1 WHERE score > (SELECT AVG(score) FROM t1) ORDER BY name",
			wantRows: [][]interface{}{{"Alice"}, {"Carol"}}},
	}
}
