// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import (
	"fmt"
	"testing"
)

// TestTrinity_Join exercises INNER JOIN, LEFT JOIN, CROSS JOIN, self-join,
// NULL join keys, NATURAL JOIN, USING clause, and multi-table joins.
func TestTrinity_Join(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityJoinTests())
}

func buildTrinityJoinTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genJoinInnerTests()...)
	tests = append(tests, genJoinLeftTests()...)
	tests = append(tests, genJoinCrossTests()...)
	tests = append(tests, genJoinSelfTests()...)
	tests = append(tests, genJoinNullKeyTests()...)
	tests = append(tests, genJoinNaturalUsingTests()...)
	tests = append(tests, genJoinMultiTableTests()...)
	return tests
}

// joinSetupEmployees creates employees and departments tables.
var joinSetupEmployees = []string{
	"CREATE TABLE dept(id INTEGER PRIMARY KEY, name TEXT)",
	"INSERT INTO dept VALUES(1, 'Engineering')",
	"INSERT INTO dept VALUES(2, 'Marketing')",
	"INSERT INTO dept VALUES(3, 'Sales')",
	"CREATE TABLE emp(id INTEGER PRIMARY KEY, name TEXT, dept_id INTEGER)",
	"INSERT INTO emp VALUES(1, 'Alice', 1)",
	"INSERT INTO emp VALUES(2, 'Bob', 1)",
	"INSERT INTO emp VALUES(3, 'Carol', 2)",
	"INSERT INTO emp VALUES(4, 'Dave', NULL)",
}

func genJoinInnerTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-JOIN-001_inner_basic",
			setup:    joinSetupEmployees,
			query:    "SELECT emp.name, dept.name FROM emp INNER JOIN dept ON emp.dept_id = dept.id ORDER BY emp.name",
			wantRows: [][]interface{}{{"Alice", "Engineering"}, {"Bob", "Engineering"}, {"Carol", "Marketing"}}},
		{name: "REQ-JOIN-002_inner_excludes_null_fk",

			setup:    joinSetupEmployees,
			query:    "SELECT COUNT(*) FROM emp INNER JOIN dept ON emp.dept_id = dept.id",
			wantRows: [][]interface{}{{int64(3)}}},
		{name: "REQ-JOIN-003_inner_with_where",
			setup:    joinSetupEmployees,
			query:    "SELECT emp.name FROM emp INNER JOIN dept ON emp.dept_id = dept.id WHERE dept.name = 'Engineering' ORDER BY emp.name",
			wantRows: [][]interface{}{{"Alice"}, {"Bob"}}},
		{name: "REQ-JOIN-004_inner_implicit",
			setup:    joinSetupEmployees,
			query:    "SELECT emp.name, dept.name FROM emp, dept WHERE emp.dept_id = dept.id ORDER BY emp.name",
			wantRows: [][]interface{}{{"Alice", "Engineering"}, {"Bob", "Engineering"}, {"Carol", "Marketing"}}},
		{name: "REQ-JOIN-005_inner_no_match",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, val TEXT)",
				"CREATE TABLE t2(id INTEGER PRIMARY KEY, t1_id INTEGER)",
				"INSERT INTO t1 VALUES(1, 'a')",
				"INSERT INTO t2 VALUES(1, 99)",
			},
			query:    "SELECT COUNT(*) FROM t1 INNER JOIN t2 ON t1.id = t2.t1_id",
			wantRows: [][]interface{}{{int64(0)}}},
		{name: "REQ-JOIN-006_inner_empty_table",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY)",
				"CREATE TABLE t2(id INTEGER PRIMARY KEY, ref INTEGER)",
				"INSERT INTO t1 VALUES(1)",
			},
			query:    "SELECT COUNT(*) FROM t1 INNER JOIN t2 ON t1.id = t2.ref",
			wantRows: [][]interface{}{{int64(0)}}},
		{name: "REQ-JOIN-007_inner_self_referential",
			setup:    joinSetupEmployees,
			query:    "SELECT e1.name FROM emp e1 JOIN emp e2 ON e1.dept_id = e2.dept_id WHERE e1.id != e2.id ORDER BY e1.name",
			wantRows: [][]interface{}{{"Alice"}, {"Bob"}}},
	}
}

func genJoinLeftTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-JOIN-010_left_basic",
			setup: joinSetupEmployees,
			query: "SELECT emp.name, dept.name FROM emp LEFT JOIN dept ON emp.dept_id = dept.id ORDER BY emp.name",
			wantRows: [][]interface{}{
				{"Alice", "Engineering"}, {"Bob", "Engineering"},
				{"Carol", "Marketing"}, {"Dave", nil},
			}},
		{name: "REQ-JOIN-011_left_includes_unmatched",
			setup:    joinSetupEmployees,
			query:    "SELECT COUNT(*) FROM emp LEFT JOIN dept ON emp.dept_id = dept.id",
			wantRows: [][]interface{}{{int64(4)}}},
		{name: "REQ-JOIN-012_left_null_columns",
			setup:    joinSetupEmployees,
			query:    "SELECT emp.name, dept.name FROM emp LEFT JOIN dept ON emp.dept_id = dept.id WHERE dept.name IS NULL",
			wantRows: [][]interface{}{{"Dave", nil}}},
		{name: "REQ-JOIN-013_left_with_aggregate",
			setup: joinSetupEmployees,
			query: "SELECT dept.name, COUNT(emp.id) AS cnt FROM dept LEFT JOIN emp ON dept.id = emp.dept_id GROUP BY dept.name ORDER BY dept.name",
			wantRows: [][]interface{}{
				{"Engineering", int64(2)}, {"Marketing", int64(1)}, {"Sales", int64(0)},
			}},
		{name: "REQ-JOIN-014_left_both_empty",
			setup: []string{
				"CREATE TABLE t1(id INTEGER)", "CREATE TABLE t2(id INTEGER, ref INTEGER)",
			},
			query:    "SELECT COUNT(*) FROM t1 LEFT JOIN t2 ON t1.id = t2.ref",
			wantRows: [][]interface{}{{int64(0)}}},
		{name: "REQ-JOIN-015_left_right_empty",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY)",
				"CREATE TABLE t2(id INTEGER PRIMARY KEY, ref INTEGER)",
				"INSERT INTO t1 VALUES(1)", "INSERT INTO t1 VALUES(2)",
			},
			query:    "SELECT t1.id, t2.ref FROM t1 LEFT JOIN t2 ON t1.id = t2.ref ORDER BY t1.id",
			wantRows: [][]interface{}{{int64(1), nil}, {int64(2), nil}}},
		{name: "REQ-JOIN-016_left_with_order_limit",
			setup:    joinSetupEmployees,
			query:    "SELECT emp.name FROM emp LEFT JOIN dept ON emp.dept_id = dept.id ORDER BY emp.name LIMIT 2",
			wantRows: [][]interface{}{{"Alice"}, {"Bob"}}},
	}
}

func genJoinCrossTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-JOIN-020_cross_basic",
			setup: []string{
				"CREATE TABLE t1(x TEXT)", "INSERT INTO t1 VALUES('a')", "INSERT INTO t1 VALUES('b')",
				"CREATE TABLE t2(y TEXT)", "INSERT INTO t2 VALUES('1')", "INSERT INTO t2 VALUES('2')",
			},
			query:    "SELECT COUNT(*) FROM t1 CROSS JOIN t2",
			wantRows: [][]interface{}{{int64(4)}}},
		{name: "REQ-JOIN-021_cross_explicit_rows",
			setup: []string{
				"CREATE TABLE colors(c TEXT)", "INSERT INTO colors VALUES('R')", "INSERT INTO colors VALUES('G')",
				"CREATE TABLE sizes(s TEXT)", "INSERT INTO sizes VALUES('S')", "INSERT INTO sizes VALUES('L')",
			},
			query: "SELECT c, s FROM colors CROSS JOIN sizes ORDER BY c, s",
			wantRows: [][]interface{}{
				{"G", "L"}, {"G", "S"}, {"R", "L"}, {"R", "S"},
			}},
		{name: "REQ-JOIN-022_cross_one_empty",
			setup: []string{
				"CREATE TABLE t1(x TEXT)", "INSERT INTO t1 VALUES('a')",
				"CREATE TABLE t2(y TEXT)",
			},
			query:    "SELECT COUNT(*) FROM t1 CROSS JOIN t2",
			wantRows: [][]interface{}{{int64(0)}}},
		{name: "REQ-JOIN-023_cross_single_row_each",
			setup: []string{
				"CREATE TABLE t1(x INTEGER)", "INSERT INTO t1 VALUES(10)",
				"CREATE TABLE t2(y INTEGER)", "INSERT INTO t2 VALUES(20)",
			},
			query:    "SELECT x + y FROM t1 CROSS JOIN t2",
			wantRows: [][]interface{}{{int64(30)}}},
	}
}

func genJoinSelfTests() []sqlTestCase {
	orgSetup := []string{
		"CREATE TABLE org(id INTEGER PRIMARY KEY, name TEXT, mgr_id INTEGER)",
		"INSERT INTO org VALUES(1, 'CEO', NULL)",
		"INSERT INTO org VALUES(2, 'VP', 1)",
		"INSERT INTO org VALUES(3, 'Dev', 2)",
		"INSERT INTO org VALUES(4, 'QA', 2)",
	}
	return []sqlTestCase{
		{name: "REQ-JOIN-030_self_join_hierarchy",
			setup: orgSetup,
			query: "SELECT e.name AS employee, m.name AS manager FROM org e JOIN org m ON e.mgr_id = m.id ORDER BY e.name",
			wantRows: [][]interface{}{
				{"Dev", "VP"}, {"QA", "VP"}, {"VP", "CEO"},
			}},
		{name: "REQ-JOIN-031_self_join_left",
			setup: orgSetup,
			query: "SELECT e.name, m.name FROM org e LEFT JOIN org m ON e.mgr_id = m.id ORDER BY e.name",
			wantRows: [][]interface{}{
				{"CEO", nil}, {"Dev", "VP"}, {"QA", "VP"}, {"VP", "CEO"},
			}},
		{name: "REQ-JOIN-032_self_join_count_reports",

			setup: orgSetup,
			query: "SELECT m.name, COUNT(e.id) FROM org m JOIN org e ON e.mgr_id = m.id GROUP BY m.name ORDER BY m.name",
			wantRows: [][]interface{}{
				{"CEO", int64(1)}, {"VP", int64(2)},
			}},
		{name: "REQ-JOIN-033_self_join_siblings",
			setup: orgSetup,
			query: "SELECT a.name, b.name FROM org a JOIN org b ON a.mgr_id = b.mgr_id AND a.id < b.id ORDER BY a.name",
			wantRows: [][]interface{}{
				{"Dev", "QA"},
			}},
	}
}

func genJoinNullKeyTests() []sqlTestCase {
	nullSetup := []string{
		"CREATE TABLE t1(id INTEGER, val TEXT)",
		"INSERT INTO t1 VALUES(1, 'a')", "INSERT INTO t1 VALUES(NULL, 'b')",
		"CREATE TABLE t2(id INTEGER, ref INTEGER, val TEXT)",
		"INSERT INTO t2 VALUES(1, 1, 'x')", "INSERT INTO t2 VALUES(2, NULL, 'y')",
	}
	return []sqlTestCase{
		{name: "REQ-JOIN-040_null_key_inner_excludes",
			setup:    nullSetup,
			query:    "SELECT t1.val, t2.val FROM t1 INNER JOIN t2 ON t1.id = t2.ref",
			wantRows: [][]interface{}{{"a", "x"}}},
		{name: "REQ-JOIN-041_null_key_left_preserves",
			setup: nullSetup,
			query: "SELECT t1.val, t2.val FROM t1 LEFT JOIN t2 ON t1.id = t2.ref ORDER BY t1.val",
			wantRows: [][]interface{}{
				{"a", "x"}, {"b", nil},
			}},
		{name: "REQ-JOIN-042_null_eq_null_inner",
			setup: []string{
				"CREATE TABLE t1(k INTEGER)", "INSERT INTO t1 VALUES(NULL)",
				"CREATE TABLE t2(k INTEGER)", "INSERT INTO t2 VALUES(NULL)",
			},
			query:    "SELECT COUNT(*) FROM t1 JOIN t2 ON t1.k = t2.k",
			wantRows: [][]interface{}{{int64(0)}}},
		{name: "REQ-JOIN-043_null_is_null_join",
			setup: []string{
				"CREATE TABLE t1(k INTEGER)", "INSERT INTO t1 VALUES(NULL)",
				"CREATE TABLE t2(k INTEGER)", "INSERT INTO t2 VALUES(NULL)",
			},
			query:    "SELECT COUNT(*) FROM t1 JOIN t2 ON t1.k IS t2.k",
			wantRows: [][]interface{}{{int64(1)}}},
	}
}

func genJoinNaturalUsingTests() []sqlTestCase {
	natSetup := []string{
		"CREATE TABLE t1(id INTEGER, name TEXT, val INTEGER)",
		"INSERT INTO t1 VALUES(1, 'a', 10)", "INSERT INTO t1 VALUES(2, 'b', 20)",
		"CREATE TABLE t2(id INTEGER, name TEXT, score INTEGER)",
		"INSERT INTO t2 VALUES(1, 'a', 100)", "INSERT INTO t2 VALUES(3, 'c', 300)",
	}
	return []sqlTestCase{
		{name: "REQ-JOIN-050_natural_join",
			setup:    natSetup,
			query:    "SELECT id, name, val, score FROM t1 NATURAL JOIN t2",
			wantRows: [][]interface{}{{int64(1), "a", int64(10), int64(100)}}},
		{name: "REQ-JOIN-051_natural_left_join",
			setup: natSetup,
			query: "SELECT id, name, val, score FROM t1 NATURAL LEFT JOIN t2 ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), "a", int64(10), int64(100)},
				{int64(2), "b", int64(20), nil},
			}},
		{name: "REQ-JOIN-052_using_single_col",
			setup:    natSetup,
			query:    "SELECT t1.name, t2.score FROM t1 JOIN t2 USING(id) ORDER BY t1.name",
			wantRows: [][]interface{}{{"a", int64(100)}}},
		{name: "REQ-JOIN-053_using_multi_col",
			setup:    natSetup,
			query:    "SELECT id, val, score FROM t1 JOIN t2 USING(id, name)",
			wantRows: [][]interface{}{{int64(1), int64(10), int64(100)}}},
		{name: "REQ-JOIN-054_natural_no_common",
			setup: []string{
				"CREATE TABLE t1(a INTEGER)", "INSERT INTO t1 VALUES(1)",
				"CREATE TABLE t2(b INTEGER)", "INSERT INTO t2 VALUES(2)",
			},
			query:    "SELECT a, b FROM t1 NATURAL JOIN t2",
			wantRows: [][]interface{}{{int64(1), int64(2)}}},
		{name: "REQ-JOIN-055_using_left_join",
			setup: natSetup,
			query: "SELECT id, val, score FROM t1 LEFT JOIN t2 USING(id, name) ORDER BY id",
			wantRows: [][]interface{}{
				{int64(1), int64(10), int64(100)},
				{int64(2), int64(20), nil},
			}},
	}
}

func genJoinMultiTableTests() []sqlTestCase {
	multiSetup := []string{
		"CREATE TABLE customers(id INTEGER PRIMARY KEY, name TEXT)",
		"INSERT INTO customers VALUES(1, 'Acme')", "INSERT INTO customers VALUES(2, 'Beta')",
		"CREATE TABLE orders(id INTEGER PRIMARY KEY, cust_id INTEGER, total REAL)",
		"INSERT INTO orders VALUES(1, 1, 100.0)", "INSERT INTO orders VALUES(2, 1, 200.0)",
		"INSERT INTO orders VALUES(3, 2, 50.0)",
		"CREATE TABLE items(id INTEGER PRIMARY KEY, order_id INTEGER, product TEXT)",
		"INSERT INTO items VALUES(1, 1, 'Widget')", "INSERT INTO items VALUES(2, 1, 'Gadget')",
		"INSERT INTO items VALUES(3, 2, 'Widget')", "INSERT INTO items VALUES(4, 3, 'Doohickey')",
	}
	return []sqlTestCase{
		{name: "REQ-JOIN-060_three_table_join",
			setup:    multiSetup,
			query:    "SELECT c.name, o.total, i.product FROM customers c JOIN orders o ON c.id = o.cust_id JOIN items i ON o.id = i.order_id WHERE c.name = 'Acme' ORDER BY o.total, i.product",
			wantRows: [][]interface{}{{"Acme", 100.0, "Gadget"}, {"Acme", 100.0, "Widget"}, {"Acme", 200.0, "Widget"}}},
		{name: "REQ-JOIN-061_three_table_aggregate",

			setup: multiSetup,
			query: "SELECT c.name, COUNT(i.id) FROM customers c JOIN orders o ON c.id = o.cust_id JOIN items i ON o.id = i.order_id GROUP BY c.name ORDER BY c.name",
			wantRows: [][]interface{}{
				{"Acme", int64(3)}, {"Beta", int64(1)},
			}},
		{name: "REQ-JOIN-062_three_table_left",
			setup: append(append([]string{}, multiSetup...),
				"INSERT INTO customers VALUES(3, 'Gamma')"),
			query: "SELECT c.name, COUNT(o.id) FROM customers c LEFT JOIN orders o ON c.id = o.cust_id LEFT JOIN items i ON o.id = i.order_id GROUP BY c.name ORDER BY c.name",
			wantRows: [][]interface{}{
				{"Acme", int64(3)}, {"Beta", int64(1)}, {"Gamma", int64(0)},
			}},
		{name: "REQ-JOIN-063_mixed_join_types",
			setup: multiSetup,
			query: "SELECT c.name, o.total FROM customers c LEFT JOIN orders o ON c.id = o.cust_id INNER JOIN items i ON o.id = i.order_id WHERE i.product = 'Widget' ORDER BY o.total",
			wantRows: [][]interface{}{
				{"Acme", 100.0}, {"Acme", 200.0},
			}},
		{name: "REQ-JOIN-064_four_table_join",

			setup: append(append([]string{}, multiSetup...),
				"CREATE TABLE categories(id INTEGER PRIMARY KEY, product TEXT, category TEXT)",
				"INSERT INTO categories VALUES(1, 'Widget', 'Hardware')",
				"INSERT INTO categories VALUES(2, 'Gadget', 'Electronics')",
				"INSERT INTO categories VALUES(3, 'Doohickey', 'Hardware')"),
			query: "SELECT c.name, cat.category, COUNT(*) FROM customers c JOIN orders o ON c.id = o.cust_id JOIN items i ON o.id = i.order_id JOIN categories cat ON i.product = cat.product GROUP BY c.name, cat.category ORDER BY c.name, cat.category",
			wantRows: [][]interface{}{
				{"Acme", "Electronics", int64(1)}, {"Acme", "Hardware", int64(2)}, {"Beta", "Hardware", int64(1)},
			}},
		{name: "REQ-JOIN-065_subquery_as_join_target",
			setup:    multiSetup,
			query:    "SELECT c.name, sub.order_count FROM customers c JOIN (SELECT cust_id, COUNT(*) AS order_count FROM orders GROUP BY cust_id) sub ON c.id = sub.cust_id ORDER BY c.name",
			wantRows: [][]interface{}{{"Acme", int64(2)}, {"Beta", int64(1)}}},
		{name: "REQ-JOIN-066_join_with_coalesce",
			setup:    joinSetupEmployees,
			query:    "SELECT emp.name, COALESCE(dept.name, 'Unassigned') FROM emp LEFT JOIN dept ON emp.dept_id = dept.id ORDER BY emp.name",
			wantRows: [][]interface{}{{"Alice", "Engineering"}, {"Bob", "Engineering"}, {"Carol", "Marketing"}, {"Dave", "Unassigned"}}},
		{name: "REQ-JOIN-067_join_distinct",
			setup:    multiSetup,
			query:    "SELECT DISTINCT i.product FROM items i JOIN orders o ON i.order_id = o.id ORDER BY i.product",
			wantRows: [][]interface{}{{"Doohickey"}, {"Gadget"}, {"Widget"}}},
	}
}

// Compile-time assertion that sub-generators are used.
var _ = fmt.Sprintf
