// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity

package driver

import "testing"

// TestTrinity_CTE validates Common Table Expression functionality per DO-178C trace.
func TestTrinity_CTE(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityCTETests())
}

func buildTrinityCTETests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genCTENonRecursiveTests()...)
	tests = append(tests, genCTEMultipleTests()...)
	tests = append(tests, genCTERecursiveCounterTests()...)
	tests = append(tests, genCTERecursiveFibTests()...)
	tests = append(tests, genCTERecursiveHierarchyTests()...)
	tests = append(tests, genCTEAdvancedTests()...)
	return tests
}

// ---------------------------------------------------------------------------
// Non-recursive CTE
// ---------------------------------------------------------------------------

func genCTENonRecursiveTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-CTE-001_simple_cte",
			query:    "WITH t AS (SELECT 1 AS x) SELECT x FROM t",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-CTE-002_cte_with_values",
			query:    "WITH t AS (SELECT 10 AS a, 20 AS b) SELECT a+b AS total FROM t",
			wantRows: [][]interface{}{{int64(30)}},
		},
		{
			name:     "REQ-CTE-003_cte_from_table",
			setup:    []string{"CREATE TABLE ct1(a INTEGER, b TEXT)", "INSERT INTO ct1 VALUES(1,'x')", "INSERT INTO ct1 VALUES(2,'y')"},
			query:    "WITH t AS (SELECT a, b FROM ct1 WHERE a=1) SELECT a, b FROM t",
			wantRows: [][]interface{}{{int64(1), "x"}},
		},
		{
			name:     "REQ-CTE-004_cte_with_aggregate",
			setup:    []string{"CREATE TABLE ct2(v INTEGER)", "INSERT INTO ct2 VALUES(10)", "INSERT INTO ct2 VALUES(20)", "INSERT INTO ct2 VALUES(30)"},
			query:    "WITH s AS (SELECT SUM(v) AS total FROM ct2) SELECT total FROM s",
			wantRows: [][]interface{}{{int64(60)}},
		},
		{
			name:     "REQ-CTE-005_cte_column_list",
			query:    "WITH t(col1, col2) AS (SELECT 1, 'hello') SELECT col1, col2 FROM t",
			wantRows: [][]interface{}{{int64(1), "hello"}},
		},
		{
			name:     "REQ-CTE-006_cte_column_list_override",
			query:    "WITH t(x, y) AS (SELECT 42 AS a, 99 AS b) SELECT x, y FROM t",
			wantRows: [][]interface{}{{int64(42), int64(99)}},
		},
		{
			name:     "REQ-CTE-007_cte_with_where",
			setup:    []string{"CREATE TABLE ct3(id INTEGER, val TEXT)", "INSERT INTO ct3 VALUES(1,'a')", "INSERT INTO ct3 VALUES(2,'b')", "INSERT INTO ct3 VALUES(3,'c')"},
			query:    "WITH t AS (SELECT id, val FROM ct3) SELECT val FROM t WHERE id > 1 ORDER BY id",
			wantRows: [][]interface{}{{"b"}, {"c"}},
		},
		{
			name:     "REQ-CTE-008_cte_with_order_by",
			setup:    []string{"CREATE TABLE ct4(v INTEGER)", "INSERT INTO ct4 VALUES(3)", "INSERT INTO ct4 VALUES(1)", "INSERT INTO ct4 VALUES(2)"},
			query:    "WITH t AS (SELECT v FROM ct4) SELECT v FROM t ORDER BY v",
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}, {int64(3)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Multiple CTEs
// ---------------------------------------------------------------------------

func genCTEMultipleTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-CTE-010_two_ctes",
			query:    "WITH a AS (SELECT 1 AS x), b AS (SELECT 2 AS y) SELECT a.x, b.y FROM a, b",
			wantRows: [][]interface{}{{int64(1), int64(2)}},
		},
		{
			name:     "REQ-CTE-011_cte_references_prior_cte",
			query:    "WITH a AS (SELECT 10 AS v), b AS (SELECT v*2 AS w FROM a) SELECT w FROM b",
			wantRows: [][]interface{}{{int64(20)}},
		},
		{
			name:     "REQ-CTE-012_three_ctes_chained",
			query:    "WITH a AS (SELECT 5 AS x), b AS (SELECT x+1 AS y FROM a), c AS (SELECT y+1 AS z FROM b) SELECT z FROM c",
			wantRows: [][]interface{}{{int64(7)}},
		},
		{
			name: "REQ-CTE-013_multiple_ctes_join",
			setup: []string{
				"CREATE TABLE mc1(id INTEGER, name TEXT)",
				"INSERT INTO mc1 VALUES(1,'Alice')", "INSERT INTO mc1 VALUES(2,'Bob')",
				"CREATE TABLE mc2(id INTEGER, score INTEGER)",
				"INSERT INTO mc2 VALUES(1,90)", "INSERT INTO mc2 VALUES(2,85)",
			},
			query:    "WITH names AS (SELECT id, name FROM mc1), scores AS (SELECT id, score FROM mc2) SELECT n.name, s.score FROM names n JOIN scores s ON n.id=s.id ORDER BY n.name",
			wantRows: [][]interface{}{{"Alice", int64(90)}, {"Bob", int64(85)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Recursive CTE: counter
// ---------------------------------------------------------------------------

func genCTERecursiveCounterTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:  "REQ-CTE-020_recursive_counter_1_to_5",
			query: "WITH RECURSIVE cnt(x) AS (SELECT 1 UNION ALL SELECT x+1 FROM cnt WHERE x<5) SELECT x FROM cnt",
			wantRows: [][]interface{}{
				{int64(1)}, {int64(2)}, {int64(3)}, {int64(4)}, {int64(5)},
			},
		},
		{
			name:  "REQ-CTE-021_recursive_counter_1_to_10",
			query: "WITH RECURSIVE cnt(x) AS (SELECT 1 UNION ALL SELECT x+1 FROM cnt WHERE x<10) SELECT x FROM cnt",
			wantRows: [][]interface{}{
				{int64(1)}, {int64(2)}, {int64(3)}, {int64(4)}, {int64(5)},
				{int64(6)}, {int64(7)}, {int64(8)}, {int64(9)}, {int64(10)},
			},
		},
		{
			name:     "REQ-CTE-022_recursive_sum",
			query:    "WITH RECURSIVE cnt(x) AS (SELECT 1 UNION ALL SELECT x+1 FROM cnt WHERE x<5) SELECT SUM(x) FROM cnt",
			wantRows: [][]interface{}{{int64(15)}},
		},
		{
			name:  "REQ-CTE-023_recursive_even_numbers",
			query: "WITH RECURSIVE ev(x) AS (SELECT 2 UNION ALL SELECT x+2 FROM ev WHERE x<10) SELECT x FROM ev",
			wantRows: [][]interface{}{
				{int64(2)}, {int64(4)}, {int64(6)}, {int64(8)}, {int64(10)},
			},
		},
		{
			name:  "REQ-CTE-024_recursive_powers_of_two",
			query: "WITH RECURSIVE pw(x) AS (SELECT 1 UNION ALL SELECT x*2 FROM pw WHERE x<32) SELECT x FROM pw",
			wantRows: [][]interface{}{
				{int64(1)}, {int64(2)}, {int64(4)}, {int64(8)}, {int64(16)}, {int64(32)},
			},
		},
	}
}

// ---------------------------------------------------------------------------
// Recursive CTE: Fibonacci
// ---------------------------------------------------------------------------

func genCTERecursiveFibTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:  "REQ-CTE-030_fibonacci_first_8",
			query: "WITH RECURSIVE fib(a, b) AS (SELECT 0, 1 UNION ALL SELECT b, a+b FROM fib WHERE b < 21) SELECT a FROM fib",
			wantRows: [][]interface{}{
				{int64(0)}, {int64(1)}, {int64(1)}, {int64(2)}, {int64(3)},
				{int64(5)}, {int64(8)}, {int64(13)},
			},
		},
		{
			name:     "REQ-CTE-031_fibonacci_sum",
			query:    "WITH RECURSIVE fib(a, b) AS (SELECT 0, 1 UNION ALL SELECT b, a+b FROM fib WHERE b < 21) SELECT SUM(a) FROM fib",
			wantRows: [][]interface{}{{int64(33)}},
		},
		{
			name:     "REQ-CTE-032_fibonacci_count",
			query:    "WITH RECURSIVE fib(a, b) AS (SELECT 0, 1 UNION ALL SELECT b, a+b FROM fib WHERE b < 21) SELECT COUNT(*) FROM fib",
			wantRows: [][]interface{}{{int64(8)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Recursive CTE: hierarchy traversal (org chart)
// ---------------------------------------------------------------------------

func genCTERecursiveHierarchyTests() []sqlTestCase {
	orgSetup := []string{
		"CREATE TABLE org(id INTEGER PRIMARY KEY, name TEXT, mgr_id INTEGER)",
		"INSERT INTO org VALUES(1,'CEO',NULL)",
		"INSERT INTO org VALUES(2,'VP_Eng',1)",
		"INSERT INTO org VALUES(3,'VP_Sales',1)",
		"INSERT INTO org VALUES(4,'Dev_Lead',2)",
		"INSERT INTO org VALUES(5,'Dev1',4)",
		"INSERT INTO org VALUES(6,'Dev2',4)",
		"INSERT INTO org VALUES(7,'Sales_Rep',3)",
	}
	return []sqlTestCase{
		{
			name:  "REQ-CTE-040_hierarchy_all_reports",
			setup: orgSetup,
			query: "WITH RECURSIVE reps(id, name, lvl) AS (SELECT id, name, 0 FROM org WHERE mgr_id IS NULL UNION ALL SELECT o.id, o.name, r.lvl+1 FROM org o JOIN reps r ON o.mgr_id=r.id) SELECT name, lvl FROM reps ORDER BY lvl, name",
			wantRows: [][]interface{}{
				{"CEO", int64(0)},
				{"VP_Eng", int64(1)}, {"VP_Sales", int64(1)},
				{"Dev_Lead", int64(2)},
				{"Sales_Rep", int64(2)},
				{"Dev1", int64(3)}, {"Dev2", int64(3)},
			},
		},
		{
			name:     "REQ-CTE-041_hierarchy_depth",
			setup:    orgSetup,
			query:    "WITH RECURSIVE reps(id, lvl) AS (SELECT id, 0 FROM org WHERE mgr_id IS NULL UNION ALL SELECT o.id, r.lvl+1 FROM org o JOIN reps r ON o.mgr_id=r.id) SELECT MAX(lvl) FROM reps",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-CTE-042_hierarchy_subtree_count",
			setup:    orgSetup,
			query:    "WITH RECURSIVE sub(id) AS (SELECT id FROM org WHERE id=2 UNION ALL SELECT o.id FROM org o JOIN sub s ON o.mgr_id=s.id) SELECT COUNT(*) FROM sub",
			wantRows: [][]interface{}{{int64(4)}},
		},
		{
			name:  "REQ-CTE-043_hierarchy_path_to_root",
			setup: orgSetup,
			query: "WITH RECURSIVE chain(id, name, mgr_id) AS (SELECT id, name, mgr_id FROM org WHERE id=5 UNION ALL SELECT o.id, o.name, o.mgr_id FROM org o JOIN chain c ON c.mgr_id=o.id) SELECT name FROM chain",
			wantRows: [][]interface{}{
				{"Dev1"}, {"Dev_Lead"}, {"VP_Eng"}, {"CEO"},
			},
		},
	}
}

// ---------------------------------------------------------------------------
// Advanced CTE usage
// ---------------------------------------------------------------------------

func genCTEAdvancedTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-CTE-050_cte_in_subquery",
			setup:    []string{"CREATE TABLE ca1(v INTEGER)", "INSERT INTO ca1 VALUES(1)", "INSERT INTO ca1 VALUES(2)", "INSERT INTO ca1 VALUES(3)"},
			query:    "SELECT v FROM ca1 WHERE v > (WITH t AS (SELECT AVG(v) AS avg_v FROM ca1) SELECT avg_v FROM t) ORDER BY v",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-CTE-051_cte_with_limit",
			query:    "WITH RECURSIVE cnt(x) AS (SELECT 1 UNION ALL SELECT x+1 FROM cnt WHERE x<100) SELECT x FROM cnt LIMIT 5",
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}, {int64(3)}, {int64(4)}, {int64(5)}},
		},
		{
			name:  "REQ-CTE-052_cte_union_all_dedup",
			query: "WITH RECURSIVE cnt(x) AS (SELECT 1 UNION ALL SELECT x+1 FROM cnt WHERE x<3) SELECT DISTINCT x FROM cnt ORDER BY x",
			wantRows: [][]interface{}{
				{int64(1)}, {int64(2)}, {int64(3)},
			},
		},
		{
			name:     "REQ-CTE-053_cte_with_group_by",
			setup:    []string{"CREATE TABLE ca3(cat TEXT, val INTEGER)", "INSERT INTO ca3 VALUES('a',10)", "INSERT INTO ca3 VALUES('a',20)", "INSERT INTO ca3 VALUES('b',30)"},
			query:    "WITH t AS (SELECT cat, SUM(val) AS total FROM ca3 GROUP BY cat) SELECT cat, total FROM t ORDER BY cat",
			wantRows: [][]interface{}{{"a", int64(30)}, {"b", int64(30)}},
		},
		{
			name:  "REQ-CTE-054_recursive_string_build",
			query: "WITH RECURSIVE s(v, n) AS (SELECT 'a', 1 UNION ALL SELECT v||'a', n+1 FROM s WHERE n<4) SELECT v FROM s ORDER BY n DESC LIMIT 1",
			wantRows: [][]interface{}{{"aaaa"}},
		},
		{
			name:     "REQ-CTE-055_cte_exists_check",
			setup:    []string{"CREATE TABLE ca5(id INTEGER)", "INSERT INTO ca5 VALUES(1)", "INSERT INTO ca5 VALUES(2)"},
			query:    "WITH t AS (SELECT id FROM ca5 WHERE id=1) SELECT EXISTS(SELECT 1 FROM t)",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:  "REQ-CTE-056_recursive_factorial",
			query: "WITH RECURSIVE fact(n, f) AS (SELECT 1, 1 UNION ALL SELECT n+1, f*(n+1) FROM fact WHERE n<6) SELECT f FROM fact WHERE n=6",
			wantRows: [][]interface{}{{int64(720)}},
		},
	}
}
