// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import "testing"

// TestTrinity_VTab validates virtual-table TVF functions per DO-178C trace.
func TestTrinity_VTab(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityVTabTests())
}

func buildTrinityVTabTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genVTabJSONEachTests()...)
	tests = append(tests, genVTabJSONTreeTests()...)
	tests = append(tests, genVTabJoinTests()...)
	return tests
}

// ---------------------------------------------------------------------------
// json_each()
// ---------------------------------------------------------------------------

func genVTabJSONEachTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-VTAB-001_json_each_array_values",
			query:    "SELECT value FROM json_each('[10,20,30]') ORDER BY key",
			wantRows: [][]interface{}{{int64(10)}, {int64(20)}, {int64(30)}},
		},
		{
			name:     "REQ-VTAB-002_json_each_array_keys",
			query:    "SELECT key FROM json_each('[10,20,30]') ORDER BY key",
			wantRows: [][]interface{}{{int64(0)}, {int64(1)}, {int64(2)}},
		},
		{
			name:     "REQ-VTAB-003_json_each_object_keys",
			query:    `SELECT key FROM json_each('{"a":1,"b":2,"c":3}') ORDER BY key`,
			wantRows: [][]interface{}{{"a"}, {"b"}, {"c"}},
		},
		{
			name:     "REQ-VTAB-004_json_each_object_values",
			query:    `SELECT value FROM json_each('{"a":1,"b":2}') ORDER BY key`,
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}},
		},
		{
			name:     "REQ-VTAB-005_json_each_types",
			query:    `SELECT type FROM json_each('[1,"two",null,true]') ORDER BY key`,
			wantRows: [][]interface{}{{"integer"}, {"text"}, {"null"}, {"true"}},
		},
		{
			name:     "REQ-VTAB-006_json_each_empty_array",

			query:    "SELECT COUNT(*) FROM json_each('[]')",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-VTAB-007_json_each_with_path",
			query:    `SELECT value FROM json_each('{"a":{"b":[4,5,6]}}', '$.a.b') ORDER BY key`,
			wantRows: [][]interface{}{{int64(4)}, {int64(5)}, {int64(6)}},
		},
		{
			name:     "REQ-VTAB-008_json_each_path_object",
			query:    `SELECT key, value FROM json_each('{"x":{"m":1,"n":2}}', '$.x') ORDER BY key`,
			wantRows: [][]interface{}{{"m", int64(1)}, {"n", int64(2)}},
		},
		{
			name:     "REQ-VTAB-009_json_each_count",

			query:    "SELECT COUNT(*) FROM json_each('[1,2,3,4,5]')",
			wantRows: [][]interface{}{{int64(5)}},
		},
		{
			name:     "REQ-VTAB-010_json_each_from_column",


			setup:    []string{"CREATE TABLE vt1(doc TEXT)", `INSERT INTO vt1 VALUES('[100,200]')`},
			query:    "SELECT je.value FROM vt1, json_each(vt1.doc) AS je ORDER BY je.key",
			wantRows: [][]interface{}{{int64(100)}, {int64(200)}},
		},
	}
}

// ---------------------------------------------------------------------------
// json_tree()
// ---------------------------------------------------------------------------

func genVTabJSONTreeTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-VTAB-020_json_tree_flat_array",

			query:    "SELECT COUNT(*) FROM json_tree('[1,2,3]')",
			wantRows: [][]interface{}{{int64(4)}}, // root array + 3 elements
		},
		{
			name:     "REQ-VTAB-021_json_tree_nested_count",

			query:    `SELECT COUNT(*) FROM json_tree('{"a":{"b":1}}')`,
			wantRows: [][]interface{}{{int64(3)}}, // root + a-object + b
		},
		{
			name:     "REQ-VTAB-022_json_tree_leaf_values",
			query:    `SELECT value FROM json_tree('{"x":1,"y":2}') WHERE atom IS NOT NULL ORDER BY key`,
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}},
		},
		{
			name: "REQ-VTAB-023_json_tree_with_path",

			query:    `SELECT value FROM json_tree('{"a":{"b":[10,20]}}', '$.a.b') WHERE atom IS NOT NULL ORDER BY id`,
			wantRows: [][]interface{}{{int64(10)}, {int64(20)}},
		},
		{
			name:  "REQ-VTAB-024_json_tree_types",
			query: `SELECT DISTINCT type FROM json_tree('{"a":[1,"t",null]}') ORDER BY type`,
			wantRows: [][]interface{}{{"array"}, {"integer"}, {"null"}, {"object"}, {"text"}},
		},
	}
}

// ---------------------------------------------------------------------------
// JOIN with json_each
// ---------------------------------------------------------------------------

func genVTabJoinTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE tags(id INTEGER PRIMARY KEY, tag_list TEXT)",
		`INSERT INTO tags VALUES(1, '["go","sql"]')`,
		`INSERT INTO tags VALUES(2, '["rust","wasm"]')`,
		`INSERT INTO tags VALUES(3, '["go","wasm","ffi"]')`,
	}
	return []sqlTestCase{
		{
			name:     "REQ-VTAB-030_join_json_each_expand",


			setup:    setup,
			query:    "SELECT t.id, je.value FROM tags t, json_each(t.tag_list) je WHERE je.value='go' ORDER BY t.id",
			wantRows: [][]interface{}{{int64(1), "go"}, {int64(3), "go"}},
		},
		{
			name:     "REQ-VTAB-031_join_json_each_count",


			setup:    setup,
			query:    "SELECT t.id, COUNT(je.value) AS cnt FROM tags t, json_each(t.tag_list) je GROUP BY t.id ORDER BY t.id",
			wantRows: [][]interface{}{{int64(1), int64(2)}, {int64(2), int64(2)}, {int64(3), int64(3)}},
		},
		{
			name:     "REQ-VTAB-032_join_json_each_filter",


			setup:    setup,
			query:    "SELECT DISTINCT je.value FROM tags t, json_each(t.tag_list) je WHERE je.value='wasm'",
			wantRows: [][]interface{}{{"wasm"}},
		},
		{
			name:     "REQ-VTAB-033_join_json_each_all_tags",


			setup:    setup,
			query:    "SELECT COUNT(DISTINCT je.value) FROM tags t, json_each(t.tag_list) je",
			wantRows: [][]interface{}{{int64(5)}}, // go, sql, rust, wasm, ffi
		},
		{
			name:     "REQ-VTAB-034_join_json_each_no_match",


			setup:    setup,
			query:    "SELECT COUNT(*) FROM tags t, json_each(t.tag_list) je WHERE je.value='python'",
			wantRows: [][]interface{}{{int64(0)}},
		},
	}
}
