// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity

package driver

import "testing"

// TestTrinity_Trans validates transaction semantics per DO-178C trace.
func TestTrinity_Trans(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityTransTests())
}

func buildTrinityTransTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genTransBeginCommitTests()...)
	tests = append(tests, genTransBeginRollbackTests()...)
	tests = append(tests, genTransAutocommitTests()...)
	tests = append(tests, genTransSavepointTests()...)
	tests = append(tests, genTransNestedSavepointTests()...)
	tests = append(tests, genTransErrorTests()...)
	tests = append(tests, genTransDDLTests()...)
	return tests
}

// ---------------------------------------------------------------------------
// BEGIN / COMMIT
// ---------------------------------------------------------------------------

func genTransBeginCommitTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-TRANS-001_begin_commit_insert",
			setup:    []string{"CREATE TABLE tc1(a INTEGER)", "BEGIN", "INSERT INTO tc1 VALUES(1)", "COMMIT"},
			query:    "SELECT a FROM tc1",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-TRANS-002_begin_commit_multiple_inserts",
			setup:    []string{"CREATE TABLE tc2(a INTEGER)", "BEGIN", "INSERT INTO tc2 VALUES(1)", "INSERT INTO tc2 VALUES(2)", "INSERT INTO tc2 VALUES(3)", "COMMIT"},
			query:    "SELECT COUNT(*) FROM tc2",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-TRANS-003_begin_commit_update",
			setup:    []string{"CREATE TABLE tc3(a INTEGER, b TEXT)", "INSERT INTO tc3 VALUES(1,'old')", "BEGIN", "UPDATE tc3 SET b='new' WHERE a=1", "COMMIT"},
			query:    "SELECT b FROM tc3 WHERE a=1",
			wantRows: [][]interface{}{{"new"}},
		},
		{
			name:     "REQ-TRANS-004_begin_commit_delete",
			setup:    []string{"CREATE TABLE tc4(a INTEGER)", "INSERT INTO tc4 VALUES(1)", "INSERT INTO tc4 VALUES(2)", "BEGIN", "DELETE FROM tc4 WHERE a=1", "COMMIT"},
			query:    "SELECT COUNT(*) FROM tc4",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-TRANS-005_begin_commit_preserves_data",
			setup:    []string{"CREATE TABLE tc5(a INTEGER)", "INSERT INTO tc5 VALUES(10)", "BEGIN", "INSERT INTO tc5 VALUES(20)", "COMMIT"},
			query:    "SELECT a FROM tc5 ORDER BY a",
			wantRows: [][]interface{}{{int64(10)}, {int64(20)}},
		},
		{
			name:     "REQ-TRANS-006_explicit_begin_transaction",
			setup:    []string{"CREATE TABLE tc6(a INTEGER)", "BEGIN TRANSACTION", "INSERT INTO tc6 VALUES(42)", "COMMIT"},
			query:    "SELECT a FROM tc6",
			wantRows: [][]interface{}{{int64(42)}},
		},
	}
}

// ---------------------------------------------------------------------------
// BEGIN / ROLLBACK
// ---------------------------------------------------------------------------

func genTransBeginRollbackTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-TRANS-010_rollback_insert",
			setup:    []string{"CREATE TABLE tr1(a INTEGER)", "BEGIN", "INSERT INTO tr1 VALUES(1)", "ROLLBACK"},
			query:    "SELECT COUNT(*) FROM tr1",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-TRANS-011_rollback_update",
			setup:    []string{"CREATE TABLE tr2(a INTEGER, b TEXT)", "INSERT INTO tr2 VALUES(1,'original')", "BEGIN", "UPDATE tr2 SET b='changed' WHERE a=1", "ROLLBACK"},
			query:    "SELECT b FROM tr2 WHERE a=1",
			wantRows: [][]interface{}{{"original"}},
		},
		{
			name:     "REQ-TRANS-012_rollback_delete",
			setup:    []string{"CREATE TABLE tr3(a INTEGER)", "INSERT INTO tr3 VALUES(1)", "BEGIN", "DELETE FROM tr3 WHERE a=1", "ROLLBACK"},
			query:    "SELECT COUNT(*) FROM tr3",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-TRANS-013_rollback_multiple_operations",
			setup:    []string{"CREATE TABLE tr4(a INTEGER)", "INSERT INTO tr4 VALUES(1)", "BEGIN", "INSERT INTO tr4 VALUES(2)", "UPDATE tr4 SET a=99 WHERE a=1", "DELETE FROM tr4 WHERE a=99", "ROLLBACK"},
			query:    "SELECT a FROM tr4",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-TRANS-014_rollback_preserves_prior_data",
			setup:    []string{"CREATE TABLE tr5(a INTEGER)", "INSERT INTO tr5 VALUES(10)", "INSERT INTO tr5 VALUES(20)", "BEGIN", "DELETE FROM tr5", "ROLLBACK"},
			query:    "SELECT COUNT(*) FROM tr5",
			wantRows: [][]interface{}{{int64(2)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Autocommit
// ---------------------------------------------------------------------------

func genTransAutocommitTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-TRANS-020_autocommit_insert",
			setup:    []string{"CREATE TABLE ta1(a INTEGER)", "INSERT INTO ta1 VALUES(1)"},
			query:    "SELECT a FROM ta1",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-TRANS-021_autocommit_update",
			setup:    []string{"CREATE TABLE ta2(a INTEGER, b TEXT)", "INSERT INTO ta2 VALUES(1,'old')", "UPDATE ta2 SET b='new'"},
			query:    "SELECT b FROM ta2",
			wantRows: [][]interface{}{{"new"}},
		},
		{
			name:     "REQ-TRANS-022_autocommit_delete",
			setup:    []string{"CREATE TABLE ta3(a INTEGER)", "INSERT INTO ta3 VALUES(1)", "DELETE FROM ta3"},
			query:    "SELECT COUNT(*) FROM ta3",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-TRANS-023_autocommit_ddl",
			setup:    []string{"CREATE TABLE ta4(a INTEGER)"},
			query:    "SELECT name FROM sqlite_master WHERE type='table' AND name='ta4'",
			wantRows: [][]interface{}{{"ta4"}},
		},
	}
}

// ---------------------------------------------------------------------------
// SAVEPOINT / RELEASE
// ---------------------------------------------------------------------------

func genTransSavepointTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-TRANS-030_savepoint_release",
			setup:    []string{"CREATE TABLE sp1(a INTEGER)", "BEGIN", "SAVEPOINT s1", "INSERT INTO sp1 VALUES(1)", "RELEASE s1", "COMMIT"},
			query:    "SELECT a FROM sp1",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-TRANS-031_savepoint_rollback_to",
			setup:    []string{"CREATE TABLE sp2(a INTEGER)", "BEGIN", "INSERT INTO sp2 VALUES(1)", "SAVEPOINT s1", "INSERT INTO sp2 VALUES(2)", "ROLLBACK TO s1", "COMMIT"},
			query:    "SELECT a FROM sp2",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-TRANS-032_savepoint_rollback_to_preserves_prior",
			setup:    []string{"CREATE TABLE sp3(a INTEGER)", "BEGIN", "INSERT INTO sp3 VALUES(10)", "SAVEPOINT s1", "INSERT INTO sp3 VALUES(20)", "INSERT INTO sp3 VALUES(30)", "ROLLBACK TO s1", "INSERT INTO sp3 VALUES(40)", "COMMIT"},
			query:    "SELECT a FROM sp3 ORDER BY a",
			wantRows: [][]interface{}{{int64(10)}, {int64(40)}},
		},
		{
			name:     "REQ-TRANS-033_savepoint_release_commits_work",
			setup:    []string{"CREATE TABLE sp4(a INTEGER)", "SAVEPOINT outer", "INSERT INTO sp4 VALUES(1)", "RELEASE outer"},
			query:    "SELECT a FROM sp4",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-TRANS-034_savepoint_rollback_to_keeps_savepoint",
			setup:    []string{"CREATE TABLE sp5(a INTEGER)", "BEGIN", "SAVEPOINT s1", "INSERT INTO sp5 VALUES(1)", "ROLLBACK TO s1", "INSERT INTO sp5 VALUES(2)", "ROLLBACK TO s1", "INSERT INTO sp5 VALUES(3)", "COMMIT"},
			query:    "SELECT a FROM sp5",
			wantRows: [][]interface{}{{int64(3)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Nested savepoints
// ---------------------------------------------------------------------------

func genTransNestedSavepointTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-TRANS-040_nested_savepoints_release_all",
			setup:    []string{"CREATE TABLE ns1(a INTEGER)", "BEGIN", "SAVEPOINT s1", "INSERT INTO ns1 VALUES(1)", "SAVEPOINT s2", "INSERT INTO ns1 VALUES(2)", "RELEASE s2", "RELEASE s1", "COMMIT"},
			query:    "SELECT COUNT(*) FROM ns1",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name:     "REQ-TRANS-041_nested_savepoint_rollback_inner",
			setup:    []string{"CREATE TABLE ns2(a INTEGER)", "BEGIN", "SAVEPOINT s1", "INSERT INTO ns2 VALUES(1)", "SAVEPOINT s2", "INSERT INTO ns2 VALUES(2)", "ROLLBACK TO s2", "RELEASE s1", "COMMIT"},
			query:    "SELECT a FROM ns2",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-TRANS-042_nested_savepoint_rollback_outer",
			setup:    []string{"CREATE TABLE ns3(a INTEGER)", "BEGIN", "SAVEPOINT s1", "INSERT INTO ns3 VALUES(1)", "SAVEPOINT s2", "INSERT INTO ns3 VALUES(2)", "RELEASE s2", "ROLLBACK TO s1", "COMMIT"},
			query:    "SELECT COUNT(*) FROM ns3",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-TRANS-043_three_level_nested_savepoints",
			setup:    []string{"CREATE TABLE ns4(a INTEGER)", "BEGIN", "SAVEPOINT s1", "INSERT INTO ns4 VALUES(1)", "SAVEPOINT s2", "INSERT INTO ns4 VALUES(2)", "SAVEPOINT s3", "INSERT INTO ns4 VALUES(3)", "ROLLBACK TO s3", "RELEASE s2", "RELEASE s1", "COMMIT"},
			query:    "SELECT a FROM ns4 ORDER BY a",
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}},
		},
		{
			name:     "REQ-TRANS-044_nested_savepoint_rollback_middle",
			setup:    []string{"CREATE TABLE ns5(a INTEGER)", "BEGIN", "INSERT INTO ns5 VALUES(1)", "SAVEPOINT s1", "INSERT INTO ns5 VALUES(2)", "SAVEPOINT s2", "INSERT INTO ns5 VALUES(3)", "ROLLBACK TO s1", "COMMIT"},
			query:    "SELECT a FROM ns5",
			wantRows: [][]interface{}{{int64(1)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Error in transaction
// ---------------------------------------------------------------------------

func genTransErrorTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-TRANS-050_error_does_not_abort_transaction",
			setup:    []string{"CREATE TABLE te1(a INTEGER NOT NULL)", "BEGIN", "INSERT INTO te1 VALUES(1)"},
			exec:     "INSERT INTO te1 VALUES(NULL)",
			wantErr:  true,
			errLike:  "NOT NULL",
		},
		{
			name:     "REQ-TRANS-051_transaction_usable_after_error",
			setup:    []string{"CREATE TABLE te2(a INTEGER UNIQUE)", "BEGIN", "INSERT INTO te2 VALUES(1)"},
			exec:     "INSERT INTO te2 VALUES(1)",
			wantErr:  true,
			errLike:  "UNIQUE constraint",
		},
		{
			name:    "REQ-TRANS-052_begin_while_in_transaction",
			setup:   []string{"BEGIN"},
			exec:    "BEGIN",
			wantErr: true,
			errLike: "transaction",
		},
		{
			name:    "REQ-TRANS-053_commit_without_transaction",
			exec:    "COMMIT",
			wantErr: true,
			errLike: "transaction",
		},
		{
			name:    "REQ-TRANS-054_rollback_without_transaction",
			exec:    "ROLLBACK",
			wantErr: true,
			errLike: "transaction",
		},
	}
}

// ---------------------------------------------------------------------------
// DDL in transaction
// ---------------------------------------------------------------------------

func genTransDDLTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-TRANS-060_ddl_create_table_in_transaction",
			setup:    []string{"BEGIN", "CREATE TABLE td1(a INTEGER)", "INSERT INTO td1 VALUES(1)", "COMMIT"},
			query:    "SELECT a FROM td1",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-TRANS-061_ddl_create_table_rollback",
			setup:    []string{"BEGIN", "CREATE TABLE td2(a INTEGER)", "INSERT INTO td2 VALUES(1)", "ROLLBACK"},
			query:    "SELECT COUNT(*) FROM sqlite_master WHERE name='td2'",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-TRANS-062_ddl_drop_table_in_transaction",
			setup:    []string{"CREATE TABLE td3(a INTEGER)", "INSERT INTO td3 VALUES(1)", "BEGIN", "DROP TABLE td3", "COMMIT"},
			query:    "SELECT COUNT(*) FROM sqlite_master WHERE name='td3'",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-TRANS-063_ddl_drop_table_rollback",
			setup:    []string{"CREATE TABLE td4(a INTEGER)", "INSERT INTO td4 VALUES(1)", "BEGIN", "DROP TABLE td4", "ROLLBACK"},
			query:    "SELECT a FROM td4",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-TRANS-064_ddl_alter_in_transaction",
			setup:    []string{"CREATE TABLE td5(a INTEGER)", "INSERT INTO td5 VALUES(1)", "BEGIN", "ALTER TABLE td5 ADD COLUMN b TEXT DEFAULT 'x'", "COMMIT"},
			query:    "SELECT a, b FROM td5",
			wantRows: [][]interface{}{{int64(1), "x"}},
		},
		{
			name:     "REQ-TRANS-065_ddl_create_index_in_transaction",
			setup:    []string{"CREATE TABLE td6(a INTEGER)", "BEGIN", "CREATE INDEX idx_td6 ON td6(a)", "COMMIT"},
			query:    "SELECT COUNT(*) FROM sqlite_master WHERE type='index' AND name='idx_td6'",
			wantRows: [][]interface{}{{int64(1)}},
		},
	}
}
