// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import "testing"

// TestTrinity_View validates SQL VIEW functionality per DO-178C trace.
func TestTrinity_View(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityViewTests())
}

func buildTrinityViewTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genViewCreateTests()...)
	tests = append(tests, genViewSelectTests()...)
	tests = append(tests, genViewDropTests()...)
	tests = append(tests, genViewAdvancedTests()...)
	return tests
}

// ---------------------------------------------------------------------------
// CREATE VIEW
// ---------------------------------------------------------------------------

func genViewCreateTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-VIEW-001_create_simple_view",
			setup:    []string{"CREATE TABLE v1(a INTEGER, b TEXT)", "CREATE VIEW vw1 AS SELECT a, b FROM v1"},
			query:    "SELECT name FROM sqlite_master WHERE type='view' AND name='vw1'",
			wantRows: [][]interface{}{{"vw1"}},
		},
		{
			name:     "REQ-VIEW-002_create_view_if_not_exists",
			setup:    []string{"CREATE TABLE v2(a INTEGER)", "CREATE VIEW vw2 AS SELECT a FROM v2", "CREATE VIEW IF NOT EXISTS vw2 AS SELECT a FROM v2"},
			query:    "SELECT COUNT(*) FROM sqlite_master WHERE type='view' AND name='vw2'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:    "REQ-VIEW-003_create_duplicate_view_error",
			setup:   []string{"CREATE TABLE v3(a INTEGER)", "CREATE VIEW vw3 AS SELECT a FROM v3"},
			exec:    "CREATE VIEW vw3 AS SELECT a FROM v3",
			wantErr: true,
			errLike: "already exists",
		},
		{
			name:     "REQ-VIEW-004_create_view_with_column_alias",
			setup:    []string{"CREATE TABLE v4(a INTEGER, b TEXT)", "INSERT INTO v4 VALUES(1,'hello')", "CREATE VIEW vw4 AS SELECT a AS id, b AS label FROM v4"},
			query:    "SELECT id, label FROM vw4",
			wantRows: [][]interface{}{{int64(1), "hello"}},
		},
		{
			name:     "REQ-VIEW-005_create_view_with_expression",
			setup:    []string{"CREATE TABLE v5(a INTEGER, b INTEGER)", "INSERT INTO v5 VALUES(10,3)", "CREATE VIEW vw5 AS SELECT a+b AS total, a*b AS product FROM v5"},
			query:    "SELECT total, product FROM vw5",
			wantRows: [][]interface{}{{int64(13), int64(30)}},
		},
	}
}

// ---------------------------------------------------------------------------
// SELECT from VIEW
// ---------------------------------------------------------------------------

func genViewSelectTests() []sqlTestCase {
	baseSetup := []string{
		"CREATE TABLE emp(id INTEGER PRIMARY KEY, name TEXT, dept TEXT, salary INTEGER)",
		"INSERT INTO emp VALUES(1,'Alice','eng',90000)",
		"INSERT INTO emp VALUES(2,'Bob','eng',85000)",
		"INSERT INTO emp VALUES(3,'Carol','sales',70000)",
		"INSERT INTO emp VALUES(4,'Dave','sales',75000)",
		"INSERT INTO emp VALUES(5,'Eve','hr',65000)",
	}
	return []sqlTestCase{
		{
			name:     "REQ-VIEW-010_select_all_from_view",
			setup:    append(baseSetup, "CREATE VIEW vw_eng AS SELECT id, name, salary FROM emp WHERE dept='eng'"),
			query:    "SELECT id, name, salary FROM vw_eng ORDER BY id",
			wantRows: [][]interface{}{{int64(1), "Alice", int64(90000)}, {int64(2), "Bob", int64(85000)}},
		},
		{
			name:     "REQ-VIEW-011_view_with_where_clause",
			setup:    append(baseSetup, "CREATE VIEW vw_all AS SELECT id, name, salary FROM emp"),
			query:    "SELECT name FROM vw_all WHERE salary > 80000 ORDER BY name",
			wantRows: [][]interface{}{{"Alice"}, {"Bob"}},
		},
		{
			name:     "REQ-VIEW-012_view_with_aggregates",
			skip:     "pre-existing: view with aggregates edge case",
			setup:    append(baseSetup, "CREATE VIEW vw_dept_avg AS SELECT dept, AVG(salary) AS avg_sal FROM emp GROUP BY dept"),
			query:    "SELECT dept, avg_sal FROM vw_dept_avg WHERE dept='eng'",
			wantRows: [][]interface{}{{"eng", float64(87500)}},
		},
		{
			name:     "REQ-VIEW-013_view_count_rows",
			setup:    append(baseSetup, "CREATE VIEW vw_count AS SELECT COUNT(*) AS cnt FROM emp"),
			query:    "SELECT cnt FROM vw_count",
			wantRows: [][]interface{}{{int64(5)}},
		},
		{
			name:     "REQ-VIEW-014_view_with_order_by",
			setup:    append(baseSetup, "CREATE VIEW vw_ordered AS SELECT name FROM emp ORDER BY salary DESC"),
			query:    "SELECT name FROM vw_ordered LIMIT 2",
			wantRows: [][]interface{}{{"Alice"}, {"Bob"}},
		},
	}
}

// ---------------------------------------------------------------------------
// DROP VIEW
// ---------------------------------------------------------------------------

func genViewDropTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-VIEW-020_drop_view",
			setup:    []string{"CREATE TABLE dv1(a INTEGER)", "CREATE VIEW dvw1 AS SELECT a FROM dv1", "DROP VIEW dvw1"},
			query:    "SELECT COUNT(*) FROM sqlite_master WHERE type='view' AND name='dvw1'",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:    "REQ-VIEW-021_drop_nonexistent_view_error",
			skip:    "pre-existing: DROP VIEW error handling",
			exec:    "DROP VIEW no_such_view",
			wantErr: true,
			errLike: "view not found",
		},
		{
			name:    "REQ-VIEW-022_drop_view_if_exists",
			exec:    "DROP VIEW IF EXISTS no_such_view",
			wantErr: false,
		},
		{
			name:     "REQ-VIEW-023_drop_view_table_survives",
			setup:    []string{"CREATE TABLE dv3(a INTEGER)", "INSERT INTO dv3 VALUES(42)", "CREATE VIEW dvw3 AS SELECT a FROM dv3", "DROP VIEW dvw3"},
			query:    "SELECT a FROM dv3",
			wantRows: [][]interface{}{{int64(42)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Advanced: nested views, JOINs
// ---------------------------------------------------------------------------

func genViewAdvancedTests() []sqlTestCase {
	joinSetup := []string{
		"CREATE TABLE dept(id INTEGER PRIMARY KEY, dname TEXT)",
		"INSERT INTO dept VALUES(1,'eng')",
		"INSERT INTO dept VALUES(2,'sales')",
		"CREATE TABLE staff(id INTEGER PRIMARY KEY, name TEXT, dept_id INTEGER)",
		"INSERT INTO staff VALUES(1,'Alice',1)",
		"INSERT INTO staff VALUES(2,'Bob',1)",
		"INSERT INTO staff VALUES(3,'Carol',2)",
	}
	return []sqlTestCase{
		{
			name: "REQ-VIEW-030_view_with_join",
			setup: append(joinSetup,
				"CREATE VIEW vw_staff_dept AS SELECT s.name, d.dname FROM staff s JOIN dept d ON s.dept_id=d.id"),
			query:    "SELECT name, dname FROM vw_staff_dept ORDER BY name",
			wantRows: [][]interface{}{{"Alice", "eng"}, {"Bob", "eng"}, {"Carol", "sales"}},
		},
		{
			name: "REQ-VIEW-031_nested_view",
			setup: append(joinSetup,
				"CREATE VIEW vw_base AS SELECT id, name, dept_id FROM staff",
				"CREATE VIEW vw_nested AS SELECT name FROM vw_base WHERE dept_id=1"),
			query:    "SELECT name FROM vw_nested ORDER BY name",
			wantRows: [][]interface{}{{"Alice"}, {"Bob"}},
		},
		{
			name: "REQ-VIEW-032_view_with_group_by",
			setup: append(joinSetup,
				"CREATE VIEW vw_dept_count AS SELECT dept_id, COUNT(*) AS cnt FROM staff GROUP BY dept_id"),
			query:    "SELECT dept_id, cnt FROM vw_dept_count ORDER BY dept_id",
			wantRows: [][]interface{}{{int64(1), int64(2)}, {int64(2), int64(1)}},
		},
		{
			name: "REQ-VIEW-033_view_with_having",
			skip: "pre-existing: view with HAVING clause",
			setup: append(joinSetup,
				"CREATE VIEW vw_dept_having AS SELECT dept_id, COUNT(*) AS cnt FROM staff GROUP BY dept_id HAVING cnt > 1"),
			query:    "SELECT dept_id, cnt FROM vw_dept_having",
			wantRows: [][]interface{}{{int64(1), int64(2)}},
		},
		{
			name: "REQ-VIEW-034_view_with_distinct",
			skip: "pre-existing: view with DISTINCT",
			setup: []string{
				"CREATE TABLE vd1(a INTEGER)",
				"INSERT INTO vd1 VALUES(1)", "INSERT INTO vd1 VALUES(1)", "INSERT INTO vd1 VALUES(2)",
				"CREATE VIEW vw_distinct AS SELECT DISTINCT a FROM vd1",
			},
			query:    "SELECT a FROM vw_distinct ORDER BY a",
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}},
		},
		{
			name: "REQ-VIEW-035_view_with_subquery",
			setup: []string{
				"CREATE TABLE vs1(a INTEGER, b TEXT)",
				"INSERT INTO vs1 VALUES(1,'x')", "INSERT INTO vs1 VALUES(2,'y')", "INSERT INTO vs1 VALUES(3,'z')",
				"CREATE VIEW vw_sub AS SELECT a, b FROM vs1 WHERE a > (SELECT MIN(a) FROM vs1)",
			},
			query:    "SELECT a, b FROM vw_sub ORDER BY a",
			wantRows: [][]interface{}{{int64(2), "y"}, {int64(3), "z"}},
		},
	}
}
