// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import "testing"

// TestTrinity_Collation validates BINARY, NOCASE, and RTRIM collation
// behaviour including indexed lookups per DO-178C trace.
func TestTrinity_Collation(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityCollationTests())
}

func buildTrinityCollationTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genCollationBinaryTests()...)
	tests = append(tests, genCollationNocaseTests()...)
	tests = append(tests, genCollationRtrimTests()...)
	tests = append(tests, genCollationIndexTests()...)
	return tests
}

// ---------------------------------------------------------------------------
// BINARY collation (default): case-sensitive comparison and ORDER BY
// ---------------------------------------------------------------------------

func genCollationBinaryTests() []sqlTestCase {
	binarySetup := []string{
		"CREATE TABLE coll_bin(v TEXT COLLATE BINARY)",
		"INSERT INTO coll_bin VALUES('abc')",
		"INSERT INTO coll_bin VALUES('ABC')",
		"INSERT INTO coll_bin VALUES('Abc')",
		"INSERT INTO coll_bin VALUES('def')",
		"INSERT INTO coll_bin VALUES('DEF')",
	}
	return []sqlTestCase{
		{
			name:     "REQ-TCOLL-001_binary_eq_case_sensitive",
			setup:    binarySetup,
			query:    "SELECT v FROM coll_bin WHERE v = 'abc'",
			wantRows: [][]interface{}{{"abc"}},
		},
		{
			name:     "REQ-TCOLL-002_binary_neq_case_mismatch",
			setup:    binarySetup,
			query:    "SELECT COUNT(*) FROM coll_bin WHERE v = 'aBc'",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:  "REQ-TCOLL-003_binary_order_by",
			setup: binarySetup,
			query: "SELECT v FROM coll_bin ORDER BY v",
			wantRows: [][]interface{}{
				{"ABC"}, {"Abc"}, {"DEF"}, {"abc"}, {"def"},
			},
		},
		{
			name:     "REQ-TCOLL-004_binary_lt_case",
			setup:    binarySetup,
			query:    "SELECT COUNT(*) FROM coll_bin WHERE v < 'abc'",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-TCOLL-005_binary_gt_case",
			setup:    binarySetup,
			query:    "SELECT COUNT(*) FROM coll_bin WHERE v > 'abc'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:  "REQ-TCOLL-006_binary_between",
			setup: binarySetup,
			query: "SELECT v FROM coll_bin WHERE v BETWEEN 'A' AND 'Z' ORDER BY v",
			wantRows: [][]interface{}{
				{"ABC"}, {"Abc"}, {"DEF"},
			},
		},
		{
			name:     "REQ-TCOLL-007_binary_min",
			setup:    binarySetup,
			query:    "SELECT MIN(v) FROM coll_bin",
			wantRows: [][]interface{}{{"ABC"}},
		},
		{
			name:     "REQ-TCOLL-008_binary_max",
			setup:    binarySetup,
			query:    "SELECT MAX(v) FROM coll_bin",
			wantRows: [][]interface{}{{"def"}},
		},
	}
}

// ---------------------------------------------------------------------------
// NOCASE collation: case-insensitive comparison and ORDER BY
// ---------------------------------------------------------------------------

func genCollationNocaseTests() []sqlTestCase {
	nocaseSetup := []string{
		"CREATE TABLE coll_nc(v TEXT COLLATE NOCASE)",
		"INSERT INTO coll_nc VALUES('apple')",
		"INSERT INTO coll_nc VALUES('APPLE')",
		"INSERT INTO coll_nc VALUES('Apple')",
		"INSERT INTO coll_nc VALUES('banana')",
		"INSERT INTO coll_nc VALUES('BANANA')",
		"INSERT INTO coll_nc VALUES('cherry')",
	}
	return []sqlTestCase{
		{
			name:     "REQ-TCOLL-010_nocase_eq_lower",
			setup:    nocaseSetup,
			query:    "SELECT COUNT(*) FROM coll_nc WHERE v = 'apple'",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-TCOLL-011_nocase_eq_upper",
			setup:    nocaseSetup,
			query:    "SELECT COUNT(*) FROM coll_nc WHERE v = 'BANANA'",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name:     "REQ-TCOLL-012_nocase_eq_mixed",
			setup:    nocaseSetup,
			query:    "SELECT COUNT(*) FROM coll_nc WHERE v = 'ApPlE'",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:  "REQ-TCOLL-013_nocase_order_by",
			setup: nocaseSetup,
			query: "SELECT v FROM coll_nc ORDER BY v, rowid",
			wantRows: [][]interface{}{
				{"apple"}, {"APPLE"}, {"Apple"},
				{"banana"}, {"BANANA"},
				{"cherry"},
			},
		},
		{
			name:     "REQ-TCOLL-014_nocase_distinct",
			setup:    nocaseSetup,
			query:    "SELECT COUNT(DISTINCT v) FROM coll_nc",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-TCOLL-015_nocase_group_by",
			setup:    nocaseSetup,
			query:    "SELECT COUNT(*) FROM coll_nc GROUP BY v ORDER BY v",
			wantRows: [][]interface{}{{int64(3)}, {int64(2)}, {int64(1)}},
		},
		{
			name:     "REQ-TCOLL-016_nocase_in_list",
			setup:    nocaseSetup,
			query:    "SELECT COUNT(*) FROM coll_nc WHERE v IN ('apple','banana')",
			wantRows: [][]interface{}{{int64(5)}},
		},
		{
			name:     "REQ-TCOLL-017_nocase_min",
			setup:    nocaseSetup,
			query:    "SELECT MIN(v) FROM coll_nc",
			wantRows: [][]interface{}{{"apple"}},
		},
		{
			name:     "REQ-TCOLL-018_nocase_max",
			setup:    nocaseSetup,
			query:    "SELECT MAX(v) FROM coll_nc",
			wantRows: [][]interface{}{{"cherry"}},
		},
	}
}

// ---------------------------------------------------------------------------
// RTRIM collation: trailing-space insensitive
// ---------------------------------------------------------------------------

func genCollationRtrimTests() []sqlTestCase {
	rtrimSetup := []string{
		"CREATE TABLE coll_rt(v TEXT COLLATE RTRIM)",
		"INSERT INTO coll_rt VALUES('abc')",
		"INSERT INTO coll_rt VALUES('abc   ')",
		"INSERT INTO coll_rt VALUES('abc ')",
		"INSERT INTO coll_rt VALUES('def')",
		"INSERT INTO coll_rt VALUES('def  ')",
	}
	return []sqlTestCase{
		{
			name:     "REQ-TCOLL-020_rtrim_eq_trailing_spaces",
			setup:    rtrimSetup,
			query:    "SELECT COUNT(*) FROM coll_rt WHERE v = 'abc'",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-TCOLL-021_rtrim_eq_with_spaces_in_query",
			setup:    rtrimSetup,
			query:    "SELECT COUNT(*) FROM coll_rt WHERE v = 'abc    '",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-TCOLL-022_rtrim_ne_leading_space",
			setup:    rtrimSetup,
			query:    "SELECT COUNT(*) FROM coll_rt WHERE v = ' abc'",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-TCOLL-023_rtrim_distinct",
			setup:    rtrimSetup,
			query:    "SELECT COUNT(DISTINCT v) FROM coll_rt",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name:  "REQ-TCOLL-024_rtrim_order_by",
			setup: rtrimSetup,
			query: "SELECT v FROM coll_rt ORDER BY v, rowid",
			wantRows: [][]interface{}{
				{"abc"}, {"abc   "}, {"abc "},
				{"def"}, {"def  "},
			},
		},
		{
			name:     "REQ-TCOLL-025_rtrim_group_by_count",
			setup:    rtrimSetup,
			query:    "SELECT COUNT(*) FROM coll_rt GROUP BY v ORDER BY v",
			wantRows: [][]interface{}{{int64(3)}, {int64(2)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Collation with indexes
// ---------------------------------------------------------------------------

func genCollationIndexTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name: "REQ-TCOLL-030_idx_binary_order",
			setup: []string{
				"CREATE TABLE coll_idx_bin(v TEXT COLLATE BINARY)",
				"CREATE INDEX idx_bin ON coll_idx_bin(v)",
				"INSERT INTO coll_idx_bin VALUES('banana')",
				"INSERT INTO coll_idx_bin VALUES('Apple')",
				"INSERT INTO coll_idx_bin VALUES('cherry')",
				"INSERT INTO coll_idx_bin VALUES('apple')",
			},
			query: "SELECT v FROM coll_idx_bin ORDER BY v",
			wantRows: [][]interface{}{
				{"Apple"}, {"apple"}, {"banana"}, {"cherry"},
			},
		},
		{
			name: "REQ-TCOLL-031_idx_nocase_order",
			setup: []string{
				"CREATE TABLE coll_idx_nc(v TEXT COLLATE NOCASE)",
				"CREATE INDEX idx_nc ON coll_idx_nc(v)",
				"INSERT INTO coll_idx_nc VALUES('banana')",
				"INSERT INTO coll_idx_nc VALUES('APPLE')",
				"INSERT INTO coll_idx_nc VALUES('cherry')",
				"INSERT INTO coll_idx_nc VALUES('apple')",
			},
			query: "SELECT v FROM coll_idx_nc ORDER BY v, rowid",
			wantRows: [][]interface{}{
				{"APPLE"}, {"apple"}, {"banana"}, {"cherry"},
			},
		},
		{
			name: "REQ-TCOLL-032_idx_nocase_lookup",
			setup: []string{
				"CREATE TABLE coll_idx_nc2(v TEXT COLLATE NOCASE)",
				"CREATE INDEX idx_nc2 ON coll_idx_nc2(v)",
				"INSERT INTO coll_idx_nc2 VALUES('Hello')",
				"INSERT INTO coll_idx_nc2 VALUES('HELLO')",
				"INSERT INTO coll_idx_nc2 VALUES('World')",
			},
			query:    "SELECT COUNT(*) FROM coll_idx_nc2 WHERE v = 'hello'",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name: "REQ-TCOLL-033_idx_rtrim_lookup",
			setup: []string{
				"CREATE TABLE coll_idx_rt(v TEXT COLLATE RTRIM)",
				"CREATE INDEX idx_rt ON coll_idx_rt(v)",
				"INSERT INTO coll_idx_rt VALUES('foo')",
				"INSERT INTO coll_idx_rt VALUES('foo  ')",
				"INSERT INTO coll_idx_rt VALUES('bar')",
			},
			query:    "SELECT COUNT(*) FROM coll_idx_rt WHERE v = 'foo'",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name: "REQ-TCOLL-034_idx_nocase_range",
			setup: []string{
				"CREATE TABLE coll_idx_rng(v TEXT COLLATE NOCASE)",
				"CREATE INDEX idx_rng ON coll_idx_rng(v)",
				"INSERT INTO coll_idx_rng VALUES('alpha')",
				"INSERT INTO coll_idx_rng VALUES('BETA')",
				"INSERT INTO coll_idx_rng VALUES('gamma')",
				"INSERT INTO coll_idx_rng VALUES('DELTA')",
			},
			query:    "SELECT COUNT(*) FROM coll_idx_rng WHERE v >= 'beta' AND v <= 'delta'",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name: "REQ-TCOLL-035_unique_idx_nocase",
			setup: []string{
				"CREATE TABLE coll_uniq(v TEXT COLLATE NOCASE)",
				"CREATE UNIQUE INDEX idx_uniq ON coll_uniq(v)",
				"INSERT INTO coll_uniq VALUES('test')",
			},
			exec:    "INSERT INTO coll_uniq VALUES('TEST')",
			wantErr: true,
			errLike: "UNIQUE constraint",
		},
		{
			name: "REQ-TCOLL-036_unique_idx_rtrim",
			setup: []string{
				"CREATE TABLE coll_uniq_rt(v TEXT COLLATE RTRIM)",
				"CREATE UNIQUE INDEX idx_uniq_rt ON coll_uniq_rt(v)",
				"INSERT INTO coll_uniq_rt VALUES('test')",
			},
			exec:    "INSERT INTO coll_uniq_rt VALUES('test  ')",
			wantErr: true,
			errLike: "UNIQUE constraint",
		},
	}
}
