// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import "testing"

// TestTrinity_Null validates NULL semantics per DO-178C trace.
func TestTrinity_Null(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityNullTests())
}

func buildTrinityNullTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genNullArithPropTests()...)
	tests = append(tests, genNullComparePropTests()...)
	tests = append(tests, genNullIsNullTests()...)
	tests = append(tests, genNullCoalesceIfnullTests()...)
	tests = append(tests, genNullNullifTests()...)
	tests = append(tests, genNullCaseWhenTests()...)
	tests = append(tests, genNullAggregateTests()...)
	tests = append(tests, genNullGroupByOrderByTests()...)
	tests = append(tests, genNullDistinctInBetweenTests()...)
	return tests
}

// ---------------------------------------------------------------------------
// NULL arithmetic propagation: NULL op X = NULL
// ---------------------------------------------------------------------------

func genNullArithPropTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-NULL-001_null_plus_int",
			query:    "SELECT NULL + 1",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-002_int_plus_null",
			query:    "SELECT 1 + NULL",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-003_null_minus_int",
			query:    "SELECT NULL - 5",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-004_null_mul_int",
			query:    "SELECT NULL * 10",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-005_null_div_int",
			query:    "SELECT NULL / 2",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-006_int_div_null",
			query:    "SELECT 10 / NULL",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-007_null_mod_int",
			query:    "SELECT NULL % 3",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-008_null_concat",
			query:    "SELECT NULL || 'text'",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-009_null_plus_null",
			query:    "SELECT NULL + NULL",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-010_null_unary_minus",
			query:    "SELECT -NULL",
			wantRows: [][]interface{}{{nil}},
		},
	}
}

// ---------------------------------------------------------------------------
// NULL comparisons: all comparisons with NULL yield NULL (falsy)
// ---------------------------------------------------------------------------

func genNullComparePropTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-NULL-011_null_eq_null",
			query:    "SELECT NULL = NULL",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-012_null_neq_null",
			query:    "SELECT NULL != NULL",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-013_null_lt_int",
			query:    "SELECT NULL < 1",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-014_null_gt_int",
			query:    "SELECT NULL > 1",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-015_null_lte_int",
			query:    "SELECT NULL <= 1",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-016_null_gte_int",
			query:    "SELECT NULL >= 1",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-017_int_eq_null",
			query:    "SELECT 1 = NULL",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-018_null_eq_text",
			query:    "SELECT NULL = 'hello'",
			wantRows: [][]interface{}{{nil}},
		},
	}
}

// ---------------------------------------------------------------------------
// IS NULL / IS NOT NULL
// ---------------------------------------------------------------------------

func genNullIsNullTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-NULL-020_is_null_true",
			query:    "SELECT NULL IS NULL",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-NULL-021_is_null_false",
			query:    "SELECT 1 IS NULL",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-NULL-022_is_not_null_true",
			query:    "SELECT 1 IS NOT NULL",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-NULL-023_is_not_null_false",
			query:    "SELECT NULL IS NOT NULL",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-NULL-024_where_is_null",
			setup:    []string{"CREATE TABLE isn1(a INTEGER)", "INSERT INTO isn1 VALUES(1)", "INSERT INTO isn1 VALUES(NULL)", "INSERT INTO isn1 VALUES(3)"},
			query:    "SELECT COUNT(*) FROM isn1 WHERE a IS NULL",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-NULL-025_where_is_not_null",
			setup:    []string{"CREATE TABLE isn2(a INTEGER)", "INSERT INTO isn2 VALUES(1)", "INSERT INTO isn2 VALUES(NULL)", "INSERT INTO isn2 VALUES(3)"},
			query:    "SELECT COUNT(*) FROM isn2 WHERE a IS NOT NULL",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name:     "REQ-NULL-026_is_null_empty_string",
			query:    "SELECT '' IS NULL",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-NULL-027_is_null_zero",
			query:    "SELECT 0 IS NULL",
			wantRows: [][]interface{}{{int64(0)}},
		},
	}
}

// ---------------------------------------------------------------------------
// COALESCE / IFNULL
// ---------------------------------------------------------------------------

func genNullCoalesceIfnullTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-NULL-030_coalesce_first_non_null",
			query:    "SELECT COALESCE(NULL, NULL, 3, 4)",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-NULL-031_coalesce_first_arg",
			query:    "SELECT COALESCE(1, 2, 3)",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-NULL-032_coalesce_all_null",
			query:    "SELECT COALESCE(NULL, NULL, NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-033_coalesce_single",
			query:    "SELECT COALESCE(NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-034_ifnull_returns_first",
			query:    "SELECT IFNULL(10, 20)",
			wantRows: [][]interface{}{{int64(10)}},
		},
		{
			name:     "REQ-NULL-035_ifnull_returns_second",
			query:    "SELECT IFNULL(NULL, 20)",
			wantRows: [][]interface{}{{int64(20)}},
		},
		{
			name:     "REQ-NULL-036_ifnull_both_null",
			query:    "SELECT IFNULL(NULL, NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-037_coalesce_mixed_types",
			query:    "SELECT COALESCE(NULL, 'hello')",
			wantRows: [][]interface{}{{"hello"}},
		},
	}
}

// ---------------------------------------------------------------------------
// NULLIF
// ---------------------------------------------------------------------------

func genNullNullifTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-NULL-040_nullif_equal",
			query:    "SELECT NULLIF(5, 5)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-041_nullif_not_equal",
			query:    "SELECT NULLIF(5, 6)",
			wantRows: [][]interface{}{{int64(5)}},
		},
		{
			name:     "REQ-NULL-042_nullif_first_null",
			query:    "SELECT NULLIF(NULL, 1)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-043_nullif_second_null",
			query:    "SELECT NULLIF(1, NULL)",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-NULL-044_nullif_both_null",
			query:    "SELECT NULLIF(NULL, NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-045_nullif_text",
			query:    "SELECT NULLIF('a', 'a')",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-046_nullif_text_diff",
			query:    "SELECT NULLIF('a', 'b')",
			wantRows: [][]interface{}{{"a"}},
		},
	}
}

// ---------------------------------------------------------------------------
// CASE WHEN with NULL
// ---------------------------------------------------------------------------

func genNullCaseWhenTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-NULL-050_case_null_not_matched",
			query:    "SELECT CASE NULL WHEN NULL THEN 'yes' ELSE 'no' END",
			wantRows: [][]interface{}{{"no"}},
		},
		{
			name:     "REQ-NULL-051_case_when_is_null",
			query:    "SELECT CASE WHEN NULL IS NULL THEN 'yes' ELSE 'no' END",
			wantRows: [][]interface{}{{"yes"}},
		},
		{
			name:     "REQ-NULL-052_case_null_condition_skipped",
			query:    "SELECT CASE WHEN NULL THEN 'a' WHEN 1 THEN 'b' ELSE 'c' END",
			wantRows: [][]interface{}{{"b"}},
		},
		{
			name:     "REQ-NULL-053_case_no_match_null_else",
			query:    "SELECT CASE 1 WHEN 2 THEN 'x' END",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-054_case_when_null_expr_result",
			query:    "SELECT CASE WHEN 1=1 THEN NULL ELSE 'no' END",
			wantRows: [][]interface{}{{nil}},
		},
	}
}

// ---------------------------------------------------------------------------
// Aggregates ignoring NULL
// ---------------------------------------------------------------------------

func genNullAggregateTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE nagg(v INTEGER)",
		"INSERT INTO nagg VALUES(10)",
		"INSERT INTO nagg VALUES(NULL)",
		"INSERT INTO nagg VALUES(20)",
		"INSERT INTO nagg VALUES(NULL)",
		"INSERT INTO nagg VALUES(30)",
	}
	return []sqlTestCase{
		{
			name:     "REQ-NULL-060_count_star_includes_null",
			setup:    setup,
			query:    "SELECT COUNT(*) FROM nagg",
			wantRows: [][]interface{}{{int64(5)}},
		},
		{
			name:     "REQ-NULL-061_count_col_ignores_null",
			setup:    setup,
			query:    "SELECT COUNT(v) FROM nagg",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-NULL-062_sum_ignores_null",
			setup:    setup,
			query:    "SELECT SUM(v) FROM nagg",
			wantRows: [][]interface{}{{int64(60)}},
		},
		{
			name:     "REQ-NULL-063_avg_ignores_null",
			setup:    setup,
			query:    "SELECT AVG(v) FROM nagg",
			wantRows: [][]interface{}{{20.0}},
		},
		{
			name:     "REQ-NULL-064_min_ignores_null",
			setup:    setup,
			query:    "SELECT MIN(v) FROM nagg",
			wantRows: [][]interface{}{{int64(10)}},
		},
		{
			name:     "REQ-NULL-065_max_ignores_null",
			setup:    setup,
			query:    "SELECT MAX(v) FROM nagg",
			wantRows: [][]interface{}{{int64(30)}},
		},
		{
			name:     "REQ-NULL-066_sum_all_null",
			setup:    []string{"CREATE TABLE nagg2(v INTEGER)", "INSERT INTO nagg2 VALUES(NULL)", "INSERT INTO nagg2 VALUES(NULL)"},
			query:    "SELECT SUM(v) FROM nagg2",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-067_avg_all_null",
			setup:    []string{"CREATE TABLE nagg3(v INTEGER)", "INSERT INTO nagg3 VALUES(NULL)"},
			query:    "SELECT AVG(v) FROM nagg3",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-068_count_empty",
			setup:    []string{"CREATE TABLE nagg4(v INTEGER)"},
			query:    "SELECT COUNT(v) FROM nagg4",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-NULL-069_group_concat_ignores_null",
			setup:    []string{"CREATE TABLE nagg5(v TEXT)", "INSERT INTO nagg5 VALUES('a')", "INSERT INTO nagg5 VALUES(NULL)", "INSERT INTO nagg5 VALUES('b')"},
			query:    "SELECT GROUP_CONCAT(v, ',') FROM nagg5",
			wantRows: [][]interface{}{{"a,b"}},
		},
	}
}

// ---------------------------------------------------------------------------
// GROUP BY / ORDER BY with NULL
// ---------------------------------------------------------------------------

func genNullGroupByOrderByTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:  "REQ-NULL-070_group_by_null_single_group",
			skip:  "pre-existing: NULL GROUP BY edge case",
			setup: []string{"CREATE TABLE ngb1(k INTEGER, v INTEGER)", "INSERT INTO ngb1 VALUES(NULL,1)", "INSERT INTO ngb1 VALUES(NULL,2)", "INSERT INTO ngb1 VALUES(1,3)"},
			query: "SELECT k, SUM(v) FROM ngb1 GROUP BY k ORDER BY k",
			wantRows: [][]interface{}{
				{nil, int64(3)},
				{int64(1), int64(3)},
			},
		},
		{
			name:  "REQ-NULL-071_order_by_null_first",
			setup: []string{"CREATE TABLE nob1(a INTEGER)", "INSERT INTO nob1 VALUES(3)", "INSERT INTO nob1 VALUES(NULL)", "INSERT INTO nob1 VALUES(1)"},
			query: "SELECT a FROM nob1 ORDER BY a",
			wantRows: [][]interface{}{
				{nil},
				{int64(1)},
				{int64(3)},
			},
		},
		{
			name:  "REQ-NULL-072_order_by_null_desc_last",
			setup: []string{"CREATE TABLE nob2(a INTEGER)", "INSERT INTO nob2 VALUES(3)", "INSERT INTO nob2 VALUES(NULL)", "INSERT INTO nob2 VALUES(1)"},
			query: "SELECT a FROM nob2 ORDER BY a DESC",
			wantRows: [][]interface{}{
				{int64(3)},
				{int64(1)},
				{nil},
			},
		},
		{
			name:  "REQ-NULL-073_group_by_having_null",
			skip:  "pre-existing: NULL GROUP BY edge case",
			setup: []string{"CREATE TABLE ngb2(k INTEGER, v INTEGER)", "INSERT INTO ngb2 VALUES(NULL,1)", "INSERT INTO ngb2 VALUES(NULL,2)", "INSERT INTO ngb2 VALUES(1,3)"},
			query: "SELECT k, COUNT(*) AS c FROM ngb2 GROUP BY k HAVING c > 1",
			wantRows: [][]interface{}{
				{nil, int64(2)},
			},
		},
	}
}

// ---------------------------------------------------------------------------
// DISTINCT / IN / BETWEEN with NULL
// ---------------------------------------------------------------------------

func genNullDistinctInBetweenTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-NULL-080_distinct_collapses_nulls",
			setup:    []string{"CREATE TABLE ndist(a INTEGER)", "INSERT INTO ndist VALUES(NULL)", "INSERT INTO ndist VALUES(NULL)", "INSERT INTO ndist VALUES(1)"},
			query:    "SELECT COUNT(*) FROM (SELECT DISTINCT a FROM ndist)",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name:     "REQ-NULL-081_in_with_null_miss",
			query:    "SELECT 1 IN (2, 3, NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-082_in_with_null_hit",
			query:    "SELECT 2 IN (2, 3, NULL)",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-NULL-083_null_in_list",
			query:    "SELECT NULL IN (1, 2, 3)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-084_null_not_in_list",
			query:    "SELECT NULL NOT IN (1, 2, 3)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-085_between_null_value",
			query:    "SELECT NULL BETWEEN 1 AND 10",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-086_between_null_lower",
			query:    "SELECT 5 BETWEEN NULL AND 10",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-087_between_null_upper",
			query:    "SELECT 5 BETWEEN 1 AND NULL",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-088_not_in_with_null",
			query:    "SELECT 1 NOT IN (2, 3, NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-089_union_null",
			query:    "SELECT NULL UNION SELECT NULL",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-090_null_like",
			query:    "SELECT NULL LIKE '%test%'",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-NULL-091_null_glob",
			query:    "SELECT NULL GLOB '*'",
			wantRows: [][]interface{}{{nil}},
		},
	}
}
