// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import "testing"

// TestTrinity_Core validates core SQL functionality per DO-178C trace.
func TestTrinity_Core(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityCoreTests())
}

func buildTrinityCoreTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genCoreCreateTableTests()...)
	tests = append(tests, genCoreInsertSelectTests()...)
	tests = append(tests, genCoreUpdateDeleteTests()...)
	tests = append(tests, genCoreWhereTests()...)
	tests = append(tests, genCoreLimitOffsetTests()...)
	tests = append(tests, genCoreRowidTests()...)
	tests = append(tests, genCoreIPKTests()...)
	tests = append(tests, genCoreDDLTests()...)
	return tests
}

// ---------------------------------------------------------------------------
// CREATE TABLE
// ---------------------------------------------------------------------------

func genCoreCreateTableTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-CORE-001_create_simple_table",
			setup:    []string{"CREATE TABLE t1(a, b, c)"},
			query:    "SELECT name FROM sqlite_master WHERE type='table' AND name='t1'",
			wantRows: [][]interface{}{{"t1"}},
		},
		{
			name:     "REQ-CORE-002_create_table_with_types",
			setup:    []string{"CREATE TABLE t2(id INTEGER, name TEXT, val REAL)"},
			query:    "SELECT name FROM sqlite_master WHERE type='table' AND name='t2'",
			wantRows: [][]interface{}{{"t2"}},
		},
		{
			name:     "REQ-CORE-003_create_table_if_not_exists",
			setup:    []string{"CREATE TABLE t3(x)", "CREATE TABLE IF NOT EXISTS t3(x)"},
			query:    "SELECT COUNT(*) FROM sqlite_master WHERE name='t3'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:    "REQ-CORE-004_create_duplicate_table_error",
			setup:   []string{"CREATE TABLE t4(x)"},
			exec:    "CREATE TABLE t4(x)",
			wantErr: true,
			errLike: "already exists",
		},
		{
			name: "REQ-CORE-005_create_table_multiple_columns",
			setup:    []string{"CREATE TABLE t5(a INT, b TEXT, c REAL, d BLOB, e)"},
			query:    "SELECT COUNT(*) FROM pragma_table_info('t5')",
			wantRows: [][]interface{}{{int64(5)}},
		},
		{
			name:     "REQ-CORE-006_create_table_with_default",
			setup:    []string{"CREATE TABLE t6(a INTEGER DEFAULT 42, b TEXT DEFAULT 'hello')"},
			exec:     "INSERT INTO t6(a) VALUES(NULL)",
			query:    "",
			wantRows: nil,
		},
		{
			name: "REQ-CORE-007_create_table_default_select",
			setup:    []string{"CREATE TABLE t7(a INTEGER DEFAULT 42, b TEXT DEFAULT 'hello')", "INSERT INTO t7(b) VALUES('world')"},
			query:    "SELECT a, b FROM t7",
			wantRows: [][]interface{}{{int64(42), "world"}},
		},
		{
			name:    "REQ-CORE-008_create_table_not_null",
			setup:   []string{"CREATE TABLE t8(a INTEGER NOT NULL)"},
			exec:    "INSERT INTO t8(a) VALUES(NULL)",
			wantErr: true,
			errLike: "NOT NULL",
		},
	}
}

// ---------------------------------------------------------------------------
// INSERT / SELECT basics
// ---------------------------------------------------------------------------

func genCoreInsertSelectTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-CORE-010_insert_single_row",
			setup:    []string{"CREATE TABLE ins1(a, b)", "INSERT INTO ins1 VALUES(1, 'one')"},
			query:    "SELECT a, b FROM ins1",
			wantRows: [][]interface{}{{int64(1), "one"}},
		},
		{
			name:     "REQ-CORE-011_insert_multiple_rows",
			setup:    []string{"CREATE TABLE ins2(a, b)", "INSERT INTO ins2 VALUES(1,'a')", "INSERT INTO ins2 VALUES(2,'b')", "INSERT INTO ins2 VALUES(3,'c')"},
			query:    "SELECT COUNT(*) FROM ins2",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-CORE-012_insert_null_value",
			setup:    []string{"CREATE TABLE ins3(a, b)", "INSERT INTO ins3 VALUES(1, NULL)"},
			query:    "SELECT a, b FROM ins3",
			wantRows: [][]interface{}{{int64(1), nil}},
		},
		{
			name:     "REQ-CORE-013_select_star",
			setup:    []string{"CREATE TABLE ins4(a, b, c)", "INSERT INTO ins4 VALUES(1, 2, 3)"},
			query:    "SELECT * FROM ins4",
			wantRows: [][]interface{}{{int64(1), int64(2), int64(3)}},
		},
		{
			name:     "REQ-CORE-014_select_column_alias",
			setup:    []string{"CREATE TABLE ins5(a)", "INSERT INTO ins5 VALUES(42)"},
			query:    "SELECT a AS val FROM ins5",
			wantRows: [][]interface{}{{int64(42)}},
		},
		{
			name:     "REQ-CORE-015_select_expression",
			setup:    []string{"CREATE TABLE ins6(a, b)", "INSERT INTO ins6 VALUES(10, 3)"},
			query:    "SELECT a + b, a - b, a * b FROM ins6",
			wantRows: [][]interface{}{{int64(13), int64(7), int64(30)}},
		},
		{
			name:     "REQ-CORE-016_select_distinct",
			setup:    []string{"CREATE TABLE ins7(a)", "INSERT INTO ins7 VALUES(1)", "INSERT INTO ins7 VALUES(1)", "INSERT INTO ins7 VALUES(2)"},
			query:    "SELECT DISTINCT a FROM ins7 ORDER BY a",
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}},
		},
		{
			name:     "REQ-CORE-017_insert_or_replace",
			setup:    []string{"CREATE TABLE ins8(id INTEGER PRIMARY KEY, v TEXT)", "INSERT INTO ins8 VALUES(1,'old')", "INSERT OR REPLACE INTO ins8 VALUES(1,'new')"},
			query:    "SELECT id, v FROM ins8",
			wantRows: [][]interface{}{{int64(1), "new"}},
		},
		{
			name:     "REQ-CORE-018_insert_or_ignore",
			setup:    []string{"CREATE TABLE ins9(id INTEGER PRIMARY KEY, v TEXT)", "INSERT INTO ins9 VALUES(1,'first')", "INSERT OR IGNORE INTO ins9 VALUES(1,'second')"},
			query:    "SELECT v FROM ins9 WHERE id=1",
			wantRows: [][]interface{}{{"first"}},
		},
	}
}

// ---------------------------------------------------------------------------
// UPDATE / DELETE
// ---------------------------------------------------------------------------

func genCoreUpdateDeleteTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:  "REQ-CORE-020_update_single_row",
			setup: []string{"CREATE TABLE upd1(a, b)", "INSERT INTO upd1 VALUES(1,'old')"},
			exec:  "UPDATE upd1 SET b='new' WHERE a=1",
			query: "",
		},
		{
			name:     "REQ-CORE-021_update_verify",
			setup:    []string{"CREATE TABLE upd2(a, b)", "INSERT INTO upd2 VALUES(1,'old')", "UPDATE upd2 SET b='new' WHERE a=1"},
			query:    "SELECT b FROM upd2 WHERE a=1",
			wantRows: [][]interface{}{{"new"}},
		},
		{
			name:     "REQ-CORE-022_update_all_rows",
			setup:    []string{"CREATE TABLE upd3(a, b)", "INSERT INTO upd3 VALUES(1,'x')", "INSERT INTO upd3 VALUES(2,'y')", "UPDATE upd3 SET b='z'"},
			query:    "SELECT DISTINCT b FROM upd3",
			wantRows: [][]interface{}{{"z"}},
		},
		{
			name:     "REQ-CORE-023_update_no_match",
			setup:    []string{"CREATE TABLE upd4(a, b)", "INSERT INTO upd4 VALUES(1,'x')", "UPDATE upd4 SET b='y' WHERE a=999"},
			query:    "SELECT b FROM upd4",
			wantRows: [][]interface{}{{"x"}},
		},
		{
			name:     "REQ-CORE-024_delete_single_row",
			setup:    []string{"CREATE TABLE del1(a)", "INSERT INTO del1 VALUES(1)", "INSERT INTO del1 VALUES(2)", "DELETE FROM del1 WHERE a=1"},
			query:    "SELECT a FROM del1",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name:     "REQ-CORE-025_delete_all_rows",
			setup:    []string{"CREATE TABLE del2(a)", "INSERT INTO del2 VALUES(1)", "INSERT INTO del2 VALUES(2)", "DELETE FROM del2"},
			query:    "SELECT COUNT(*) FROM del2",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-CORE-026_delete_no_match",
			setup:    []string{"CREATE TABLE del3(a)", "INSERT INTO del3 VALUES(1)", "DELETE FROM del3 WHERE a=999"},
			query:    "SELECT COUNT(*) FROM del3",
			wantRows: [][]interface{}{{int64(1)}},
		},
	}
}

// ---------------------------------------------------------------------------
// WHERE clause
// ---------------------------------------------------------------------------

func genCoreWhereTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE w1(a INTEGER, b TEXT)",
		"INSERT INTO w1 VALUES(1,'alpha')",
		"INSERT INTO w1 VALUES(2,'beta')",
		"INSERT INTO w1 VALUES(3,'gamma')",
		"INSERT INTO w1 VALUES(4,'delta')",
		"INSERT INTO w1 VALUES(5,'epsilon')",
	}
	return []sqlTestCase{
		{
			name:     "REQ-CORE-030_where_eq",
			setup:    setup,
			query:    "SELECT a FROM w1 WHERE a=3",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-CORE-031_where_neq",
			setup:    setup,
			query:    "SELECT COUNT(*) FROM w1 WHERE a!=3",
			wantRows: [][]interface{}{{int64(4)}},
		},
		{
			name:     "REQ-CORE-032_where_lt",
			setup:    setup,
			query:    "SELECT COUNT(*) FROM w1 WHERE a<3",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name:     "REQ-CORE-033_where_gt",
			setup:    setup,
			query:    "SELECT COUNT(*) FROM w1 WHERE a>3",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name:     "REQ-CORE-034_where_lte",
			setup:    setup,
			query:    "SELECT COUNT(*) FROM w1 WHERE a<=3",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-CORE-035_where_gte",
			setup:    setup,
			query:    "SELECT COUNT(*) FROM w1 WHERE a>=3",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-CORE-036_where_and",
			setup:    setup,
			query:    "SELECT a FROM w1 WHERE a>1 AND a<5 AND b='gamma'",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-CORE-037_where_or",
			setup:    setup,
			query:    "SELECT COUNT(*) FROM w1 WHERE a=1 OR a=5",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name:     "REQ-CORE-038_where_in",
			setup:    setup,
			query:    "SELECT COUNT(*) FROM w1 WHERE a IN (1,3,5)",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-CORE-039_where_between",
			setup:    setup,
			query:    "SELECT COUNT(*) FROM w1 WHERE a BETWEEN 2 AND 4",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-CORE-040_where_like",
			setup:    setup,
			query:    "SELECT b FROM w1 WHERE b LIKE '%eta'",
			wantRows: [][]interface{}{{"beta"}},
		},
		{
			name:     "REQ-CORE-041_where_not",
			setup:    setup,
			query:    "SELECT COUNT(*) FROM w1 WHERE NOT a=3",
			wantRows: [][]interface{}{{int64(4)}},
		},
	}
}

// ---------------------------------------------------------------------------
// LIMIT / OFFSET
// ---------------------------------------------------------------------------

func genCoreLimitOffsetTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE lim1(a INTEGER)",
		"INSERT INTO lim1 VALUES(1)",
		"INSERT INTO lim1 VALUES(2)",
		"INSERT INTO lim1 VALUES(3)",
		"INSERT INTO lim1 VALUES(4)",
		"INSERT INTO lim1 VALUES(5)",
	}
	return []sqlTestCase{
		{
			name:     "REQ-CORE-045_limit",
			setup:    setup,
			query:    "SELECT a FROM lim1 ORDER BY a LIMIT 3",
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}, {int64(3)}},
		},
		{
			name:     "REQ-CORE-046_limit_offset",
			setup:    setup,
			query:    "SELECT a FROM lim1 ORDER BY a LIMIT 2 OFFSET 2",
			wantRows: [][]interface{}{{int64(3)}, {int64(4)}},
		},
		{
			name:     "REQ-CORE-047_limit_zero",
			setup:    setup,
			query:    "SELECT a FROM lim1 ORDER BY a LIMIT 0",
			wantRows: nil,
		},
		{
			name:     "REQ-CORE-048_limit_exceeds_rows",
			setup:    setup,
			query:    "SELECT COUNT(*) FROM (SELECT a FROM lim1 LIMIT 100)",
			wantRows: [][]interface{}{{int64(5)}},
		},
	}
}

// ---------------------------------------------------------------------------
// ROWID
// ---------------------------------------------------------------------------

func genCoreRowidTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-CORE-050_rowid_auto_assign",
			setup:    []string{"CREATE TABLE rid1(a TEXT)", "INSERT INTO rid1 VALUES('x')", "INSERT INTO rid1 VALUES('y')"},
			query:    "SELECT rowid, a FROM rid1 ORDER BY rowid",
			wantRows: [][]interface{}{{int64(1), "x"}, {int64(2), "y"}},
		},
		{
			name: "REQ-CORE-051_rowid_explicit",
			setup:    []string{"CREATE TABLE rid2(a TEXT)", "INSERT INTO rid2(rowid, a) VALUES(100,'z')"},
			query:    "SELECT rowid, a FROM rid2",
			wantRows: [][]interface{}{{int64(100), "z"}},
		},
		{
			name:     "REQ-CORE-052_rowid_aliases",
			setup:    []string{"CREATE TABLE rid3(a TEXT)", "INSERT INTO rid3 VALUES('q')"},
			query:    "SELECT rowid, _rowid_, oid FROM rid3",
			wantRows: [][]interface{}{{int64(1), int64(1), int64(1)}},
		},
		{
			name:     "REQ-CORE-053_rowid_after_delete_gap",
			setup:    []string{"CREATE TABLE rid4(a INTEGER)", "INSERT INTO rid4 VALUES(10)", "INSERT INTO rid4 VALUES(20)", "DELETE FROM rid4 WHERE a=10", "INSERT INTO rid4 VALUES(30)"},
			query:    "SELECT rowid, a FROM rid4 ORDER BY rowid",
			wantRows: [][]interface{}{{int64(2), int64(20)}, {int64(3), int64(30)}},
		},
	}
}

// ---------------------------------------------------------------------------
// INTEGER PRIMARY KEY (alias for rowid)
// ---------------------------------------------------------------------------

func genCoreIPKTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-CORE-055_ipk_is_rowid",
			setup:    []string{"CREATE TABLE ipk1(id INTEGER PRIMARY KEY, v TEXT)", "INSERT INTO ipk1 VALUES(10,'a')"},
			query:    "SELECT id, rowid, v FROM ipk1",
			wantRows: [][]interface{}{{int64(10), int64(10), "a"}},
		},
		{
			name:     "REQ-CORE-056_ipk_autoincrement",
			setup:    []string{"CREATE TABLE ipk2(id INTEGER PRIMARY KEY, v TEXT)", "INSERT INTO ipk2(v) VALUES('a')", "INSERT INTO ipk2(v) VALUES('b')"},
			query:    "SELECT id, v FROM ipk2 ORDER BY id",
			wantRows: [][]interface{}{{int64(1), "a"}, {int64(2), "b"}},
		},
		{
			name:     "REQ-CORE-057_ipk_null_becomes_rowid",
			setup:    []string{"CREATE TABLE ipk3(id INTEGER PRIMARY KEY, v TEXT)", "INSERT INTO ipk3 VALUES(NULL,'z')"},
			query:    "SELECT id, v FROM ipk3",
			wantRows: [][]interface{}{{int64(1), "z"}},
		},
		{
			name:    "REQ-CORE-058_ipk_duplicate_error",
			setup:   []string{"CREATE TABLE ipk4(id INTEGER PRIMARY KEY, v TEXT)", "INSERT INTO ipk4 VALUES(1,'a')"},
			exec:    "INSERT INTO ipk4 VALUES(1,'b')",
			wantErr: true,
			errLike: "UNIQUE constraint",
		},
		{
			name:     "REQ-CORE-059_ipk_autoincrement_keyword",
			setup:    []string{"CREATE TABLE ipk5(id INTEGER PRIMARY KEY AUTOINCREMENT, v TEXT)", "INSERT INTO ipk5(v) VALUES('x')", "INSERT INTO ipk5(v) VALUES('y')"},
			query:    "SELECT id, v FROM ipk5 ORDER BY id",
			wantRows: [][]interface{}{{int64(1), "x"}, {int64(2), "y"}},
		},
	}
}

// ---------------------------------------------------------------------------
// DDL: DROP TABLE, ALTER TABLE
// ---------------------------------------------------------------------------

func genCoreDDLTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-CORE-060_drop_table",
			setup:    []string{"CREATE TABLE dd1(a)", "DROP TABLE dd1"},
			query:    "SELECT COUNT(*) FROM sqlite_master WHERE name='dd1'",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:    "REQ-CORE-061_drop_table_if_exists",
			exec:    "DROP TABLE IF EXISTS dd_nonexistent",
			wantErr: false,
		},
		{
			name:    "REQ-CORE-062_drop_nonexistent_error",
			exec:    "DROP TABLE dd_nonexistent",
			wantErr: true,
			errLike: "table not found",
		},
		{
			name:     "REQ-CORE-063_alter_table_rename",
			setup:    []string{"CREATE TABLE dd3a(a)", "ALTER TABLE dd3a RENAME TO dd3b"},
			query:    "SELECT name FROM sqlite_master WHERE type='table' AND name='dd3b'",
			wantRows: [][]interface{}{{"dd3b"}},
		},
		{
			name:     "REQ-CORE-064_alter_table_add_column",
			setup:    []string{"CREATE TABLE dd4(a)", "INSERT INTO dd4 VALUES(1)", "ALTER TABLE dd4 ADD COLUMN b TEXT DEFAULT 'dflt'"},
			query:    "SELECT a, b FROM dd4",
			wantRows: [][]interface{}{{int64(1), "dflt"}},
		},
		{
			name:    "REQ-CORE-065_create_table_with_unique",
			setup:   []string{"CREATE TABLE dd5(a INTEGER UNIQUE)", "INSERT INTO dd5 VALUES(1)"},
			exec:    "INSERT INTO dd5 VALUES(1)",
			wantErr: true,
			errLike: "UNIQUE constraint",
		},
		{
			name:    "REQ-CORE-066_create_table_check_constraint",
			setup:   []string{"CREATE TABLE dd6(a INTEGER CHECK(a > 0))"},
			exec:    "INSERT INTO dd6 VALUES(-1)",
			wantErr: true,
			errLike: "CHECK constraint",
		},
		{
			name:    "REQ-CORE-067_create_table_primary_key_text",
			setup:   []string{"CREATE TABLE dd7(k TEXT PRIMARY KEY, v INTEGER)", "INSERT INTO dd7 VALUES('abc',1)"},
			exec:    "INSERT INTO dd7 VALUES('abc',2)",
			wantErr: true,
			errLike: "UNIQUE constraint",
		},
	}
}
