// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import (
	"fmt"
	"testing"
)

// TestTrinity_Compound exercises UNION, UNION ALL, INTERSECT, EXCEPT,
// with ORDER BY/LIMIT, and nested compound queries.
func TestTrinity_Compound(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityCompoundTests())
}

func buildTrinityCompoundTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genCompoundUnionTests()...)
	tests = append(tests, genCompoundIntersectExceptTests()...)
	tests = append(tests, genCompoundOrderLimitTests()...)
	tests = append(tests, genCompoundNestedTests()...)
	return tests
}

var compoundSetup = []string{
	"CREATE TABLE t1(id INTEGER PRIMARY KEY, val TEXT)",
	"INSERT INTO t1 VALUES(1, 'a')", "INSERT INTO t1 VALUES(2, 'b')", "INSERT INTO t1 VALUES(3, 'c')",
	"CREATE TABLE t2(id INTEGER PRIMARY KEY, val TEXT)",
	"INSERT INTO t2 VALUES(2, 'b')", "INSERT INTO t2 VALUES(3, 'c')", "INSERT INTO t2 VALUES(4, 'd')",
}

func genCompoundUnionTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-CMP-001_union_dedup",
			setup: compoundSetup,
			query: "SELECT val FROM t1 UNION SELECT val FROM t2 ORDER BY val",
			wantRows: [][]interface{}{
				{"a"}, {"b"}, {"c"}, {"d"},
			}},
		{name: "REQ-CMP-002_union_all_keeps_dups",
			setup:    compoundSetup,
			query:    "SELECT val FROM t1 UNION ALL SELECT val FROM t2 ORDER BY val",
			wantRows: [][]interface{}{{"a"}, {"b"}, {"b"}, {"c"}, {"c"}, {"d"}}},
		{name: "REQ-CMP-003_union_different_types",
			query:    "SELECT 1 AS v UNION SELECT 'hello' ORDER BY v",
			wantRows: [][]interface{}{{int64(1)}, {"hello"}}},
		{name: "REQ-CMP-004_union_empty_left",
			setup: []string{
				"CREATE TABLE t1(v TEXT)", "CREATE TABLE t2(v TEXT)",
				"INSERT INTO t2 VALUES('x')",
			},
			query:    "SELECT v FROM t1 UNION SELECT v FROM t2",
			wantRows: [][]interface{}{{"x"}}},
		{name: "REQ-CMP-005_union_empty_right",
			setup: []string{
				"CREATE TABLE t1(v TEXT)", "CREATE TABLE t2(v TEXT)",
				"INSERT INTO t1 VALUES('x')",
			},
			query:    "SELECT v FROM t1 UNION SELECT v FROM t2",
			wantRows: [][]interface{}{{"x"}}},
		{name: "REQ-CMP-006_union_both_empty",
			setup: []string{
				"CREATE TABLE t1(v TEXT)", "CREATE TABLE t2(v TEXT)",
			},
			query:    "SELECT v FROM t1 UNION SELECT v FROM t2",
			wantRows: [][]interface{}{}},
		{name: "REQ-CMP-007_union_all_count",
			setup:    compoundSetup,
			query:    "SELECT COUNT(*) FROM (SELECT val FROM t1 UNION ALL SELECT val FROM t2)",
			wantRows: [][]interface{}{{int64(6)}}},
		{name: "REQ-CMP-008_union_with_null",
			setup: []string{
				"CREATE TABLE t1(v TEXT)", "INSERT INTO t1 VALUES(NULL)", "INSERT INTO t1 VALUES('a')",
				"CREATE TABLE t2(v TEXT)", "INSERT INTO t2 VALUES(NULL)", "INSERT INTO t2 VALUES('b')",
			},
			query:    "SELECT v FROM t1 UNION SELECT v FROM t2 ORDER BY v",
			wantRows: [][]interface{}{{nil}, {"a"}, {"b"}}},
	}
}

func genCompoundIntersectExceptTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-CMP-010_intersect_basic",
			setup: compoundSetup,
			query: "SELECT val FROM t1 INTERSECT SELECT val FROM t2 ORDER BY val",
			wantRows: [][]interface{}{
				{"b"}, {"c"},
			}},
		{name: "REQ-CMP-011_intersect_no_overlap",
			setup: []string{
				"CREATE TABLE t1(v INTEGER)", "INSERT INTO t1 VALUES(1)",
				"CREATE TABLE t2(v INTEGER)", "INSERT INTO t2 VALUES(2)",
			},
			query:    "SELECT v FROM t1 INTERSECT SELECT v FROM t2",
			wantRows: [][]interface{}{}},
		{name: "REQ-CMP-012_intersect_identical",
			setup: []string{
				"CREATE TABLE t1(v TEXT)", "INSERT INTO t1 VALUES('x')",
				"CREATE TABLE t2(v TEXT)", "INSERT INTO t2 VALUES('x')",
			},
			query:    "SELECT v FROM t1 INTERSECT SELECT v FROM t2",
			wantRows: [][]interface{}{{"x"}}},
		{name: "REQ-CMP-013_except_basic",
			setup:    compoundSetup,
			query:    "SELECT val FROM t1 EXCEPT SELECT val FROM t2 ORDER BY val",
			wantRows: [][]interface{}{{"a"}}},
		{name: "REQ-CMP-014_except_reverse",
			setup:    compoundSetup,
			query:    "SELECT val FROM t2 EXCEPT SELECT val FROM t1 ORDER BY val",
			wantRows: [][]interface{}{{"d"}}},
		{name: "REQ-CMP-015_except_all_removed",
			setup: []string{
				"CREATE TABLE t1(v TEXT)", "INSERT INTO t1 VALUES('a')",
				"CREATE TABLE t2(v TEXT)", "INSERT INTO t2 VALUES('a')",
			},
			query:    "SELECT v FROM t1 EXCEPT SELECT v FROM t2",
			wantRows: [][]interface{}{}},
		{name: "REQ-CMP-016_except_with_null",
			setup: []string{
				"CREATE TABLE t1(v TEXT)", "INSERT INTO t1 VALUES(NULL)", "INSERT INTO t1 VALUES('a')",
				"CREATE TABLE t2(v TEXT)", "INSERT INTO t2 VALUES('a')",
			},
			query:    "SELECT v FROM t1 EXCEPT SELECT v FROM t2",
			wantRows: [][]interface{}{{nil}}},
	}
}

func genCompoundOrderLimitTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-CMP-020_union_order_by",
			setup: compoundSetup,
			query: "SELECT val FROM t1 UNION SELECT val FROM t2 ORDER BY val DESC",
			wantRows: [][]interface{}{
				{"d"}, {"c"}, {"b"}, {"a"},
			}},
		{name: "REQ-CMP-021_union_limit",
			setup:    compoundSetup,
			query:    "SELECT val FROM t1 UNION SELECT val FROM t2 ORDER BY val LIMIT 2",
			wantRows: [][]interface{}{{"a"}, {"b"}}},
		{name: "REQ-CMP-022_union_limit_offset",
			setup:    compoundSetup,
			query:    "SELECT val FROM t1 UNION SELECT val FROM t2 ORDER BY val LIMIT 2 OFFSET 1",
			wantRows: [][]interface{}{{"b"}, {"c"}}},
		{name: "REQ-CMP-023_union_all_limit",
			setup:    compoundSetup,
			query:    "SELECT val FROM t1 UNION ALL SELECT val FROM t2 ORDER BY val LIMIT 3",
			wantRows: [][]interface{}{{"a"}, {"b"}, {"b"}}},
		{name: "REQ-CMP-024_intersect_order",
			setup:    compoundSetup,
			query:    "SELECT val FROM t1 INTERSECT SELECT val FROM t2 ORDER BY val DESC",
			wantRows: [][]interface{}{{"c"}, {"b"}}},
		{name: "REQ-CMP-025_except_limit",
			setup:    compoundSetup,
			query:    "SELECT id FROM t1 EXCEPT SELECT id FROM t2 ORDER BY id LIMIT 1",
			wantRows: [][]interface{}{{int64(1)}}},
	}
}

func genCompoundNestedTests() []sqlTestCase {
	nestedSetup := []string{
		"CREATE TABLE t1(v INTEGER)", "INSERT INTO t1 VALUES(1)", "INSERT INTO t1 VALUES(2)", "INSERT INTO t1 VALUES(3)",
		"CREATE TABLE t2(v INTEGER)", "INSERT INTO t2 VALUES(2)", "INSERT INTO t2 VALUES(3)", "INSERT INTO t2 VALUES(4)",
		"CREATE TABLE t3(v INTEGER)", "INSERT INTO t3 VALUES(3)", "INSERT INTO t3 VALUES(4)", "INSERT INTO t3 VALUES(5)",
	}
	return []sqlTestCase{
		{name: "REQ-CMP-030_nested_union_intersect",
			setup:    nestedSetup,
			query:    "SELECT v FROM t1 UNION SELECT v FROM t2 INTERSECT SELECT v FROM t3 ORDER BY v",
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}, {int64(3)}, {int64(4)}}},
		{name: "REQ-CMP-031_nested_intersect_first",
			setup:    nestedSetup,
			query:    "SELECT v FROM (SELECT v FROM t1 INTERSECT SELECT v FROM t2) UNION SELECT v FROM t3 ORDER BY v",
			wantRows: [][]interface{}{{int64(2)}, {int64(3)}, {int64(4)}, {int64(5)}}},
		{name: "REQ-CMP-032_nested_except_union",
			setup:    nestedSetup,
			query:    "SELECT v FROM (SELECT v FROM t1 EXCEPT SELECT v FROM t2) UNION ALL SELECT v FROM t3 ORDER BY v",
			wantRows: [][]interface{}{{int64(1)}, {int64(3)}, {int64(4)}, {int64(5)}}},
		{name: "REQ-CMP-033_triple_union",
			setup:    nestedSetup,
			query:    "SELECT v FROM t1 UNION SELECT v FROM t2 UNION SELECT v FROM t3 ORDER BY v",
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}, {int64(3)}, {int64(4)}, {int64(5)}}},
	}
}

// Compile-time assertion that sub-generators are used.
var _ = fmt.Sprintf
