// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import "testing"

// TestTrinity_Types validates type affinity, TYPEOF, and CAST per DO-178C trace.
func TestTrinity_Types(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityTypesTests())
}

func buildTrinityTypesTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genTypeAffinityMatrixTests()...)
	tests = append(tests, genTypeofTests()...)
	tests = append(tests, genTypeCastTests()...)
	tests = append(tests, genImplicitCoercionTests()...)
	return tests
}

// ---------------------------------------------------------------------------
// Type affinity 5x5 matrix: store {INTEGER,REAL,TEXT,BLOB,NULL} into
// columns declared as {INT,TEXT,REAL,BLOB,NUMERIC}.
// ---------------------------------------------------------------------------

func genTypeAffinityMatrixTests() []sqlTestCase {
	return append(
		genAffinityMatrixINTandTEXT(),
		genAffinityMatrixREALBLOBNUMERIC()...,
	)
}

func genAffinityMatrixINTandTEXT() []sqlTestCase {
	return []sqlTestCase{
		// INT column
		{
			name:     "REQ-TYPE-001_int_col_store_integer",
			setup:    []string{"CREATE TABLE ta01(v INT)", "INSERT INTO ta01 VALUES(42)"},
			query:    "SELECT TYPEOF(v), v FROM ta01",
			wantRows: [][]interface{}{{"integer", int64(42)}},
		},
		{
			name:     "REQ-TYPE-002_int_col_store_real",
			setup:    []string{"CREATE TABLE ta02(v INT)", "INSERT INTO ta02 VALUES(3.14)"},
			query:    "SELECT TYPEOF(v), v FROM ta02",
			wantRows: [][]interface{}{{"real", 3.14}},
		},
		{
			name:     "REQ-TYPE-003_int_col_store_text_numeric",
			setup:    []string{"CREATE TABLE ta03(v INT)", "INSERT INTO ta03 VALUES('100')"},
			query:    "SELECT TYPEOF(v), v FROM ta03",
			wantRows: [][]interface{}{{"integer", int64(100)}},
		},
		{
			name: "REQ-TYPE-004_int_col_store_blob",
			setup:    []string{"CREATE TABLE ta04(v INT)", "INSERT INTO ta04 VALUES(X'CAFE')"},
			query:    "SELECT TYPEOF(v) FROM ta04",
			wantRows: [][]interface{}{{"blob"}},
		},
		{
			name:     "REQ-TYPE-005_int_col_store_null",
			setup:    []string{"CREATE TABLE ta05(v INT)", "INSERT INTO ta05 VALUES(NULL)"},
			query:    "SELECT TYPEOF(v), v FROM ta05",
			wantRows: [][]interface{}{{"null", nil}},
		},
		// TEXT column
		{
			name:     "REQ-TYPE-006_text_col_store_integer",
			setup:    []string{"CREATE TABLE ta06(v TEXT)", "INSERT INTO ta06 VALUES(42)"},
			query:    "SELECT TYPEOF(v), v FROM ta06",
			wantRows: [][]interface{}{{"text", "42"}},
		},
		{
			name:     "REQ-TYPE-007_text_col_store_real",
			setup:    []string{"CREATE TABLE ta07(v TEXT)", "INSERT INTO ta07 VALUES(3.14)"},
			query:    "SELECT TYPEOF(v), v FROM ta07",
			wantRows: [][]interface{}{{"text", "3.14"}},
		},
		{
			name:     "REQ-TYPE-008_text_col_store_text",
			setup:    []string{"CREATE TABLE ta08(v TEXT)", "INSERT INTO ta08 VALUES('hello')"},
			query:    "SELECT TYPEOF(v), v FROM ta08",
			wantRows: [][]interface{}{{"text", "hello"}},
		},
		{
			name: "REQ-TYPE-009_text_col_store_blob",
			setup:    []string{"CREATE TABLE ta09(v TEXT)", "INSERT INTO ta09 VALUES(X'CAFE')"},
			query:    "SELECT TYPEOF(v) FROM ta09",
			wantRows: [][]interface{}{{"blob"}},
		},
		{
			name:     "REQ-TYPE-010_text_col_store_null",
			setup:    []string{"CREATE TABLE ta10(v TEXT)", "INSERT INTO ta10 VALUES(NULL)"},
			query:    "SELECT TYPEOF(v), v FROM ta10",
			wantRows: [][]interface{}{{"null", nil}},
		},
	}
}

func genAffinityMatrixREALBLOBNUMERIC() []sqlTestCase {
	return []sqlTestCase{
		// REAL column
		{
			name:     "REQ-TYPE-011_real_col_store_integer",
			setup:    []string{"CREATE TABLE ta11(v REAL)", "INSERT INTO ta11 VALUES(42)"},
			query:    "SELECT TYPEOF(v), v FROM ta11",
			wantRows: [][]interface{}{{"real", 42.0}},
		},
		{
			name:     "REQ-TYPE-012_real_col_store_real",
			setup:    []string{"CREATE TABLE ta12(v REAL)", "INSERT INTO ta12 VALUES(2.718)"},
			query:    "SELECT TYPEOF(v), v FROM ta12",
			wantRows: [][]interface{}{{"real", 2.718}},
		},
		{
			name:     "REQ-TYPE-013_real_col_store_text_numeric",
			setup:    []string{"CREATE TABLE ta13(v REAL)", "INSERT INTO ta13 VALUES('9.5')"},
			query:    "SELECT TYPEOF(v), v FROM ta13",
			wantRows: [][]interface{}{{"real", 9.5}},
		},
		{
			name: "REQ-TYPE-014_real_col_store_blob",
			setup:    []string{"CREATE TABLE ta14(v REAL)", "INSERT INTO ta14 VALUES(X'BEEF')"},
			query:    "SELECT TYPEOF(v) FROM ta14",
			wantRows: [][]interface{}{{"blob"}},
		},
		{
			name:     "REQ-TYPE-015_real_col_store_null",
			setup:    []string{"CREATE TABLE ta15(v REAL)", "INSERT INTO ta15 VALUES(NULL)"},
			query:    "SELECT TYPEOF(v), v FROM ta15",
			wantRows: [][]interface{}{{"null", nil}},
		},
		// BLOB column
		{
			name:     "REQ-TYPE-016_blob_col_store_integer",
			setup:    []string{"CREATE TABLE ta16(v BLOB)", "INSERT INTO ta16 VALUES(42)"},
			query:    "SELECT TYPEOF(v), v FROM ta16",
			wantRows: [][]interface{}{{"integer", int64(42)}},
		},
		{
			name:     "REQ-TYPE-017_blob_col_store_real",
			setup:    []string{"CREATE TABLE ta17(v BLOB)", "INSERT INTO ta17 VALUES(1.5)"},
			query:    "SELECT TYPEOF(v), v FROM ta17",
			wantRows: [][]interface{}{{"real", 1.5}},
		},
		{
			name:     "REQ-TYPE-018_blob_col_store_text",
			setup:    []string{"CREATE TABLE ta18(v BLOB)", "INSERT INTO ta18 VALUES('abc')"},
			query:    "SELECT TYPEOF(v), v FROM ta18",
			wantRows: [][]interface{}{{"text", "abc"}},
		},
		{
			name: "REQ-TYPE-019_blob_col_store_blob",
			setup:    []string{"CREATE TABLE ta19(v BLOB)", "INSERT INTO ta19 VALUES(X'DEAD')"},
			query:    "SELECT TYPEOF(v) FROM ta19",
			wantRows: [][]interface{}{{"blob"}},
		},
		{
			name:     "REQ-TYPE-020_blob_col_store_null",
			setup:    []string{"CREATE TABLE ta20(v BLOB)", "INSERT INTO ta20 VALUES(NULL)"},
			query:    "SELECT TYPEOF(v), v FROM ta20",
			wantRows: [][]interface{}{{"null", nil}},
		},
		// NUMERIC column
		{
			name:     "REQ-TYPE-021_numeric_col_store_integer",
			setup:    []string{"CREATE TABLE ta21(v NUMERIC)", "INSERT INTO ta21 VALUES(42)"},
			query:    "SELECT TYPEOF(v), v FROM ta21",
			wantRows: [][]interface{}{{"integer", int64(42)}},
		},
		{
			name:     "REQ-TYPE-022_numeric_col_store_real",
			setup:    []string{"CREATE TABLE ta22(v NUMERIC)", "INSERT INTO ta22 VALUES(3.14)"},
			query:    "SELECT TYPEOF(v), v FROM ta22",
			wantRows: [][]interface{}{{"real", 3.14}},
		},
		{
			name:     "REQ-TYPE-023_numeric_col_store_text_int",
			setup:    []string{"CREATE TABLE ta23(v NUMERIC)", "INSERT INTO ta23 VALUES('100')"},
			query:    "SELECT TYPEOF(v), v FROM ta23",
			wantRows: [][]interface{}{{"integer", int64(100)}},
		},
		{
			name: "REQ-TYPE-024_numeric_col_store_blob",
			setup:    []string{"CREATE TABLE ta24(v NUMERIC)", "INSERT INTO ta24 VALUES(X'FF')"},
			query:    "SELECT TYPEOF(v) FROM ta24",
			wantRows: [][]interface{}{{"blob"}},
		},
		{
			name:     "REQ-TYPE-025_numeric_col_store_null",
			setup:    []string{"CREATE TABLE ta25(v NUMERIC)", "INSERT INTO ta25 VALUES(NULL)"},
			query:    "SELECT TYPEOF(v), v FROM ta25",
			wantRows: [][]interface{}{{"null", nil}},
		},
	}
}

// ---------------------------------------------------------------------------
// TYPEOF() function
// ---------------------------------------------------------------------------

func genTypeofTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-TYPE-030_typeof_integer",
			query:    "SELECT TYPEOF(42)",
			wantRows: [][]interface{}{{"integer"}},
		},
		{
			name:     "REQ-TYPE-031_typeof_real",
			query:    "SELECT TYPEOF(3.14)",
			wantRows: [][]interface{}{{"real"}},
		},
		{
			name:     "REQ-TYPE-032_typeof_text",
			query:    "SELECT TYPEOF('hello')",
			wantRows: [][]interface{}{{"text"}},
		},
		{
			name:     "REQ-TYPE-033_typeof_blob",
			query:    "SELECT TYPEOF(X'AB')",
			wantRows: [][]interface{}{{"blob"}},
		},
		{
			name:     "REQ-TYPE-034_typeof_null",
			query:    "SELECT TYPEOF(NULL)",
			wantRows: [][]interface{}{{"null"}},
		},
		{
			name:     "REQ-TYPE-035_typeof_true",
			query:    "SELECT TYPEOF(TRUE)",
			wantRows: [][]interface{}{{"integer"}},
		},
		{
			name:     "REQ-TYPE-036_typeof_false",
			query:    "SELECT TYPEOF(FALSE)",
			wantRows: [][]interface{}{{"integer"}},
		},
		{
			name:     "REQ-TYPE-037_typeof_negative",
			query:    "SELECT TYPEOF(-1)",
			wantRows: [][]interface{}{{"integer"}},
		},
		{
			name:     "REQ-TYPE-038_typeof_zero_real",
			query:    "SELECT TYPEOF(0.0)",
			wantRows: [][]interface{}{{"real"}},
		},
	}
}

// ---------------------------------------------------------------------------
// CAST expressions
// ---------------------------------------------------------------------------

func genTypeCastTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-TYPE-040_cast_text_to_int",
			query:    "SELECT CAST('123' AS INTEGER)",
			wantRows: [][]interface{}{{int64(123)}},
		},
		{
			name:     "REQ-TYPE-041_cast_real_to_int",
			query:    "SELECT CAST(3.9 AS INTEGER)",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-TYPE-042_cast_int_to_real",
			query:    "SELECT TYPEOF(CAST(42 AS REAL)), CAST(42 AS REAL)",
			wantRows: [][]interface{}{{"real", 42.0}},
		},
		{
			name:     "REQ-TYPE-043_cast_int_to_text",
			query:    "SELECT TYPEOF(CAST(42 AS TEXT)), CAST(42 AS TEXT)",
			wantRows: [][]interface{}{{"text", "42"}},
		},
		{
			name:     "REQ-TYPE-044_cast_real_to_text",
			query:    "SELECT TYPEOF(CAST(3.14 AS TEXT)), CAST(3.14 AS TEXT)",
			wantRows: [][]interface{}{{"text", "3.14"}},
		},
		{
			name:     "REQ-TYPE-045_cast_null_to_int",
			query:    "SELECT CAST(NULL AS INTEGER)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-TYPE-046_cast_null_to_text",
			query:    "SELECT CAST(NULL AS TEXT)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-TYPE-047_cast_text_nonnumeric_to_int",
			query:    "SELECT CAST('abc' AS INTEGER)",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-TYPE-048_cast_blob_to_text",
			query:    "SELECT TYPEOF(CAST(X'68656C6C6F' AS TEXT))",
			wantRows: [][]interface{}{{"text"}},
		},
	}
}

// ---------------------------------------------------------------------------
// Implicit coercion
// ---------------------------------------------------------------------------

func genImplicitCoercionTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-TYPE-050_coerce_text_int_add",
			query:    "SELECT '10' + 5",
			wantRows: [][]interface{}{{int64(15)}},
		},
		{
			name:     "REQ-TYPE-051_coerce_text_real_add",
			query:    "SELECT '2.5' + 1",
			wantRows: [][]interface{}{{3.5}},
		},
		{
			name:     "REQ-TYPE-052_coerce_nonnumeric_text_add",
			query:    "SELECT 'abc' + 1",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-TYPE-053_coerce_int_concat",
			query:    "SELECT 42 || ' things'",
			wantRows: [][]interface{}{{"42 things"}},
		},
		{
			name:     "REQ-TYPE-054_coerce_bool_arithmetic",
			query:    "SELECT TRUE + TRUE",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name:     "REQ-TYPE-055_coerce_text_compare_numeric",
			query:    "SELECT '9' > '10'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-TYPE-056_coerce_int_vs_text_compare",
			query:    "SELECT 9 > '10'",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-TYPE-057_coerce_real_int_equality",
			query:    "SELECT 1.0 = 1",
			wantRows: [][]interface{}{{int64(1)}},
		},
	}
}
