// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import (
	"fmt"
	"testing"
)

func TestTrinity_Func(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityFuncTests())
}

func buildTrinityFuncTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, buildStringFuncTests()...)
	tests = append(tests, buildMathFuncTests()...)
	tests = append(tests, buildTypeFuncTests()...)
	tests = append(tests, buildDateTimeFuncTests()...)
	tests = append(tests, buildAggregateFuncTests()...)
	return tests
}

// ---------------------------------------------------------------------------
// String functions
// ---------------------------------------------------------------------------

func buildStringFuncTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, buildLengthTests()...)
	tests = append(tests, buildUpperLowerTests()...)
	tests = append(tests, buildSubstrTests()...)
	tests = append(tests, buildTrimTests()...)
	tests = append(tests, buildReplaceInstrTests()...)
	tests = append(tests, buildHexQuoteTests()...)
	tests = append(tests, buildUnicodeCharTests()...)
	tests = append(tests, buildZeroblobTests()...)
	return tests
}

func buildLengthTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-001_length/ascii",
			query:    "SELECT length('hello')",
			wantRows: [][]interface{}{{int64(5)}},
		},
		{
			name:     "REQ-FUNC-001_length/empty",
			query:    "SELECT length('')",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-FUNC-001_length/null",
			query:    "SELECT length(NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-001_length/integer",
			query:    "SELECT length(12345)",
			wantRows: [][]interface{}{{int64(5)}},
		},
		{
			name:     "REQ-FUNC-001_length/blob",
			query:    "SELECT length(X'0102030405')",
			wantRows: [][]interface{}{{int64(5)}},
		},
	}
}

func buildUpperLowerTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-002_upper/basic",
			query:    "SELECT upper('hello')",
			wantRows: [][]interface{}{{"HELLO"}},
		},
		{
			name:     "REQ-FUNC-002_upper/mixed",
			query:    "SELECT upper('Hello World')",
			wantRows: [][]interface{}{{"HELLO WORLD"}},
		},
		{
			name:     "REQ-FUNC-002_upper/null",
			query:    "SELECT upper(NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-002_upper/numbers",
			query:    "SELECT upper('abc123')",
			wantRows: [][]interface{}{{"ABC123"}},
		},
		{
			name:     "REQ-FUNC-003_lower/basic",
			query:    "SELECT lower('HELLO')",
			wantRows: [][]interface{}{{"hello"}},
		},
		{
			name:     "REQ-FUNC-003_lower/mixed",
			query:    "SELECT lower('Hello World')",
			wantRows: [][]interface{}{{"hello world"}},
		},
		{
			name:     "REQ-FUNC-003_lower/null",
			query:    "SELECT lower(NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-003_lower/already_lower",
			query:    "SELECT lower('already')",
			wantRows: [][]interface{}{{"already"}},
		},
	}
}

func buildSubstrTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-004_substr/from_start",
			query:    "SELECT substr('hello world', 1, 5)",
			wantRows: [][]interface{}{{"hello"}},
		},
		{
			name:     "REQ-FUNC-004_substr/from_middle",
			query:    "SELECT substr('hello world', 7, 5)",
			wantRows: [][]interface{}{{"world"}},
		},
		{
			name:     "REQ-FUNC-004_substr/no_length",
			query:    "SELECT substr('hello world', 7)",
			wantRows: [][]interface{}{{"world"}},
		},
		{
			name:     "REQ-FUNC-004_substr/negative_start",
			query:    "SELECT substr('hello', -3)",
			wantRows: [][]interface{}{{"llo"}},
		},
		{
			name:     "REQ-FUNC-004_substr/null",
			query:    "SELECT substr(NULL, 1, 3)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-004_substr/zero_length",
			query:    "SELECT substr('hello', 1, 0)",
			wantRows: [][]interface{}{{""}},
		},
		{
			name:     "REQ-FUNC-004_substr/beyond_end",
			query:    "SELECT substr('hi', 1, 100)",
			wantRows: [][]interface{}{{"hi"}},
		},
	}
}

func buildTrimTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-005_trim/spaces",
			query:    "SELECT trim('  hello  ')",
			wantRows: [][]interface{}{{"hello"}},
		},
		{
			name:     "REQ-FUNC-005_trim/custom_chars",
			query:    "SELECT trim('xxhelloxx', 'x')",
			wantRows: [][]interface{}{{"hello"}},
		},
		{
			name:     "REQ-FUNC-005_trim/null",
			query:    "SELECT trim(NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-006_ltrim/spaces",
			query:    "SELECT ltrim('  hello  ')",
			wantRows: [][]interface{}{{"hello  "}},
		},
		{
			name:     "REQ-FUNC-006_ltrim/custom",
			query:    "SELECT ltrim('xxhello', 'x')",
			wantRows: [][]interface{}{{"hello"}},
		},
		{
			name:     "REQ-FUNC-006_ltrim/null",
			query:    "SELECT ltrim(NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-007_rtrim/spaces",
			query:    "SELECT rtrim('  hello  ')",
			wantRows: [][]interface{}{{"  hello"}},
		},
		{
			name:     "REQ-FUNC-007_rtrim/custom",
			query:    "SELECT rtrim('helloxx', 'x')",
			wantRows: [][]interface{}{{"hello"}},
		},
		{
			name:     "REQ-FUNC-007_rtrim/null",
			query:    "SELECT rtrim(NULL)",
			wantRows: [][]interface{}{{nil}},
		},
	}
}

func buildReplaceInstrTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-008_replace/basic",
			query:    "SELECT replace('hello world', 'world', 'there')",
			wantRows: [][]interface{}{{"hello there"}},
		},
		{
			name:     "REQ-FUNC-008_replace/multiple",
			query:    "SELECT replace('aaa', 'a', 'bb')",
			wantRows: [][]interface{}{{"bbbbbb"}},
		},
		{
			name:     "REQ-FUNC-008_replace/no_match",
			query:    "SELECT replace('hello', 'xyz', 'abc')",
			wantRows: [][]interface{}{{"hello"}},
		},
		{
			name:     "REQ-FUNC-008_replace/null",
			query:    "SELECT replace(NULL, 'a', 'b')",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-008_replace/remove",
			query:    "SELECT replace('hello world', ' ', '')",
			wantRows: [][]interface{}{{"helloworld"}},
		},
		{
			name:     "REQ-FUNC-009_instr/found",
			query:    "SELECT instr('hello world', 'world')",
			wantRows: [][]interface{}{{int64(7)}},
		},
		{
			name:     "REQ-FUNC-009_instr/first_char",
			query:    "SELECT instr('hello', 'h')",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-FUNC-009_instr/not_found",
			query:    "SELECT instr('hello', 'xyz')",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-FUNC-009_instr/null",
			query:    "SELECT instr(NULL, 'a')",
			wantRows: [][]interface{}{{nil}},
		},
	}
}

func buildHexQuoteTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-010_hex/integer",
			query:    "SELECT hex(255)",
			wantRows: [][]interface{}{{"323535"}},
		},
		{
			name:     "REQ-FUNC-010_hex/string",
			query:    "SELECT hex('ABC')",
			wantRows: [][]interface{}{{"414243"}},
		},
		{
			name:     "REQ-FUNC-010_hex/blob",
			query:    "SELECT hex(X'DEADBEEF')",
			wantRows: [][]interface{}{{"DEADBEEF"}},
		},
		{
			name:     "REQ-FUNC-010_hex/null",
			query:    "SELECT hex(NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-011_quote/integer",
			query:    "SELECT quote(42)",
			wantRows: [][]interface{}{{"42"}},
		},
		{
			name:     "REQ-FUNC-011_quote/string",
			query:    "SELECT quote('hello')",
			wantRows: [][]interface{}{{"'hello'"}},
		},
		{
			name:     "REQ-FUNC-011_quote/null",
			query:    "SELECT quote(NULL)",
			wantRows: [][]interface{}{{"NULL"}},
		},
		{
			name:     "REQ-FUNC-011_quote/string_with_quote",
			query:    "SELECT quote('it''s')",
			wantRows: [][]interface{}{{"'it''s'"}},
		},
		{
			name:     "REQ-FUNC-011_quote/real",
			query:    "SELECT quote(3.14)",
			wantRows: [][]interface{}{{"3.14"}},
		},
		{
			name:     "REQ-FUNC-011_quote/blob",
			query:    "SELECT quote(X'0102')",
			wantRows: [][]interface{}{{"X'0102'"}},
		},
	}
}

func buildUnicodeCharTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-012_unicode/ascii_A",
			query:    "SELECT unicode('A')",
			wantRows: [][]interface{}{{int64(65)}},
		},
		{
			name:     "REQ-FUNC-012_unicode/ascii_a",
			query:    "SELECT unicode('a')",
			wantRows: [][]interface{}{{int64(97)}},
		},
		{
			name:     "REQ-FUNC-012_unicode/space",
			query:    "SELECT unicode(' ')",
			wantRows: [][]interface{}{{int64(32)}},
		},
		{
			name:     "REQ-FUNC-012_unicode/null",
			query:    "SELECT unicode(NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-013_char/single",
			query:    "SELECT char(65)",
			wantRows: [][]interface{}{{"A"}},
		},
		{
			name:     "REQ-FUNC-013_char/multiple",
			query:    "SELECT char(72, 101, 108, 108, 111)",
			wantRows: [][]interface{}{{"Hello"}},
		},
		{
			name:     "REQ-FUNC-013_char/newline",
			query:    "SELECT char(10)",
			wantRows: [][]interface{}{{"\n"}},
		},
		{
			name:     "REQ-FUNC-013_char/null_code",
			query:    "SELECT char(0)",
			wantRows: [][]interface{}{{"\x00"}},
		},
	}
}

func buildZeroblobTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-014_zeroblob/length_check",
			query:    "SELECT length(zeroblob(10))",
			wantRows: [][]interface{}{{int64(10)}},
		},
		{
			name:     "REQ-FUNC-014_zeroblob/typeof",
			query:    "SELECT typeof(zeroblob(5))",
			wantRows: [][]interface{}{{"blob"}},
		},
		{
			name:     "REQ-FUNC-014_zeroblob/hex",
			query:    "SELECT hex(zeroblob(4))",
			wantRows: [][]interface{}{{"00000000"}},
		},
		{
			name:     "REQ-FUNC-014_zeroblob/zero_size",
			query:    "SELECT length(zeroblob(0))",
			wantRows: [][]interface{}{{int64(0)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Math functions
// ---------------------------------------------------------------------------

func buildMathFuncTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, buildAbsTests()...)
	tests = append(tests, buildMinMaxScalarTests()...)
	tests = append(tests, buildRoundTests()...)
	tests = append(tests, buildRandomTests()...)
	return tests
}

func buildAbsTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-020_abs/positive_int",
			query:    "SELECT abs(42)",
			wantRows: [][]interface{}{{int64(42)}},
		},
		{
			name:     "REQ-FUNC-020_abs/negative_int",
			query:    "SELECT abs(-42)",
			wantRows: [][]interface{}{{int64(42)}},
		},
		{
			name:     "REQ-FUNC-020_abs/zero",
			query:    "SELECT abs(0)",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-FUNC-020_abs/positive_float",
			query:    "SELECT abs(3.14)",
			wantRows: [][]interface{}{{float64(3.14)}},
		},
		{
			name:     "REQ-FUNC-020_abs/negative_float",
			query:    "SELECT abs(-3.14)",
			wantRows: [][]interface{}{{float64(3.14)}},
		},
		{
			name:     "REQ-FUNC-020_abs/null",
			query:    "SELECT abs(NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-020_abs/string_coerce",
			query:    "SELECT abs('-7')",
			wantRows: [][]interface{}{{int64(7)}},
		},
	}
}

func buildMinMaxScalarTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-021_max_scalar/ints",
			query:    "SELECT max(1, 5, 3)",
			wantRows: [][]interface{}{{int64(5)}},
		},
		{
			name:     "REQ-FUNC-021_max_scalar/floats",
			query:    "SELECT max(1.1, 5.5, 3.3)",
			wantRows: [][]interface{}{{float64(5.5)}},
		},
		{
			name:     "REQ-FUNC-021_max_scalar/with_null",
			query:    "SELECT max(1, NULL, 3)",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-FUNC-021_max_scalar/strings",
			query:    "SELECT max('apple', 'cherry', 'banana')",
			wantRows: [][]interface{}{{"cherry"}},
		},
		{
			name:     "REQ-FUNC-021_max_scalar/single",
			query:    "SELECT max(42)",
			wantRows: [][]interface{}{{int64(42)}},
		},
		{
			name:     "REQ-FUNC-022_min_scalar/ints",
			query:    "SELECT min(5, 1, 3)",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-FUNC-022_min_scalar/floats",
			query:    "SELECT min(5.5, 1.1, 3.3)",
			wantRows: [][]interface{}{{float64(1.1)}},
		},
		{
			name:     "REQ-FUNC-022_min_scalar/with_null",
			query:    "SELECT min(5, NULL, 1)",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-FUNC-022_min_scalar/strings",
			query:    "SELECT min('cherry', 'apple', 'banana')",
			wantRows: [][]interface{}{{"apple"}},
		},
	}
}

func buildRoundTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-023_round/default_digits",
			query:    "SELECT round(3.7)",
			wantRows: [][]interface{}{{float64(4.0)}},
		},
		{
			name:     "REQ-FUNC-023_round/two_digits",
			query:    "SELECT round(3.14159, 2)",
			wantRows: [][]interface{}{{float64(3.14)}},
		},
		{
			name:     "REQ-FUNC-023_round/zero_digits",
			query:    "SELECT round(3.5, 0)",
			wantRows: [][]interface{}{{float64(4.0)}},
		},
		{
			name:     "REQ-FUNC-023_round/negative",
			query:    "SELECT round(-3.7)",
			wantRows: [][]interface{}{{float64(-4.0)}},
		},
		{
			name:     "REQ-FUNC-023_round/null",
			query:    "SELECT round(NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-023_round/integer_input",
			query:    "SELECT round(42)",
			wantRows: [][]interface{}{{float64(42.0)}},
		},
	}
}

func buildRandomTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-024_random/returns_integer",
			query:    "SELECT typeof(random())",
			wantRows: [][]interface{}{{"integer"}},
		},
		{
			name:     "REQ-FUNC-024_random/not_null",
			query:    "SELECT random() IS NOT NULL",
			wantRows: [][]interface{}{{int64(1)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Type functions
// ---------------------------------------------------------------------------

func buildTypeFuncTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, buildTypeofTests()...)
	tests = append(tests, buildCoalesceIfnullTests()...)
	tests = append(tests, buildNullifIifTests()...)
	return tests
}

func buildTypeofTests() []sqlTestCase {
	type typeofCase struct {
		expr string
		want string
	}
	cases := []typeofCase{
		{"42", "integer"},
		{"3.14", "real"},
		{"'hello'", "text"},
		{"NULL", "null"},
		{"X'01'", "blob"},
		{"1 + 2", "integer"},
		{"1.0 + 2", "real"},
	}
	tests := make([]sqlTestCase, len(cases))
	for i, c := range cases {
		tests[i] = sqlTestCase{
			name:     fmt.Sprintf("REQ-FUNC-030_typeof/%s", c.expr),
			query:    fmt.Sprintf("SELECT typeof(%s)", c.expr),
			wantRows: [][]interface{}{{c.want}},
		}
	}
	return tests
}

func buildCoalesceIfnullTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-031_coalesce/first_non_null",
			query:    "SELECT coalesce(NULL, NULL, 3, 4)",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-FUNC-031_coalesce/first_arg",
			query:    "SELECT coalesce(1, 2, 3)",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-FUNC-031_coalesce/all_null",
			query:    "SELECT coalesce(NULL, NULL, NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-031_coalesce/string",
			query:    "SELECT coalesce(NULL, 'hello')",
			wantRows: [][]interface{}{{"hello"}},
		},
		{
			name:     "REQ-FUNC-032_ifnull/first_non_null",
			query:    "SELECT ifnull(NULL, 42)",
			wantRows: [][]interface{}{{int64(42)}},
		},
		{
			name:     "REQ-FUNC-032_ifnull/first_not_null",
			query:    "SELECT ifnull(1, 42)",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-FUNC-032_ifnull/both_null",
			query:    "SELECT ifnull(NULL, NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-032_ifnull/string",
			query:    "SELECT ifnull(NULL, 'default')",
			wantRows: [][]interface{}{{"default"}},
		},
	}
}

func buildNullifIifTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-033_nullif/equal",
			query:    "SELECT nullif(1, 1)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-033_nullif/not_equal",
			query:    "SELECT nullif(1, 2)",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-FUNC-033_nullif/strings_equal",
			query:    "SELECT nullif('a', 'a')",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-033_nullif/strings_not_equal",
			query:    "SELECT nullif('a', 'b')",
			wantRows: [][]interface{}{{"a"}},
		},
		{
			name:     "REQ-FUNC-033_nullif/null_first",
			query:    "SELECT nullif(NULL, 1)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-034_iif/true",
			query:    "SELECT iif(1, 'yes', 'no')",
			wantRows: [][]interface{}{{"yes"}},
		},
		{
			name:     "REQ-FUNC-034_iif/false",
			query:    "SELECT iif(0, 'yes', 'no')",
			wantRows: [][]interface{}{{"no"}},
		},
		{
			name:     "REQ-FUNC-034_iif/null_cond",
			query:    "SELECT iif(NULL, 'yes', 'no')",
			wantRows: [][]interface{}{{"no"}},
		},
		{
			name:     "REQ-FUNC-034_iif/expression",
			query:    "SELECT iif(5 > 3, 'bigger', 'smaller')",
			wantRows: [][]interface{}{{"bigger"}},
		},
		{
			name:     "REQ-FUNC-034_iif/numeric_result",
			query:    "SELECT iif(1, 100, 200)",
			wantRows: [][]interface{}{{int64(100)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Date/Time functions
// ---------------------------------------------------------------------------

func buildDateTimeFuncTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, buildDateFuncBasicTests()...)
	tests = append(tests, buildTimeFuncTests()...)
	tests = append(tests, buildDatetimeFuncTests()...)
	tests = append(tests, buildStrftimeTests()...)
	return tests
}

func buildDateFuncBasicTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-040_date/literal",
			query:    "SELECT date('2023-06-15')",
			wantRows: [][]interface{}{{"2023-06-15"}},
		},
		{
			name:     "REQ-FUNC-040_date/with_time",
			query:    "SELECT date('2023-06-15 14:30:00')",
			wantRows: [][]interface{}{{"2023-06-15"}},
		},
		{
			name:     "REQ-FUNC-040_date/add_days",
			query:    "SELECT date('2023-01-01', '+10 days')",
			wantRows: [][]interface{}{{"2023-01-11"}},
		},
		{
			name:     "REQ-FUNC-040_date/sub_months",
			query:    "SELECT date('2023-06-15', '-2 months')",
			wantRows: [][]interface{}{{"2023-04-15"}},
		},
		{
			name:     "REQ-FUNC-040_date/add_years",
			query:    "SELECT date('2023-06-15', '+1 year')",
			wantRows: [][]interface{}{{"2024-06-15"}},
		},
		{
			name:     "REQ-FUNC-040_date/start_of_month",
			query:    "SELECT date('2023-06-15', 'start of month')",
			wantRows: [][]interface{}{{"2023-06-01"}},
		},
		{
			name:     "REQ-FUNC-040_date/start_of_year",
			query:    "SELECT date('2023-06-15', 'start of year')",
			wantRows: [][]interface{}{{"2023-01-01"}},
		},
		{
			name:     "REQ-FUNC-040_date/null",
			query:    "SELECT date(NULL)",
			wantRows: [][]interface{}{{nil}},
		},
	}
}

func buildTimeFuncTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-041_time/literal",
			query:    "SELECT time('14:30:00')",
			wantRows: [][]interface{}{{"14:30:00"}},
		},
		{
			name:     "REQ-FUNC-041_time/from_datetime",
			query:    "SELECT time('2023-06-15 14:30:45')",
			wantRows: [][]interface{}{{"14:30:45"}},
		},
		{
			name:     "REQ-FUNC-041_time/add_hours",
			query:    "SELECT time('14:30:00', '+2 hours')",
			wantRows: [][]interface{}{{"16:30:00"}},
		},
		{
			name:     "REQ-FUNC-041_time/add_minutes",
			query:    "SELECT time('14:30:00', '+45 minutes')",
			wantRows: [][]interface{}{{"15:15:00"}},
		},
		{
			name:     "REQ-FUNC-041_time/add_seconds",
			query:    "SELECT time('14:30:00', '+90 seconds')",
			wantRows: [][]interface{}{{"14:31:30"}},
		},
		{
			name:     "REQ-FUNC-041_time/null",
			query:    "SELECT time(NULL)",
			wantRows: [][]interface{}{{nil}},
		},
	}
}

func buildDatetimeFuncTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-042_datetime/literal",
			query:    "SELECT datetime('2023-06-15 14:30:00')",
			wantRows: [][]interface{}{{"2023-06-15 14:30:00"}},
		},
		{
			name:     "REQ-FUNC-042_datetime/from_date",
			query:    "SELECT datetime('2023-06-15')",
			wantRows: [][]interface{}{{"2023-06-15 00:00:00"}},
		},
		{
			name:     "REQ-FUNC-042_datetime/add_days_hours",
			query:    "SELECT datetime('2023-06-15 14:30:00', '+1 day', '+2 hours')",
			wantRows: [][]interface{}{{"2023-06-16 16:30:00"}},
		},
		{
			name:     "REQ-FUNC-042_datetime/null",
			query:    "SELECT datetime(NULL)",
			wantRows: [][]interface{}{{nil}},
		},
	}
}

func buildStrftimeTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-043_strftime/year",
			query:    "SELECT strftime('%Y', '2023-06-15')",
			wantRows: [][]interface{}{{"2023"}},
		},
		{
			name:     "REQ-FUNC-043_strftime/month",
			query:    "SELECT strftime('%m', '2023-06-15')",
			wantRows: [][]interface{}{{"06"}},
		},
		{
			name:     "REQ-FUNC-043_strftime/day",
			query:    "SELECT strftime('%d', '2023-06-15')",
			wantRows: [][]interface{}{{"15"}},
		},
		{
			name:     "REQ-FUNC-043_strftime/hour",
			query:    "SELECT strftime('%H', '2023-06-15 14:30:45')",
			wantRows: [][]interface{}{{"14"}},
		},
		{
			name:     "REQ-FUNC-043_strftime/minute",
			query:    "SELECT strftime('%M', '2023-06-15 14:30:45')",
			wantRows: [][]interface{}{{"30"}},
		},
		{
			name:     "REQ-FUNC-043_strftime/second",
			query:    "SELECT strftime('%S', '2023-06-15 14:30:45')",
			wantRows: [][]interface{}{{"45"}},
		},
		{
			name:     "REQ-FUNC-043_strftime/day_of_week",
			query:    "SELECT strftime('%w', '2023-06-15')",
			wantRows: [][]interface{}{{"4"}},
		},
		{
			name:     "REQ-FUNC-043_strftime/iso_day_of_week",
			query:    "SELECT strftime('%u', '2023-06-15')",
			wantRows: [][]interface{}{{"4"}},
		},
		{
			name:     "REQ-FUNC-043_strftime/week_of_year",
			query:    "SELECT strftime('%W', '2023-06-15')",
			wantRows: [][]interface{}{{"24"}},
		},
		{
			name:     "REQ-FUNC-043_strftime/day_of_year",
			query:    "SELECT strftime('%j', '2023-06-15')",
			wantRows: [][]interface{}{{"166"}},
		},
		{
			name:     "REQ-FUNC-043_strftime/full_format",
			query:    "SELECT strftime('%Y-%m-%d %H:%M:%S', '2023-06-15 14:30:45')",
			wantRows: [][]interface{}{{"2023-06-15 14:30:45"}},
		},
		{
			name:     "REQ-FUNC-043_strftime/null",
			query:    "SELECT strftime('%Y', NULL)",
			wantRows: [][]interface{}{{nil}},
		},
	}
}

// ---------------------------------------------------------------------------
// Aggregate functions
// ---------------------------------------------------------------------------

func buildAggregateFuncTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, buildCountTests()...)
	tests = append(tests, buildSumAvgTests()...)
	tests = append(tests, buildAggMinMaxTests()...)
	tests = append(tests, buildGroupConcatTests()...)
	tests = append(tests, buildTotalTests()...)
	return tests
}

func buildCountTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE t_agg(grp TEXT, val INTEGER, nval INTEGER)",
		"INSERT INTO t_agg VALUES('a', 10, NULL)",
		"INSERT INTO t_agg VALUES('a', 20, 1)",
		"INSERT INTO t_agg VALUES('a', 30, NULL)",
		"INSERT INTO t_agg VALUES('b', 40, 2)",
		"INSERT INTO t_agg VALUES('b', 50, 3)",
	}
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-050_count/star",
			setup:    setup,
			query:    "SELECT count(*) FROM t_agg",
			wantRows: [][]interface{}{{int64(5)}},
		},
		{
			name:     "REQ-FUNC-050_count/column",
			setup:    setup,
			query:    "SELECT count(nval) FROM t_agg",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-FUNC-050_count/empty_table",
			setup:    []string{"CREATE TABLE t_empty(x INTEGER)"},
			query:    "SELECT count(*) FROM t_empty",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-FUNC-050_count/group_by",
			setup:    setup,
			query:    "SELECT grp, count(*) FROM t_agg GROUP BY grp ORDER BY grp",
			wantRows: [][]interface{}{{"a", int64(3)}, {"b", int64(2)}},
		},
		{
			name:     "REQ-FUNC-050_count/distinct",
			setup:    []string{"CREATE TABLE t_cd(v INTEGER)", "INSERT INTO t_cd VALUES(1),(1),(2),(3),(3)"},
			query:    "SELECT count(DISTINCT v) FROM t_cd",
			wantRows: [][]interface{}{{int64(3)}},
		},
	}
}

func buildSumAvgTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE t_sa(grp TEXT, val INTEGER)",
		"INSERT INTO t_sa VALUES('a', 10)",
		"INSERT INTO t_sa VALUES('a', 20)",
		"INSERT INTO t_sa VALUES('a', 30)",
		"INSERT INTO t_sa VALUES('b', 40)",
		"INSERT INTO t_sa VALUES('b', 50)",
	}
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-051_sum/all",
			setup:    setup,
			query:    "SELECT sum(val) FROM t_sa",
			wantRows: [][]interface{}{{int64(150)}},
		},
		{
			name:     "REQ-FUNC-051_sum/group_by",
			setup:    setup,
			query:    "SELECT grp, sum(val) FROM t_sa GROUP BY grp ORDER BY grp",
			wantRows: [][]interface{}{{"a", int64(60)}, {"b", int64(90)}},
		},
		{
			name:     "REQ-FUNC-051_sum/empty",
			setup:    []string{"CREATE TABLE t_se(v INTEGER)"},
			query:    "SELECT sum(v) FROM t_se",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-051_sum/with_nulls",
			setup:    []string{"CREATE TABLE t_sn(v INTEGER)", "INSERT INTO t_sn VALUES(10),(NULL),(30)"},
			query:    "SELECT sum(v) FROM t_sn",
			wantRows: [][]interface{}{{int64(40)}},
		},
		{
			name:     "REQ-FUNC-052_avg/all",
			setup:    setup,
			query:    "SELECT avg(val) FROM t_sa",
			wantRows: [][]interface{}{{float64(30.0)}},
		},
		{
			name:     "REQ-FUNC-052_avg/group_by",
			setup:    setup,
			query:    "SELECT grp, avg(val) FROM t_sa GROUP BY grp ORDER BY grp",
			wantRows: [][]interface{}{{"a", float64(20.0)}, {"b", float64(45.0)}},
		},
		{
			name:     "REQ-FUNC-052_avg/empty",
			setup:    []string{"CREATE TABLE t_ae(v INTEGER)"},
			query:    "SELECT avg(v) FROM t_ae",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-052_avg/with_nulls",
			setup:    []string{"CREATE TABLE t_an(v INTEGER)", "INSERT INTO t_an VALUES(10),(NULL),(30)"},
			query:    "SELECT avg(v) FROM t_an",
			wantRows: [][]interface{}{{float64(20.0)}},
		},
	}
}

func buildAggMinMaxTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE t_mm(grp TEXT, val INTEGER)",
		"INSERT INTO t_mm VALUES('a', 10)",
		"INSERT INTO t_mm VALUES('a', 30)",
		"INSERT INTO t_mm VALUES('a', 20)",
		"INSERT INTO t_mm VALUES('b', 50)",
		"INSERT INTO t_mm VALUES('b', 40)",
	}
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-053_agg_min/all",
			setup:    setup,
			query:    "SELECT min(val) FROM t_mm",
			wantRows: [][]interface{}{{int64(10)}},
		},
		{
			name:     "REQ-FUNC-053_agg_min/group_by",
			setup:    setup,
			query:    "SELECT grp, min(val) FROM t_mm GROUP BY grp ORDER BY grp",
			wantRows: [][]interface{}{{"a", int64(10)}, {"b", int64(40)}},
		},
		{
			name:     "REQ-FUNC-053_agg_min/empty",
			setup:    []string{"CREATE TABLE t_me(v INTEGER)"},
			query:    "SELECT min(v) FROM t_me",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-054_agg_max/all",
			setup:    setup,
			query:    "SELECT max(val) FROM t_mm",
			wantRows: [][]interface{}{{int64(50)}},
		},
		{
			name:     "REQ-FUNC-054_agg_max/group_by",
			setup:    setup,
			query:    "SELECT grp, max(val) FROM t_mm GROUP BY grp ORDER BY grp",
			wantRows: [][]interface{}{{"a", int64(30)}, {"b", int64(50)}},
		},
		{
			name:     "REQ-FUNC-054_agg_max/empty",
			setup:    []string{"CREATE TABLE t_me2(v INTEGER)"},
			query:    "SELECT max(v) FROM t_me2",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-053_agg_min/strings",
			setup:    []string{"CREATE TABLE t_ms(v TEXT)", "INSERT INTO t_ms VALUES('cherry'),('apple'),('banana')"},
			query:    "SELECT min(v) FROM t_ms",
			wantRows: [][]interface{}{{"apple"}},
		},
		{
			name:     "REQ-FUNC-054_agg_max/strings",
			setup:    []string{"CREATE TABLE t_ms2(v TEXT)", "INSERT INTO t_ms2 VALUES('cherry'),('apple'),('banana')"},
			query:    "SELECT max(v) FROM t_ms2",
			wantRows: [][]interface{}{{"cherry"}},
		},
	}
}

func buildGroupConcatTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE t_gc(grp TEXT, val TEXT)",
		"INSERT INTO t_gc VALUES('a', 'x')",
		"INSERT INTO t_gc VALUES('a', 'y')",
		"INSERT INTO t_gc VALUES('a', 'z')",
		"INSERT INTO t_gc VALUES('b', 'p')",
		"INSERT INTO t_gc VALUES('b', 'q')",
	}
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-055_group_concat/default_sep",
			setup:    setup,
			query:    "SELECT group_concat(val) FROM t_gc WHERE grp='a'",
			wantRows: [][]interface{}{{"x,y,z"}},
		},
		{
			name:     "REQ-FUNC-055_group_concat/custom_sep",
			setup:    setup,
			query:    "SELECT group_concat(val, '; ') FROM t_gc WHERE grp='a'",
			wantRows: [][]interface{}{{"x; y; z"}},
		},
		{
			name:     "REQ-FUNC-055_group_concat/group_by",
			setup:    setup,
			query:    "SELECT grp, group_concat(val) FROM t_gc GROUP BY grp ORDER BY grp",
			wantRows: [][]interface{}{{"a", "x,y,z"}, {"b", "p,q"}},
		},
		{
			name:     "REQ-FUNC-055_group_concat/empty",
			setup:    []string{"CREATE TABLE t_gce(v TEXT)"},
			query:    "SELECT group_concat(v) FROM t_gce",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FUNC-055_group_concat/with_nulls",
			setup:    []string{"CREATE TABLE t_gcn(v TEXT)", "INSERT INTO t_gcn VALUES('a'),(NULL),('c')"},
			query:    "SELECT group_concat(v) FROM t_gcn",
			wantRows: [][]interface{}{{"a,c"}},
		},
		{
			name:     "REQ-FUNC-055_group_concat/integers",
			setup:    []string{"CREATE TABLE t_gci(v INTEGER)", "INSERT INTO t_gci VALUES(1),(2),(3)"},
			query:    "SELECT group_concat(v, '-') FROM t_gci",
			wantRows: [][]interface{}{{"1-2-3"}},
		},
	}
}

func buildTotalTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-FUNC-056_total/basic",
			setup:    []string{"CREATE TABLE t_tot(v INTEGER)", "INSERT INTO t_tot VALUES(10),(20),(30)"},
			query:    "SELECT total(v) FROM t_tot",
			wantRows: [][]interface{}{{float64(60.0)}},
		},
		{
			name:     "REQ-FUNC-056_total/empty_returns_zero",
			setup:    []string{"CREATE TABLE t_tote(v INTEGER)"},
			query:    "SELECT total(v) FROM t_tote",
			wantRows: [][]interface{}{{float64(0.0)}},
		},
		{
			name:     "REQ-FUNC-056_total/with_nulls",
			setup:    []string{"CREATE TABLE t_totn(v INTEGER)", "INSERT INTO t_totn VALUES(10),(NULL),(30)"},
			query:    "SELECT total(v) FROM t_totn",
			wantRows: [][]interface{}{{float64(40.0)}},
		},
		{
			name:     "REQ-FUNC-056_total/floats",
			setup:    []string{"CREATE TABLE t_totf(v REAL)", "INSERT INTO t_totf VALUES(1.5),(2.5),(3.0)"},
			query:    "SELECT total(v) FROM t_totf",
			wantRows: [][]interface{}{{float64(7.0)}},
		},
		{
			name: "REQ-FUNC-056_total/group_by",
			setup: []string{
				"CREATE TABLE t_totg(grp TEXT, v INTEGER)",
				"INSERT INTO t_totg VALUES('a',10),('a',20),('b',30),('b',40)",
			},
			query:    "SELECT grp, total(v) FROM t_totg GROUP BY grp ORDER BY grp",
			wantRows: [][]interface{}{{"a", float64(30.0)}, {"b", float64(70.0)}},
		},
	}
}
