// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity

package driver

import "testing"

// TestTrinity_Trigger validates trigger semantics per DO-178C trace.
func TestTrinity_Trigger(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityTriggerTests())
}

func buildTrinityTriggerTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genTriggerBeforeInsertTests()...)
	tests = append(tests, genTriggerAfterInsertTests()...)
	tests = append(tests, genTriggerBeforeUpdateTests()...)
	tests = append(tests, genTriggerAfterUpdateTests()...)
	tests = append(tests, genTriggerBeforeDeleteTests()...)
	tests = append(tests, genTriggerAfterDeleteTests()...)
	tests = append(tests, genTriggerWhenTests()...)
	tests = append(tests, genTriggerUpdateOfTests()...)
	tests = append(tests, genTriggerRaiseTests()...)
	tests = append(tests, genTriggerRefTests()...)
	tests = append(tests, genTriggerDropTests()...)
	tests = append(tests, genTriggerMultipleTests()...)
	tests = append(tests, genTriggerCascadingTests()...)
	return tests
}

// ---------------------------------------------------------------------------
// BEFORE INSERT
// ---------------------------------------------------------------------------

func genTriggerBeforeInsertTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE t1(a INTEGER, b TEXT)",
		"CREATE TABLE log(msg TEXT)",
		"CREATE TRIGGER trg_bi BEFORE INSERT ON t1 BEGIN INSERT INTO log VALUES('before_insert'); END",
	}
	return []sqlTestCase{
		{
			name:     "REQ-TRIG-001_before_insert_fires",
			setup:    append(setup, "INSERT INTO t1 VALUES(1,'x')"),
			query:    "SELECT msg FROM log",
			wantRows: [][]interface{}{{"before_insert"}},
		},
		{
			name:     "REQ-TRIG-002_before_insert_fires_per_row",
			setup:    append(setup, "INSERT INTO t1 VALUES(1,'a')", "INSERT INTO t1 VALUES(2,'b')"),
			query:    "SELECT COUNT(*) FROM log",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name:     "REQ-TRIG-003_before_insert_row_still_inserted",
			setup:    append(setup, "INSERT INTO t1 VALUES(1,'x')"),
			query:    "SELECT a, b FROM t1",
			wantRows: [][]interface{}{{int64(1), "x"}},
		},
	}
}

// ---------------------------------------------------------------------------
// AFTER INSERT
// ---------------------------------------------------------------------------

func genTriggerAfterInsertTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE t2(a INTEGER, b TEXT)",
		"CREATE TABLE log(msg TEXT)",
		"CREATE TRIGGER trg_ai AFTER INSERT ON t2 BEGIN INSERT INTO log VALUES('after_insert'); END",
	}
	return []sqlTestCase{
		{
			name:     "REQ-TRIG-005_after_insert_fires",
			setup:    append(setup, "INSERT INTO t2 VALUES(1,'x')"),
			query:    "SELECT msg FROM log",
			wantRows: [][]interface{}{{"after_insert"}},
		},
		{
			name:     "REQ-TRIG-006_after_insert_multiple",
			setup:    append(setup, "INSERT INTO t2 VALUES(1,'a')", "INSERT INTO t2 VALUES(2,'b')", "INSERT INTO t2 VALUES(3,'c')"),
			query:    "SELECT COUNT(*) FROM log",
			wantRows: [][]interface{}{{int64(3)}},
		},
	}
}

// ---------------------------------------------------------------------------
// BEFORE UPDATE
// ---------------------------------------------------------------------------

func genTriggerBeforeUpdateTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE t3(a INTEGER, b TEXT)",
		"CREATE TABLE log(msg TEXT)",
		"INSERT INTO t3 VALUES(1,'old')",
		"CREATE TRIGGER trg_bu BEFORE UPDATE ON t3 BEGIN INSERT INTO log VALUES('before_update'); END",
	}
	return []sqlTestCase{
		{
			name:     "REQ-TRIG-010_before_update_fires",
			setup:    append(setup, "UPDATE t3 SET b='new' WHERE a=1"),
			query:    "SELECT msg FROM log",
			wantRows: [][]interface{}{{"before_update"}},
		},
		{
			name:     "REQ-TRIG-011_before_update_per_row",
			setup:    []string{"CREATE TABLE t3b(a INTEGER, b TEXT)", "CREATE TABLE log(msg TEXT)", "INSERT INTO t3b VALUES(1,'x')", "INSERT INTO t3b VALUES(2,'y')", "CREATE TRIGGER trg_bu2 BEFORE UPDATE ON t3b BEGIN INSERT INTO log VALUES('bu'); END", "UPDATE t3b SET b='z'"},
			query:    "SELECT COUNT(*) FROM log",
			wantRows: [][]interface{}{{int64(2)}},
		},
	}
}

// ---------------------------------------------------------------------------
// AFTER UPDATE
// ---------------------------------------------------------------------------

func genTriggerAfterUpdateTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE t4(a INTEGER, b TEXT)",
		"CREATE TABLE log(msg TEXT)",
		"INSERT INTO t4 VALUES(1,'old')",
		"CREATE TRIGGER trg_au AFTER UPDATE ON t4 BEGIN INSERT INTO log VALUES('after_update'); END",
	}
	return []sqlTestCase{
		{
			name:     "REQ-TRIG-015_after_update_fires",
			setup:    append(setup, "UPDATE t4 SET b='new' WHERE a=1"),
			query:    "SELECT msg FROM log",
			wantRows: [][]interface{}{{"after_update"}},
		},
		{
			name:     "REQ-TRIG-016_after_update_no_match_no_fire",
			setup:    append(setup, "UPDATE t4 SET b='new' WHERE a=999"),
			query:    "SELECT COUNT(*) FROM log",
			wantRows: [][]interface{}{{int64(0)}},
		},
	}
}

// ---------------------------------------------------------------------------
// BEFORE DELETE
// ---------------------------------------------------------------------------

func genTriggerBeforeDeleteTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE t5(a INTEGER, b TEXT)",
		"CREATE TABLE log(msg TEXT)",
		"INSERT INTO t5 VALUES(1,'x')",
		"INSERT INTO t5 VALUES(2,'y')",
		"CREATE TRIGGER trg_bd BEFORE DELETE ON t5 BEGIN INSERT INTO log VALUES('before_delete'); END",
	}
	return []sqlTestCase{
		{
			name:     "REQ-TRIG-020_before_delete_fires",
			setup:    append(setup, "DELETE FROM t5 WHERE a=1"),
			query:    "SELECT msg FROM log",
			wantRows: [][]interface{}{{"before_delete"}},
		},
		{
			name:     "REQ-TRIG-021_before_delete_per_row",
			setup:    append(setup, "DELETE FROM t5"),
			query:    "SELECT COUNT(*) FROM log",
			wantRows: [][]interface{}{{int64(2)}},
		},
	}
}

// ---------------------------------------------------------------------------
// AFTER DELETE
// ---------------------------------------------------------------------------

func genTriggerAfterDeleteTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE t6(a INTEGER, b TEXT)",
		"CREATE TABLE log(msg TEXT)",
		"INSERT INTO t6 VALUES(1,'x')",
		"CREATE TRIGGER trg_ad AFTER DELETE ON t6 BEGIN INSERT INTO log VALUES('after_delete'); END",
	}
	return []sqlTestCase{
		{
			name:     "REQ-TRIG-025_after_delete_fires",
			setup:    append(setup, "DELETE FROM t6 WHERE a=1"),
			query:    "SELECT msg FROM log",
			wantRows: [][]interface{}{{"after_delete"}},
		},
		{
			name:     "REQ-TRIG-026_after_delete_no_match_no_fire",
			setup:    append(setup, "DELETE FROM t6 WHERE a=999"),
			query:    "SELECT COUNT(*) FROM log",
			wantRows: [][]interface{}{{int64(0)}},
		},
	}
}

// ---------------------------------------------------------------------------
// WHEN clause
// ---------------------------------------------------------------------------

func genTriggerWhenTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name: "REQ-TRIG-030_when_true_fires",
			setup: []string{
				"CREATE TABLE tw1(a INTEGER)",
				"CREATE TABLE log(msg TEXT)",
				"CREATE TRIGGER trg_when_t AFTER INSERT ON tw1 WHEN NEW.a > 5 BEGIN INSERT INTO log VALUES('gt5'); END",
				"INSERT INTO tw1 VALUES(10)",
			},
			query:    "SELECT msg FROM log",
			wantRows: [][]interface{}{{"gt5"}},
		},
		{
			name: "REQ-TRIG-031_when_false_no_fire",
			setup: []string{
				"CREATE TABLE tw2(a INTEGER)",
				"CREATE TABLE log(msg TEXT)",
				"CREATE TRIGGER trg_when_f AFTER INSERT ON tw2 WHEN NEW.a > 5 BEGIN INSERT INTO log VALUES('gt5'); END",
				"INSERT INTO tw2 VALUES(3)",
			},
			query:    "SELECT COUNT(*) FROM log",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name: "REQ-TRIG-032_when_mixed",
			setup: []string{
				"CREATE TABLE tw3(a INTEGER)",
				"CREATE TABLE log(msg TEXT)",
				"CREATE TRIGGER trg_when_m AFTER INSERT ON tw3 WHEN NEW.a > 5 BEGIN INSERT INTO log VALUES('gt5'); END",
				"INSERT INTO tw3 VALUES(3)",
				"INSERT INTO tw3 VALUES(10)",
				"INSERT INTO tw3 VALUES(1)",
			},
			query:    "SELECT COUNT(*) FROM log",
			wantRows: [][]interface{}{{int64(1)}},
		},
	}
}

// ---------------------------------------------------------------------------
// UPDATE OF column filter
// ---------------------------------------------------------------------------

func genTriggerUpdateOfTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE tuo(a INTEGER, b TEXT, c REAL)",
		"CREATE TABLE log(msg TEXT)",
		"INSERT INTO tuo VALUES(1,'old',1.0)",
		"CREATE TRIGGER trg_uo AFTER UPDATE OF b ON tuo BEGIN INSERT INTO log VALUES('b_changed'); END",
	}
	return []sqlTestCase{
		{
			name:     "REQ-TRIG-035_update_of_matching_column",
			setup:    append(setup, "UPDATE tuo SET b='new' WHERE a=1"),
			query:    "SELECT msg FROM log",
			wantRows: [][]interface{}{{"b_changed"}},
		},
		{
			name:     "REQ-TRIG-036_update_of_non_matching_column",
			setup:    append(setup, "UPDATE tuo SET c=2.0 WHERE a=1"),
			query:    "SELECT COUNT(*) FROM log",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-TRIG-037_update_of_both_columns",
			setup:    append(setup, "UPDATE tuo SET b='new', c=2.0 WHERE a=1"),
			query:    "SELECT msg FROM log",
			wantRows: [][]interface{}{{"b_changed"}},
		},
	}
}

// ---------------------------------------------------------------------------
// RAISE functions
// ---------------------------------------------------------------------------

func genTriggerRaiseTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name: "REQ-TRIG-040_raise_ignore",
			setup: []string{
				"CREATE TABLE tri1(a INTEGER)",
				"CREATE TABLE log(msg TEXT)",
				"CREATE TRIGGER trg_ign BEFORE INSERT ON tri1 BEGIN SELECT RAISE(IGNORE); END",
				"INSERT INTO tri1 VALUES(1)",
			},
			query:    "SELECT COUNT(*) FROM tri1",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name: "REQ-TRIG-041_raise_rollback",
			setup: []string{
				"CREATE TABLE tri2(a INTEGER)",
				"CREATE TRIGGER trg_rb BEFORE INSERT ON tri2 BEGIN SELECT RAISE(ROLLBACK, 'trigger_rollback'); END",
			},
			exec:    "INSERT INTO tri2 VALUES(1)",
			wantErr: true,
			errLike: "trigger_rollback",
		},
		{
			name: "REQ-TRIG-042_raise_abort",
			setup: []string{
				"CREATE TABLE tri3(a INTEGER)",
				"CREATE TRIGGER trg_ab BEFORE INSERT ON tri3 BEGIN SELECT RAISE(ABORT, 'trigger_abort'); END",
			},
			exec:    "INSERT INTO tri3 VALUES(1)",
			wantErr: true,
			errLike: "trigger_abort",
		},
		{
			name: "REQ-TRIG-043_raise_fail",
			setup: []string{
				"CREATE TABLE tri4(a INTEGER)",
				"CREATE TRIGGER trg_fl BEFORE INSERT ON tri4 BEGIN SELECT RAISE(FAIL, 'trigger_fail'); END",
			},
			exec:    "INSERT INTO tri4 VALUES(1)",
			wantErr: true,
			errLike: "trigger_fail",
		},
		{
			name: "REQ-TRIG-044_raise_rollback_preserves_prior",
			setup: []string{
				"CREATE TABLE tri5(a INTEGER)",
				"CREATE TRIGGER trg_rb5 BEFORE INSERT ON tri5 WHEN NEW.a > 5 BEGIN SELECT RAISE(ROLLBACK, 'too_big'); END",
				"INSERT INTO tri5 VALUES(1)",
				"INSERT INTO tri5 VALUES(2)",
			},
			exec:    "INSERT INTO tri5 VALUES(10)",
			wantErr: true,
			errLike: "too_big",
		},
		{
			name: "REQ-TRIG-045_raise_abort_table_unchanged",
			setup: []string{
				"CREATE TABLE tri6(a INTEGER)",
				"CREATE TRIGGER trg_ab6 BEFORE INSERT ON tri6 WHEN NEW.a < 0 BEGIN SELECT RAISE(ABORT, 'negative'); END",
				"INSERT INTO tri6 VALUES(1)",
			},
			exec:    "INSERT INTO tri6 VALUES(-1)",
			wantErr: true,
			errLike: "negative",
		},
	}
}

// ---------------------------------------------------------------------------
// NEW.col and OLD.col references
// ---------------------------------------------------------------------------

func genTriggerRefTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name: "REQ-TRIG-050_new_ref_insert",
			setup: []string{
				"CREATE TABLE tref1(a INTEGER, b TEXT)",
				"CREATE TABLE log(msg TEXT)",
				"CREATE TRIGGER trg_new AFTER INSERT ON tref1 BEGIN INSERT INTO log VALUES(NEW.b); END",
				"INSERT INTO tref1 VALUES(1,'hello')",
			},
			query:    "SELECT msg FROM log",
			wantRows: [][]interface{}{{"hello"}},
		},
		{
			name: "REQ-TRIG-051_old_ref_delete",
			setup: []string{
				"CREATE TABLE tref2(a INTEGER, b TEXT)",
				"CREATE TABLE log(msg TEXT)",
				"INSERT INTO tref2 VALUES(1,'goodbye')",
				"CREATE TRIGGER trg_old AFTER DELETE ON tref2 BEGIN INSERT INTO log VALUES(OLD.b); END",
				"DELETE FROM tref2 WHERE a=1",
			},
			query:    "SELECT msg FROM log",
			wantRows: [][]interface{}{{"goodbye"}},
		},
		{
			name: "REQ-TRIG-052_old_and_new_ref_update",
			setup: []string{
				"CREATE TABLE tref3(a INTEGER, b TEXT)",
				"CREATE TABLE log(msg TEXT)",
				"INSERT INTO tref3 VALUES(1,'old_val')",
				"CREATE TRIGGER trg_on AFTER UPDATE ON tref3 BEGIN INSERT INTO log VALUES(OLD.b || '->' || NEW.b); END",
				"UPDATE tref3 SET b='new_val' WHERE a=1",
			},
			query:    "SELECT msg FROM log",
			wantRows: [][]interface{}{{"old_val->new_val"}},
		},
		{
			name: "REQ-TRIG-053_new_ref_computed_value",
			setup: []string{
				"CREATE TABLE tref4(a INTEGER, b INTEGER)",
				"CREATE TABLE log(msg TEXT)",
				"CREATE TRIGGER trg_comp AFTER INSERT ON tref4 BEGIN INSERT INTO log VALUES(CAST(NEW.a + NEW.b AS TEXT)); END",
				"INSERT INTO tref4 VALUES(10, 20)",
			},
			query:    "SELECT msg FROM log",
			wantRows: [][]interface{}{{"30"}},
		},
	}
}

// ---------------------------------------------------------------------------
// DROP TRIGGER
// ---------------------------------------------------------------------------

func genTriggerDropTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name: "REQ-TRIG-060_drop_trigger",
			setup: []string{
				"CREATE TABLE td1(a INTEGER)",
				"CREATE TABLE log(msg TEXT)",
				"CREATE TRIGGER trg_drop AFTER INSERT ON td1 BEGIN INSERT INTO log VALUES('fired'); END",
				"DROP TRIGGER trg_drop",
				"INSERT INTO td1 VALUES(1)",
			},
			query:    "SELECT COUNT(*) FROM log",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name: "REQ-TRIG-061_drop_trigger_if_exists",
			setup: []string{
				"DROP TRIGGER IF EXISTS nonexistent_trigger",
			},
			query:    "SELECT 1",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:    "REQ-TRIG-062_drop_nonexistent_trigger_error",
			exec:    "DROP TRIGGER nonexistent_trigger",
			wantErr: true,
			errLike: "trigger not found",
		},
		{
			name: "REQ-TRIG-063_drop_trigger_schema_clean",
			setup: []string{
				"CREATE TABLE td2(a INTEGER)",
				"CREATE TRIGGER trg_clean AFTER INSERT ON td2 BEGIN SELECT 1; END",
				"DROP TRIGGER trg_clean",
			},
			query:    "SELECT COUNT(*) FROM sqlite_master WHERE type='trigger' AND name='trg_clean'",
			wantRows: [][]interface{}{{int64(0)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Multiple triggers on same table
// ---------------------------------------------------------------------------

func genTriggerMultipleTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name: "REQ-TRIG-070_multiple_triggers_same_event",
			setup: []string{
				"CREATE TABLE tm1(a INTEGER)",
				"CREATE TABLE log(msg TEXT)",
				"CREATE TRIGGER trg_m1 AFTER INSERT ON tm1 BEGIN INSERT INTO log VALUES('trigger1'); END",
				"CREATE TRIGGER trg_m2 AFTER INSERT ON tm1 BEGIN INSERT INTO log VALUES('trigger2'); END",
				"INSERT INTO tm1 VALUES(1)",
			},
			query:    "SELECT COUNT(*) FROM log",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name: "REQ-TRIG-071_before_and_after_on_same_table",
			setup: []string{
				"CREATE TABLE tm2(a INTEGER)",
				"CREATE TABLE log(msg TEXT)",
				"CREATE TRIGGER trg_b BEFORE INSERT ON tm2 BEGIN INSERT INTO log VALUES('before'); END",
				"CREATE TRIGGER trg_a AFTER INSERT ON tm2 BEGIN INSERT INTO log VALUES('after'); END",
				"INSERT INTO tm2 VALUES(1)",
			},
			query:    "SELECT COUNT(*) FROM log",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name: "REQ-TRIG-072_multiple_event_types",
			setup: []string{
				"CREATE TABLE tm3(a INTEGER, b TEXT)",
				"CREATE TABLE log(msg TEXT)",
				"CREATE TRIGGER trg_ins AFTER INSERT ON tm3 BEGIN INSERT INTO log VALUES('ins'); END",
				"CREATE TRIGGER trg_upd AFTER UPDATE ON tm3 BEGIN INSERT INTO log VALUES('upd'); END",
				"CREATE TRIGGER trg_del AFTER DELETE ON tm3 BEGIN INSERT INTO log VALUES('del'); END",
				"INSERT INTO tm3 VALUES(1,'x')",
				"UPDATE tm3 SET b='y' WHERE a=1",
				"DELETE FROM tm3 WHERE a=1",
			},
			query:    "SELECT COUNT(*) FROM log",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name: "REQ-TRIG-073_multiple_triggers_all_fire",
			setup: []string{
				"CREATE TABLE tm4(a INTEGER)",
				"CREATE TABLE log(msg TEXT)",
				"CREATE TRIGGER trg_t1 AFTER INSERT ON tm4 BEGIN INSERT INTO log VALUES('t1'); END",
				"CREATE TRIGGER trg_t2 AFTER INSERT ON tm4 BEGIN INSERT INTO log VALUES('t2'); END",
				"CREATE TRIGGER trg_t3 AFTER INSERT ON tm4 BEGIN INSERT INTO log VALUES('t3'); END",
				"INSERT INTO tm4 VALUES(1)",
			},
			query:    "SELECT COUNT(*) FROM log",
			wantRows: [][]interface{}{{int64(3)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Cascading triggers
// ---------------------------------------------------------------------------

func genTriggerCascadingTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name: "REQ-TRIG-080_cascading_trigger",
			setup: []string{
				"CREATE TABLE tc1(a INTEGER)",
				"CREATE TABLE tc2(b INTEGER)",
				"CREATE TABLE log(msg TEXT)",
				"CREATE TRIGGER trg_cas1 AFTER INSERT ON tc1 BEGIN INSERT INTO tc2 VALUES(NEW.a * 10); END",
				"CREATE TRIGGER trg_cas2 AFTER INSERT ON tc2 BEGIN INSERT INTO log VALUES('cascade_' || CAST(NEW.b AS TEXT)); END",
				"INSERT INTO tc1 VALUES(5)",
			},
			query:    "SELECT msg FROM log",
			wantRows: [][]interface{}{{"cascade_50"}},
		},
		{
			name: "REQ-TRIG-081_cascading_trigger_intermediate",
			setup: []string{
				"CREATE TABLE tc3(a INTEGER)",
				"CREATE TABLE tc4(b INTEGER)",
				"CREATE TABLE log(msg TEXT)",
				"CREATE TRIGGER trg_cas3 AFTER INSERT ON tc3 BEGIN INSERT INTO tc4 VALUES(NEW.a + 1); END",
				"CREATE TRIGGER trg_cas4 AFTER INSERT ON tc4 BEGIN INSERT INTO log VALUES(CAST(NEW.b AS TEXT)); END",
				"INSERT INTO tc3 VALUES(1)",
			},
			query:    "SELECT b FROM tc4",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name: "REQ-TRIG-082_cascading_multiple_rows",
			setup: []string{
				"CREATE TABLE tc5(a INTEGER)",
				"CREATE TABLE tc6(b INTEGER)",
				"CREATE TABLE log(msg TEXT)",
				"CREATE TRIGGER trg_cas5 AFTER INSERT ON tc5 BEGIN INSERT INTO tc6 VALUES(NEW.a); END",
				"CREATE TRIGGER trg_cas6 AFTER INSERT ON tc6 BEGIN INSERT INTO log VALUES('c'); END",
				"INSERT INTO tc5 VALUES(1)",
				"INSERT INTO tc5 VALUES(2)",
				"INSERT INTO tc5 VALUES(3)",
			},
			query:    "SELECT COUNT(*) FROM log",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name: "REQ-TRIG-083_cascade_delete_chain",
			setup: []string{
				"CREATE TABLE tc7(a INTEGER)",
				"CREATE TABLE tc8(b INTEGER)",
				"CREATE TABLE log(msg TEXT)",
				"INSERT INTO tc7 VALUES(1)",
				"INSERT INTO tc8 VALUES(10)",
				"CREATE TRIGGER trg_cas7 AFTER DELETE ON tc7 BEGIN DELETE FROM tc8; END",
				"CREATE TRIGGER trg_cas8 AFTER DELETE ON tc8 BEGIN INSERT INTO log VALUES('chain_del'); END",
				"DELETE FROM tc7 WHERE a=1",
			},
			query:    "SELECT msg FROM log",
			wantRows: [][]interface{}{{"chain_del"}},
		},
		{
			name: "REQ-TRIG-084_cascade_update_chain",
			setup: []string{
				"CREATE TABLE tc9(a INTEGER, b TEXT)",
				"CREATE TABLE tc10(c INTEGER, d TEXT)",
				"CREATE TABLE log(msg TEXT)",
				"INSERT INTO tc9 VALUES(1,'old')",
				"INSERT INTO tc10 VALUES(1,'old')",
				"CREATE TRIGGER trg_cas9 AFTER UPDATE ON tc9 BEGIN UPDATE tc10 SET d='new' WHERE c=1; END",
				"CREATE TRIGGER trg_cas10 AFTER UPDATE ON tc10 BEGIN INSERT INTO log VALUES('chain_upd'); END",
				"UPDATE tc9 SET b='new' WHERE a=1",
			},
			query:    "SELECT msg FROM log",
			wantRows: [][]interface{}{{"chain_upd"}},
		},
	}
}
