// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import (
	"fmt"
	"testing"
)

// TestTrinity_DDL exercises CREATE TABLE, ALTER TABLE, DROP TABLE,
// CREATE/DROP INDEX, CREATE/DROP VIEW, and REINDEX operations.
func TestTrinity_DDL(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityDDLTests())
}

func buildTrinityDDLTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genDDLCreateTableTests()...)
	tests = append(tests, genDDLConstraintTests()...)
	tests = append(tests, genDDLCompositePKTests()...)
	tests = append(tests, genDDLIfNotExistsTests()...)
	tests = append(tests, genDDLAlterTableTests()...)
	tests = append(tests, genDDLDropTableTests()...)
	tests = append(tests, genDDLIndexTests()...)
	tests = append(tests, genDDLViewTests()...)
	tests = append(tests, genDDLReindexTests()...)
	return tests
}

func genDDLCreateTableTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-DDL-001_create_basic_table",
			exec: "CREATE TABLE t1(id INTEGER PRIMARY KEY, name TEXT)"},
		{name: "REQ-DDL-002_create_and_insert",
			setup:    []string{"CREATE TABLE t1(id INTEGER PRIMARY KEY, val TEXT)"},
			exec:     "INSERT INTO t1 VALUES(1, 'hello')",
			wantRows: nil},
		{name: "REQ-DDL-003_create_verify_data",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, val TEXT)",
				"INSERT INTO t1 VALUES(1, 'hello')",
			},
			query:    "SELECT id, val FROM t1",
			wantRows: [][]interface{}{{int64(1), "hello"}}},
		{name: "REQ-DDL-004_create_multiple_columns",
			setup: []string{
				"CREATE TABLE t1(a INT, b TEXT, c REAL, d BLOB)",
				"INSERT INTO t1 VALUES(1, 'x', 3.14, X'CAFE')",
			},
			query:    "SELECT a, b, c FROM t1",
			wantRows: [][]interface{}{{int64(1), "x", 3.14}}},
		{name: "REQ-DDL-005_create_without_rowid",
			setup: []string{
				"CREATE TABLE t1(k TEXT PRIMARY KEY, v TEXT) WITHOUT ROWID",
				"INSERT INTO t1 VALUES('a', 'alpha')",
			},
			query:    "SELECT k, v FROM t1",
			wantRows: [][]interface{}{{"a", "alpha"}}},
		{name: "REQ-DDL-006_create_duplicate_table",
			setup:   []string{"CREATE TABLE t1(id INTEGER)"},
			exec:    "CREATE TABLE t1(id INTEGER)",
			wantErr: true, errLike: "already exists"},
	}
}

func genDDLConstraintTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-DDL-010_not_null_enforced",
			setup:   []string{"CREATE TABLE t1(id INTEGER PRIMARY KEY, name TEXT NOT NULL)"},
			exec:    "INSERT INTO t1(id) VALUES(1)",
			wantErr: true, errLike: "NOT NULL"},
		{name: "REQ-DDL-011_not_null_with_value",
			setup: []string{"CREATE TABLE t1(id INTEGER PRIMARY KEY, name TEXT NOT NULL)"},
			exec:  "INSERT INTO t1 VALUES(1, 'ok')"},
		{name: "REQ-DDL-012_unique_enforced",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, code TEXT UNIQUE)",
				"INSERT INTO t1 VALUES(1, 'A')",
			},
			exec:    "INSERT INTO t1 VALUES(2, 'A')",
			wantErr: true, errLike: "UNIQUE"},
		{name: "REQ-DDL-013_unique_allows_distinct",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, code TEXT UNIQUE)",
				"INSERT INTO t1 VALUES(1, 'A')",
			},
			exec: "INSERT INTO t1 VALUES(2, 'B')"},
		{name: "REQ-DDL-014_default_value",
			skip: "engine gap: column-list INSERT does not apply DEFAULT values",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, status TEXT DEFAULT 'active')",
				"INSERT INTO t1(id) VALUES(1)",
			},
			query:    "SELECT status FROM t1 WHERE id = 1",
			wantRows: [][]interface{}{{"active"}}},
		{name: "REQ-DDL-015_default_integer",
			skip: "engine gap: column-list INSERT does not apply DEFAULT values",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, qty INTEGER DEFAULT 0)",
				"INSERT INTO t1(id) VALUES(1)",
			},
			query:    "SELECT qty FROM t1 WHERE id = 1",
			wantRows: [][]interface{}{{int64(0)}}},
		{name: "REQ-DDL-016_check_constraint_reject",
			skip:    "engine gap: CHECK constraints not enforced",
			setup:   []string{"CREATE TABLE t1(id INTEGER PRIMARY KEY, age INTEGER CHECK(age >= 0))"},
			exec:    "INSERT INTO t1 VALUES(1, -1)",
			wantErr: true, errLike: "CHECK"},
		{name: "REQ-DDL-017_check_constraint_accept",
			setup: []string{"CREATE TABLE t1(id INTEGER PRIMARY KEY, age INTEGER CHECK(age >= 0))"},
			exec:  "INSERT INTO t1 VALUES(1, 10)"},
		{name: "REQ-DDL-018_multiple_constraints",
			skip: "engine gap: column-list INSERT does not apply DEFAULT values",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, age INTEGER CHECK(age > 0) DEFAULT 1)",
				"INSERT INTO t1(id, name) VALUES(1, 'Alice')",
			},
			query:    "SELECT name, age FROM t1",
			wantRows: [][]interface{}{{"Alice", int64(1)}}},
	}
}

func genDDLCompositePKTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-DDL-020_composite_pk_create",
			setup: []string{
				"CREATE TABLE t1(a INTEGER, b INTEGER, c TEXT, PRIMARY KEY(a, b))",
				"INSERT INTO t1 VALUES(1, 1, 'one-one')",
				"INSERT INTO t1 VALUES(1, 2, 'one-two')",
			},
			query: "SELECT c FROM t1 ORDER BY a, b",
			wantRows: [][]interface{}{
				{"one-one"}, {"one-two"},
			}},
		{name: "REQ-DDL-021_composite_pk_unique",
			skip: "engine gap: composite PRIMARY KEY uniqueness not enforced",
			setup: []string{
				"CREATE TABLE t1(a INTEGER, b INTEGER, c TEXT, PRIMARY KEY(a, b))",
				"INSERT INTO t1 VALUES(1, 1, 'first')",
			},
			exec:    "INSERT INTO t1 VALUES(1, 1, 'dup')",
			wantErr: true, errLike: "UNIQUE"},
		{name: "REQ-DDL-022_composite_pk_partial_overlap",
			setup: []string{
				"CREATE TABLE t1(a INTEGER, b INTEGER, c TEXT, PRIMARY KEY(a, b))",
				"INSERT INTO t1 VALUES(1, 1, 'x')",
				"INSERT INTO t1 VALUES(1, 2, 'y')",
				"INSERT INTO t1 VALUES(2, 1, 'z')",
			},
			query:    "SELECT COUNT(*) FROM t1",
			wantRows: [][]interface{}{{int64(3)}}},
	}
}

func genDDLIfNotExistsTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-DDL-025_if_not_exists_new",
			exec: "CREATE TABLE IF NOT EXISTS t1(id INTEGER PRIMARY KEY)"},
		{name: "REQ-DDL-026_if_not_exists_existing",
			setup: []string{"CREATE TABLE t1(id INTEGER PRIMARY KEY)"},
			exec:  "CREATE TABLE IF NOT EXISTS t1(id INTEGER PRIMARY KEY)"},
		{name: "REQ-DDL-027_if_not_exists_preserves_data",
			skip: "engine gap: CREATE TABLE IF NOT EXISTS does not preserve existing data",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, val TEXT)",
				"INSERT INTO t1 VALUES(1, 'kept')",
				"CREATE TABLE IF NOT EXISTS t1(id INTEGER PRIMARY KEY, val TEXT)",
			},
			query:    "SELECT val FROM t1",
			wantRows: [][]interface{}{{"kept"}}},
	}
}

func genDDLAlterTableTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-DDL-030_alter_rename_table",
			setup: []string{
				"CREATE TABLE old_t(id INTEGER PRIMARY KEY, val TEXT)",
				"INSERT INTO old_t VALUES(1, 'data')",
				"ALTER TABLE old_t RENAME TO new_t",
			},
			query:    "SELECT val FROM new_t",
			wantRows: [][]interface{}{{"data"}}},
		{name: "REQ-DDL-031_alter_rename_old_gone",
			setup: []string{
				"CREATE TABLE old_t(id INTEGER PRIMARY KEY)",
				"ALTER TABLE old_t RENAME TO new_t",
			},
			query:   "SELECT * FROM old_t",
			wantErr: true, errLike: "table not found"},
		{name: "REQ-DDL-032_alter_rename_column",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, old_col TEXT)",
				"INSERT INTO t1 VALUES(1, 'hi')",
				"ALTER TABLE t1 RENAME COLUMN old_col TO new_col",
			},
			query:    "SELECT new_col FROM t1",
			wantRows: [][]interface{}{{"hi"}}},
		{name: "REQ-DDL-033_alter_add_column",
			skip: "engine gap: ALTER TABLE ADD COLUMN does not backfill DEFAULT for existing rows",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY)",
				"INSERT INTO t1 VALUES(1)",
				"ALTER TABLE t1 ADD COLUMN extra TEXT DEFAULT 'def'",
			},
			query:    "SELECT extra FROM t1",
			wantRows: [][]interface{}{{"def"}}},
		{name: "REQ-DDL-034_alter_drop_column",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, keep_me TEXT, drop_me TEXT)",
				"INSERT INTO t1 VALUES(1, 'yes', 'no')",
				"ALTER TABLE t1 DROP COLUMN drop_me",
			},
			query:    "SELECT keep_me FROM t1 WHERE id = 1",
			wantRows: [][]interface{}{{"yes"}}},
		{name: "REQ-DDL-035_alter_drop_column_gone",
			setup: []string{
				"CREATE TABLE t1(id INTEGER PRIMARY KEY, a TEXT, b TEXT)",
				"ALTER TABLE t1 DROP COLUMN b",
			},
			query:   "SELECT b FROM t1",
			wantErr: true, errLike: "column not found"},
		{name: "REQ-DDL-036_alter_nonexistent_table",
			exec:    "ALTER TABLE nonexistent RENAME TO something",
			wantErr: true, errLike: "table not found"},
	}
}

func genDDLDropTableTests() []sqlTestCase {
	return []sqlTestCase{
		{name: "REQ-DDL-040_drop_table",
			setup: []string{"CREATE TABLE t1(id INTEGER)"},
			exec:  "DROP TABLE t1"},
		{name: "REQ-DDL-041_drop_table_gone",
			setup: []string{
				"CREATE TABLE t1(id INTEGER)",
				"DROP TABLE t1",
			},
			query:   "SELECT * FROM t1",
			wantErr: true, errLike: "table not found"},
		{name: "REQ-DDL-042_drop_if_exists_present",
			setup: []string{"CREATE TABLE t1(id INTEGER)"},
			exec:  "DROP TABLE IF EXISTS t1"},
		{name: "REQ-DDL-043_drop_if_exists_absent",
			exec: "DROP TABLE IF EXISTS nonexistent"},
		{name: "REQ-DDL-044_drop_nonexistent",
			exec:    "DROP TABLE nonexistent",
			wantErr: true, errLike: "table not found"},
	}
}

func genDDLIndexTests() []sqlTestCase {
	baseSetup := []string{
		"CREATE TABLE t1(id INTEGER PRIMARY KEY, name TEXT, age INTEGER)",
		"INSERT INTO t1 VALUES(1, 'Alice', 30)",
		"INSERT INTO t1 VALUES(2, 'Bob', 25)",
	}
	return []sqlTestCase{
		{name: "REQ-DDL-050_create_index",
			setup: baseSetup,
			exec:  "CREATE INDEX idx_name ON t1(name)"},
		{name: "REQ-DDL-051_create_unique_index",
			setup: baseSetup,
			exec:  "CREATE UNIQUE INDEX idx_name_u ON t1(name)"},
		{name: "REQ-DDL-052_unique_index_enforced",
			skip: "engine gap: UNIQUE index constraint not enforced on INSERT",
			setup: append(append([]string{}, baseSetup...),
				"CREATE UNIQUE INDEX idx_name_u ON t1(name)"),
			exec:    "INSERT INTO t1 VALUES(3, 'Alice', 40)",
			wantErr: true, errLike: "UNIQUE"},
		{name: "REQ-DDL-053_index_if_not_exists",
			setup: append(append([]string{}, baseSetup...),
				"CREATE INDEX idx_name ON t1(name)"),
			exec: "CREATE INDEX IF NOT EXISTS idx_name ON t1(name)"},
		{name: "REQ-DDL-054_drop_index",
			setup: append(append([]string{}, baseSetup...),
				"CREATE INDEX idx_name ON t1(name)"),
			exec: "DROP INDEX idx_name"},
		{name: "REQ-DDL-055_drop_index_if_exists",
			exec: "DROP INDEX IF EXISTS nonexistent"},
		{name: "REQ-DDL-056_composite_index",
			setup: baseSetup,
			exec:  "CREATE INDEX idx_name_age ON t1(name, age)"},
		{name: "REQ-DDL-057_index_query_works",
			setup: append(append([]string{}, baseSetup...),
				"CREATE INDEX idx_age ON t1(age)"),
			query:    "SELECT name FROM t1 WHERE age = 25",
			wantRows: [][]interface{}{{"Bob"}}},
	}
}

func genDDLViewTests() []sqlTestCase {
	viewSetup := []string{
		"CREATE TABLE t1(id INTEGER PRIMARY KEY, name TEXT, age INTEGER)",
		"INSERT INTO t1 VALUES(1, 'Alice', 30)",
		"INSERT INTO t1 VALUES(2, 'Bob', 25)",
		"INSERT INTO t1 VALUES(3, 'Carol', 35)",
	}
	return []sqlTestCase{
		{name: "REQ-DDL-060_create_view",
			setup: viewSetup,
			exec:  "CREATE VIEW v1 AS SELECT name, age FROM t1 WHERE age >= 30"},
		{name: "REQ-DDL-061_query_view",
			setup: append(append([]string{}, viewSetup...),
				"CREATE VIEW v1 AS SELECT name, age FROM t1 WHERE age >= 30"),
			query: "SELECT name FROM v1 ORDER BY name",
			wantRows: [][]interface{}{
				{"Alice"}, {"Carol"},
			}},
		{name: "REQ-DDL-062_view_reflects_changes",
			setup: append(append([]string{}, viewSetup...),
				"CREATE VIEW v1 AS SELECT name FROM t1 WHERE age >= 30",
				"INSERT INTO t1 VALUES(4, 'Dave', 40)"),
			query: "SELECT name FROM v1 ORDER BY name",
			wantRows: [][]interface{}{
				{"Alice"}, {"Carol"}, {"Dave"},
			}},
		{name: "REQ-DDL-063_drop_view",
			setup: append(append([]string{}, viewSetup...),
				"CREATE VIEW v1 AS SELECT * FROM t1",
				"DROP VIEW v1"),
			query:   "SELECT * FROM v1",
			wantErr: true, errLike: "table not found"},
		{name: "REQ-DDL-064_drop_view_if_exists",
			exec: "DROP VIEW IF EXISTS nonexistent"},
		{name: "REQ-DDL-065_create_view_if_not_exists",
			setup: append(append([]string{}, viewSetup...),
				"CREATE VIEW v1 AS SELECT name FROM t1"),
			exec: "CREATE VIEW IF NOT EXISTS v1 AS SELECT age FROM t1"},
	}
}

func genDDLReindexTests() []sqlTestCase {
	reindexSetup := []string{
		"CREATE TABLE t1(id INTEGER PRIMARY KEY, val TEXT)",
		"CREATE INDEX idx_val ON t1(val)",
		"INSERT INTO t1 VALUES(1, 'alpha')",
		"INSERT INTO t1 VALUES(2, 'beta')",
	}
	return []sqlTestCase{
		{name: "REQ-DDL-070_reindex_table",
			setup: reindexSetup,
			exec:  "REINDEX t1"},
		{name: "REQ-DDL-071_reindex_index",
			setup: reindexSetup,
			exec:  "REINDEX idx_val"},
		{name: "REQ-DDL-072_reindex_all",
			setup: reindexSetup,
			exec:  "REINDEX"},
		{name: "REQ-DDL-073_reindex_data_intact",
			setup: append(append([]string{}, reindexSetup...), "REINDEX"),
			query: "SELECT val FROM t1 ORDER BY val",
			wantRows: [][]interface{}{
				{"alpha"}, {"beta"},
			}},
	}
}

// Compile-time assertion that sub-generators are used.
var _ = fmt.Sprintf
