// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity

package driver

import "testing"

// TestTrinity_FKey validates foreign key semantics per DO-178C trace.
func TestTrinity_FKey(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityFKeyTests())
}

func buildTrinityFKeyTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genFKeyBasicTests()...)
	tests = append(tests, genFKeyDeleteCascadeTests()...)
	tests = append(tests, genFKeyDeleteSetNullTests()...)
	tests = append(tests, genFKeyDeleteSetDefaultTests()...)
	tests = append(tests, genFKeyDeleteRestrictTests()...)
	tests = append(tests, genFKeyUpdateTests()...)
	tests = append(tests, genFKeyMultiColumnTests()...)
	tests = append(tests, genFKeySelfRefTests()...)
	tests = append(tests, genFKeyDeferredTests()...)
	return tests
}

// ---------------------------------------------------------------------------
// Basic FK constraint
// ---------------------------------------------------------------------------

func genFKeyBasicTests() []sqlTestCase {
	parentChild := []string{
		"PRAGMA foreign_keys=ON",
		"CREATE TABLE parent(id INTEGER PRIMARY KEY, name TEXT)",
		"CREATE TABLE child(id INTEGER PRIMARY KEY, pid INTEGER REFERENCES parent(id))",
	}
	parentChildData := []string{
		"PRAGMA foreign_keys=ON",
		"CREATE TABLE parent(id INTEGER PRIMARY KEY, name TEXT)",
		"CREATE TABLE child(id INTEGER PRIMARY KEY, pid INTEGER REFERENCES parent(id))",
		"INSERT INTO parent VALUES(1,'Alice')",
		"INSERT INTO parent VALUES(2,'Bob')",
	}
	return []sqlTestCase{
		{
			name:    "REQ-FKEY-001_insert_violating_fk",
			setup:   parentChild,
			exec:    "INSERT INTO child VALUES(1, 999)",
			wantErr: true,
			errLike: "FOREIGN KEY",
		},
		{
			name:     "REQ-FKEY-002_insert_valid_fk",
			setup:    append(parentChildData, "INSERT INTO child VALUES(1, 1)"),
			query:    "SELECT id, pid FROM child",
			wantRows: [][]interface{}{{int64(1), int64(1)}},
		},
		{
			name:     "REQ-FKEY-003_insert_null_fk_allowed",
			setup:    append(parentChild, "INSERT INTO child VALUES(1, NULL)"),
			query:    "SELECT id, pid FROM child",
			wantRows: [][]interface{}{{int64(1), nil}},
		},
		{
			name:    "REQ-FKEY-004_delete_parent_with_child",
			setup:   append(parentChildData, "INSERT INTO child VALUES(1, 1)"),
			exec:    "DELETE FROM parent WHERE id=1",
			wantErr: true,
			errLike: "FOREIGN KEY",
		},
		{
			name:    "REQ-FKEY-005_update_parent_pk_with_child",
			setup:   append(parentChildData, "INSERT INTO child VALUES(1, 1)"),
			exec:    "UPDATE parent SET id=99 WHERE id=1",
			wantErr: true,
			errLike: "FOREIGN KEY",
		},
		{
			name:     "REQ-FKEY-006_pragma_foreign_keys_on",
			setup:    []string{"PRAGMA foreign_keys=ON"},
			query:    "PRAGMA foreign_keys",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-FKEY-007_pragma_foreign_keys_off_default",
			query:    "PRAGMA foreign_keys",
			wantRows: [][]interface{}{{int64(0)}},
		},
	}
}

// ---------------------------------------------------------------------------
// ON DELETE CASCADE
// ---------------------------------------------------------------------------

func genFKeyDeleteCascadeTests() []sqlTestCase {
	setup := []string{
		"PRAGMA foreign_keys=ON",
		"CREATE TABLE p_cas(id INTEGER PRIMARY KEY, name TEXT)",
		"CREATE TABLE c_cas(id INTEGER PRIMARY KEY, pid INTEGER REFERENCES p_cas(id) ON DELETE CASCADE, val TEXT)",
		"INSERT INTO p_cas VALUES(1,'Alice')",
		"INSERT INTO p_cas VALUES(2,'Bob')",
		"INSERT INTO c_cas VALUES(1, 1, 'a1')",
		"INSERT INTO c_cas VALUES(2, 1, 'a2')",
		"INSERT INTO c_cas VALUES(3, 2, 'b1')",
	}
	return []sqlTestCase{
		{
			name:     "REQ-FKEY-010_cascade_delete_removes_children",
			setup:    append(setup, "DELETE FROM p_cas WHERE id=1"),
			query:    "SELECT COUNT(*) FROM c_cas",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-FKEY-011_cascade_delete_correct_children",
			setup:    append(setup, "DELETE FROM p_cas WHERE id=1"),
			query:    "SELECT val FROM c_cas",
			wantRows: [][]interface{}{{"b1"}},
		},
		{
			name:     "REQ-FKEY-012_cascade_delete_all_parents",
			setup:    append(setup, "DELETE FROM p_cas"),
			query:    "SELECT COUNT(*) FROM c_cas",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-FKEY-013_cascade_delete_no_matching_children",
			setup:    append(setup, "INSERT INTO p_cas VALUES(3,'Charlie')", "DELETE FROM p_cas WHERE id=3"),
			query:    "SELECT COUNT(*) FROM c_cas",
			wantRows: [][]interface{}{{int64(3)}},
		},
	}
}

// ---------------------------------------------------------------------------
// ON DELETE SET NULL
// ---------------------------------------------------------------------------

func genFKeyDeleteSetNullTests() []sqlTestCase {
	setup := []string{
		"PRAGMA foreign_keys=ON",
		"CREATE TABLE p_sn(id INTEGER PRIMARY KEY, name TEXT)",
		"CREATE TABLE c_sn(id INTEGER PRIMARY KEY, pid INTEGER REFERENCES p_sn(id) ON DELETE SET NULL, val TEXT)",
		"INSERT INTO p_sn VALUES(1,'Alice')",
		"INSERT INTO c_sn VALUES(1, 1, 'a1')",
		"INSERT INTO c_sn VALUES(2, 1, 'a2')",
	}
	return []sqlTestCase{
		{
			name:     "REQ-FKEY-020_set_null_on_delete",
			setup:    append(setup, "DELETE FROM p_sn WHERE id=1"),
			query:    "SELECT id, pid, val FROM c_sn ORDER BY id",
			wantRows: [][]interface{}{{int64(1), nil, "a1"}, {int64(2), nil, "a2"}},
		},
		{
			name:     "REQ-FKEY-021_set_null_preserves_child_row",
			setup:    append(setup, "DELETE FROM p_sn WHERE id=1"),
			query:    "SELECT COUNT(*) FROM c_sn",
			wantRows: [][]interface{}{{int64(2)}},
		},
	}
}

// ---------------------------------------------------------------------------
// ON DELETE SET DEFAULT
// ---------------------------------------------------------------------------

func genFKeyDeleteSetDefaultTests() []sqlTestCase {
	setup := []string{
		"PRAGMA foreign_keys=ON",
		"CREATE TABLE p_sd(id INTEGER PRIMARY KEY, name TEXT)",
		"CREATE TABLE c_sd(id INTEGER PRIMARY KEY, pid INTEGER DEFAULT 0 REFERENCES p_sd(id) ON DELETE SET DEFAULT, val TEXT)",
		"INSERT INTO p_sd VALUES(0,'Default')",
		"INSERT INTO p_sd VALUES(1,'Alice')",
		"INSERT INTO c_sd VALUES(1, 1, 'a1')",
	}
	return []sqlTestCase{
		{
			name:     "REQ-FKEY-025_set_default_on_delete",
			setup:    append(setup, "DELETE FROM p_sd WHERE id=1"),
			query:    "SELECT id, pid, val FROM c_sd",
			wantRows: [][]interface{}{{int64(1), int64(0), "a1"}},
		},
		{
			name:     "REQ-FKEY-026_set_default_preserves_child",
			setup:    append(setup, "DELETE FROM p_sd WHERE id=1"),
			query:    "SELECT COUNT(*) FROM c_sd",
			wantRows: [][]interface{}{{int64(1)}},
		},
	}
}

// ---------------------------------------------------------------------------
// ON DELETE RESTRICT / NO ACTION
// ---------------------------------------------------------------------------

func genFKeyDeleteRestrictTests() []sqlTestCase {
	restrictSetup := []string{
		"PRAGMA foreign_keys=ON",
		"CREATE TABLE p_res(id INTEGER PRIMARY KEY, name TEXT)",
		"CREATE TABLE c_res(id INTEGER PRIMARY KEY, pid INTEGER REFERENCES p_res(id) ON DELETE RESTRICT)",
		"INSERT INTO p_res VALUES(1,'Alice')",
		"INSERT INTO c_res VALUES(1, 1)",
	}
	noActionSetup := []string{
		"PRAGMA foreign_keys=ON",
		"CREATE TABLE p_na(id INTEGER PRIMARY KEY, name TEXT)",
		"CREATE TABLE c_na(id INTEGER PRIMARY KEY, pid INTEGER REFERENCES p_na(id) ON DELETE NO ACTION)",
		"INSERT INTO p_na VALUES(1,'Alice')",
		"INSERT INTO c_na VALUES(1, 1)",
	}
	return []sqlTestCase{
		{
			name:    "REQ-FKEY-030_restrict_prevents_delete",
			setup:   restrictSetup,
			exec:    "DELETE FROM p_res WHERE id=1",
			wantErr: true,
			errLike: "FOREIGN KEY",
		},
		{
			name:     "REQ-FKEY-031_restrict_allows_delete_no_children",
			setup:    []string{"PRAGMA foreign_keys=ON", "CREATE TABLE p_res2(id INTEGER PRIMARY KEY)", "CREATE TABLE c_res2(id INTEGER PRIMARY KEY, pid INTEGER REFERENCES p_res2(id) ON DELETE RESTRICT)", "INSERT INTO p_res2 VALUES(1)", "INSERT INTO p_res2 VALUES(2)", "INSERT INTO c_res2 VALUES(1, 1)", "DELETE FROM p_res2 WHERE id=2"},
			query:    "SELECT COUNT(*) FROM p_res2",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:    "REQ-FKEY-032_no_action_prevents_delete",
			setup:   noActionSetup,
			exec:    "DELETE FROM p_na WHERE id=1",
			wantErr: true,
			errLike: "FOREIGN KEY",
		},
	}
}

// ---------------------------------------------------------------------------
// ON UPDATE CASCADE / SET NULL
// ---------------------------------------------------------------------------

func genFKeyUpdateTests() []sqlTestCase {
	cascadeSetup := []string{
		"PRAGMA foreign_keys=ON",
		"CREATE TABLE p_uc(id INTEGER PRIMARY KEY, name TEXT)",
		"CREATE TABLE c_uc(id INTEGER PRIMARY KEY, pid INTEGER REFERENCES p_uc(id) ON UPDATE CASCADE)",
		"INSERT INTO p_uc VALUES(1,'Alice')",
		"INSERT INTO c_uc VALUES(1, 1)",
	}
	setNullSetup := []string{
		"PRAGMA foreign_keys=ON",
		"CREATE TABLE p_usn(id INTEGER PRIMARY KEY, name TEXT)",
		"CREATE TABLE c_usn(id INTEGER PRIMARY KEY, pid INTEGER REFERENCES p_usn(id) ON UPDATE SET NULL)",
		"INSERT INTO p_usn VALUES(1,'Alice')",
		"INSERT INTO c_usn VALUES(1, 1)",
	}
	return []sqlTestCase{
		{
			name:     "REQ-FKEY-040_update_cascade_propagates",
			setup:    append(cascadeSetup, "UPDATE p_uc SET id=100 WHERE id=1"),
			query:    "SELECT pid FROM c_uc WHERE id=1",
			wantRows: [][]interface{}{{int64(100)}},
		},
		{
			name:     "REQ-FKEY-041_update_cascade_parent_updated",
			setup:    append(cascadeSetup, "UPDATE p_uc SET id=100 WHERE id=1"),
			query:    "SELECT id FROM p_uc",
			wantRows: [][]interface{}{{int64(100)}},
		},
		{
			name:     "REQ-FKEY-042_update_cascade_multiple_children",
			setup:    []string{"PRAGMA foreign_keys=ON", "CREATE TABLE p_uc2(id INTEGER PRIMARY KEY)", "CREATE TABLE c_uc2(id INTEGER PRIMARY KEY, pid INTEGER REFERENCES p_uc2(id) ON UPDATE CASCADE)", "INSERT INTO p_uc2 VALUES(1)", "INSERT INTO c_uc2 VALUES(1,1)", "INSERT INTO c_uc2 VALUES(2,1)", "UPDATE p_uc2 SET id=50 WHERE id=1"},
			query:    "SELECT pid FROM c_uc2 ORDER BY id",
			wantRows: [][]interface{}{{int64(50)}, {int64(50)}},
		},
		{
			name:     "REQ-FKEY-043_update_set_null",
			setup:    append(setNullSetup, "UPDATE p_usn SET id=100 WHERE id=1"),
			query:    "SELECT pid FROM c_usn WHERE id=1",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-FKEY-044_update_set_null_preserves_row",
			setup:    append(setNullSetup, "UPDATE p_usn SET id=100 WHERE id=1"),
			query:    "SELECT COUNT(*) FROM c_usn",
			wantRows: [][]interface{}{{int64(1)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Multi-column FK
// ---------------------------------------------------------------------------

func genFKeyMultiColumnTests() []sqlTestCase {
	setup := []string{
		"PRAGMA foreign_keys=ON",
		"CREATE TABLE p_mc(a INTEGER, b INTEGER, name TEXT, PRIMARY KEY(a, b))",
		"CREATE TABLE c_mc(id INTEGER PRIMARY KEY, pa INTEGER, pb INTEGER, FOREIGN KEY(pa, pb) REFERENCES p_mc(a, b))",
		"INSERT INTO p_mc VALUES(1, 1, 'one-one')",
		"INSERT INTO p_mc VALUES(1, 2, 'one-two')",
	}
	return []sqlTestCase{
		{
			name:     "REQ-FKEY-050_multi_col_fk_valid",
			setup:    append(setup, "INSERT INTO c_mc VALUES(1, 1, 1)"),
			query:    "SELECT id, pa, pb FROM c_mc",
			wantRows: [][]interface{}{{int64(1), int64(1), int64(1)}},
		},
		{
			name:    "REQ-FKEY-051_multi_col_fk_violation",
			setup:   setup,
			exec:    "INSERT INTO c_mc VALUES(1, 1, 99)",
			wantErr: true,
			errLike: "FOREIGN KEY",
		},
		{
			name:    "REQ-FKEY-052_multi_col_fk_partial_match",
			setup:   setup,
			exec:    "INSERT INTO c_mc VALUES(1, 99, 1)",
			wantErr: true,
			errLike: "FOREIGN KEY",
		},
		{
			name:     "REQ-FKEY-053_multi_col_fk_null_allowed",
			setup:    append(setup, "INSERT INTO c_mc VALUES(1, NULL, NULL)"),
			query:    "SELECT pa, pb FROM c_mc",
			wantRows: [][]interface{}{{nil, nil}},
		},
	}
}

// ---------------------------------------------------------------------------
// Self-referencing FK
// ---------------------------------------------------------------------------

func genFKeySelfRefTests() []sqlTestCase {
	setup := []string{
		"PRAGMA foreign_keys=ON",
		"CREATE TABLE tree(id INTEGER PRIMARY KEY, parent_id INTEGER REFERENCES tree(id))",
		"INSERT INTO tree VALUES(1, NULL)",
		"INSERT INTO tree VALUES(2, 1)",
		"INSERT INTO tree VALUES(3, 1)",
	}
	return []sqlTestCase{
		{
			name:     "REQ-FKEY-060_self_ref_root_node",
			setup:    setup,
			query:    "SELECT id, parent_id FROM tree WHERE parent_id IS NULL",
			wantRows: [][]interface{}{{int64(1), nil}},
		},
		{
			name:     "REQ-FKEY-061_self_ref_child_nodes",
			setup:    setup,
			query:    "SELECT COUNT(*) FROM tree WHERE parent_id=1",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name:    "REQ-FKEY-062_self_ref_invalid_parent",
			setup:   setup,
			exec:    "INSERT INTO tree VALUES(4, 999)",
			wantErr: true,
			errLike: "FOREIGN KEY",
		},
		{
			name:     "REQ-FKEY-063_self_ref_valid_insert",
			setup:    append(setup, "INSERT INTO tree VALUES(4, 2)"),
			query:    "SELECT parent_id FROM tree WHERE id=4",
			wantRows: [][]interface{}{{int64(2)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Deferred FK constraints
// ---------------------------------------------------------------------------

func genFKeyDeferredTests() []sqlTestCase {
	deferSetup := []string{
		"PRAGMA foreign_keys=ON",
		"CREATE TABLE p_def(id INTEGER PRIMARY KEY)",
		"CREATE TABLE c_def(id INTEGER PRIMARY KEY, pid INTEGER REFERENCES p_def(id) DEFERRABLE INITIALLY DEFERRED)",
	}
	return []sqlTestCase{
		{
			name:     "REQ-FKEY-070_deferred_fk_within_transaction",
			setup:    append(deferSetup, "BEGIN", "INSERT INTO c_def VALUES(1, 1)", "INSERT INTO p_def VALUES(1)", "COMMIT"),
			query:    "SELECT c_def.id, c_def.pid FROM c_def",
			wantRows: [][]interface{}{{int64(1), int64(1)}},
		},
		{
			name:    "REQ-FKEY-071_deferred_fk_violation_at_commit",
			setup:   append(deferSetup, "BEGIN", "INSERT INTO c_def VALUES(1, 999)"),
			exec:    "COMMIT",
			wantErr: true,
			errLike: "FOREIGN KEY",
		},
		{
			name:     "REQ-FKEY-072_deferred_fk_insert_order_independent",
			setup:    append(deferSetup, "BEGIN", "INSERT INTO c_def VALUES(1, 10)", "INSERT INTO c_def VALUES(2, 20)", "INSERT INTO p_def VALUES(10)", "INSERT INTO p_def VALUES(20)", "COMMIT"),
			query:    "SELECT COUNT(*) FROM c_def",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name:     "REQ-FKEY-073_deferred_fk_delete_and_reinsert",
			setup:    append(deferSetup, "INSERT INTO p_def VALUES(1)", "INSERT INTO c_def VALUES(1, 1)", "BEGIN", "DELETE FROM p_def WHERE id=1", "INSERT INTO p_def VALUES(1)", "COMMIT"),
			query:    "SELECT pid FROM c_def",
			wantRows: [][]interface{}{{int64(1)}},
		},
	}
}
