// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity

package driver

import "testing"

// TestTrinity_JSON validates JSON1 extension functions per DO-178C trace.
func TestTrinity_JSON(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityJSONTests())
}

func buildTrinityJSONTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genJSONScalarTests()...)
	tests = append(tests, genJSONExtractTests()...)
	tests = append(tests, genJSONTypeValidTests()...)
	tests = append(tests, genJSONModifyTests()...)
	tests = append(tests, genJSONTableTests()...)
	return tests
}

// ---------------------------------------------------------------------------
// json(), json_array(), json_object()
// ---------------------------------------------------------------------------

func genJSONScalarTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-JSON-001_json_minify",
			query:    `SELECT json('  { "a" : 1 }  ')`,
			wantRows: [][]interface{}{{`{"a":1}`}},
		},
		{
			name:     "REQ-JSON-002_json_array_empty",
			query:    "SELECT json_array()",
			wantRows: [][]interface{}{{"[]"}},
		},
		{
			name:     "REQ-JSON-003_json_array_ints",
			query:    "SELECT json_array(1, 2, 3)",
			wantRows: [][]interface{}{{"[1,2,3]"}},
		},
		{
			name:     "REQ-JSON-004_json_array_mixed",
			query:    `SELECT json_array(1, 'two', NULL, 3.0)`,
			wantRows: [][]interface{}{{"[1,\"two\",null,3.0]"}},
		},
		{
			name:     "REQ-JSON-005_json_object_empty",
			query:    "SELECT json_object()",
			wantRows: [][]interface{}{{"{}"}},
		},
		{
			name:     "REQ-JSON-006_json_object_single",
			query:    `SELECT json_object('a', 1)`,
			wantRows: [][]interface{}{{`{"a":1}`}},
		},
		{
			name:     "REQ-JSON-007_json_object_multiple",
			query:    `SELECT json_object('a', 1, 'b', 'two', 'c', NULL)`,
			wantRows: [][]interface{}{{`{"a":1,"b":"two","c":null}`}},
		},
		{
			name:     "REQ-JSON-008_json_array_nested",
			query:    `SELECT json_array(1, json_array(2, 3))`,
			wantRows: [][]interface{}{{"[1,[2,3]]"}},
		},
		{
			name:     "REQ-JSON-009_json_object_nested",
			query:    `SELECT json_object('a', json_object('b', 2))`,
			wantRows: [][]interface{}{{`{"a":{"b":2}}`}},
		},
		{
			name:    "REQ-JSON-010_json_invalid_input",
			query:   `SELECT json('not json')`,
			wantErr: true,
			errLike: "malformed",
		},
		{
			name:     "REQ-JSON-011_json_null_literal",
			query:    `SELECT json('null')`,
			wantRows: [][]interface{}{{"null"}},
		},
		{
			name:     "REQ-JSON-012_json_string_value",
			query:    `SELECT json('"hello"')`,
			wantRows: [][]interface{}{{`"hello"`}},
		},
	}
}

// ---------------------------------------------------------------------------
// json_extract()
// ---------------------------------------------------------------------------

func genJSONExtractTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-JSON-020_extract_root",
			query:    `SELECT json_extract('{"a":1}', '$')`,
			wantRows: [][]interface{}{{`{"a":1}`}},
		},
		{
			name:     "REQ-JSON-021_extract_key",
			query:    `SELECT json_extract('{"a":1,"b":2}', '$.a')`,
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-JSON-022_extract_nested",
			query:    `SELECT json_extract('{"a":{"b":{"c":3}}}', '$.a.b.c')`,
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-JSON-023_extract_array_element",
			query:    `SELECT json_extract('[10,20,30]', '$[1]')`,
			wantRows: [][]interface{}{{int64(20)}},
		},
		{
			name:     "REQ-JSON-024_extract_null_key",
			query:    `SELECT json_extract('{"a":null}', '$.a')`,
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-JSON-025_extract_missing_key",
			query:    `SELECT json_extract('{"a":1}', '$.b')`,
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-JSON-026_extract_string_value",
			query:    `SELECT json_extract('{"name":"alice"}', '$.name')`,
			wantRows: [][]interface{}{{"alice"}},
		},
		{
			name:     "REQ-JSON-027_extract_multi_path",
			query:    `SELECT json_extract('{"a":1,"b":2}', '$.a', '$.b')`,
			wantRows: [][]interface{}{{"[1,2]"}},
		},
		{
			name:     "REQ-JSON-028_extract_from_table",
			setup:    []string{"CREATE TABLE je1(doc TEXT)", `INSERT INTO je1 VALUES('{"x":42}')`},
			query:    "SELECT json_extract(doc, '$.x') FROM je1",
			wantRows: [][]interface{}{{int64(42)}},
		},
		{
			name:     "REQ-JSON-029_extract_real_value",
			query:    `SELECT json_extract('{"pi":3.14}', '$.pi')`,
			wantRows: [][]interface{}{{3.14}},
		},
		{
			name:     "REQ-JSON-030_extract_bool_true",
			query:    `SELECT json_extract('{"flag":true}', '$.flag')`,
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-JSON-031_extract_bool_false",
			query:    `SELECT json_extract('{"flag":false}', '$.flag')`,
			wantRows: [][]interface{}{{int64(0)}},
		},
	}
}

// ---------------------------------------------------------------------------
// json_type(), json_valid()
// ---------------------------------------------------------------------------

func genJSONTypeValidTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-JSON-040_type_object",
			query:    `SELECT json_type('{"a":1}')`,
			wantRows: [][]interface{}{{"object"}},
		},
		{
			name:     "REQ-JSON-041_type_array",
			query:    `SELECT json_type('[1,2]')`,
			wantRows: [][]interface{}{{"array"}},
		},
		{
			name:     "REQ-JSON-042_type_integer",
			query:    `SELECT json_type('42')`,
			wantRows: [][]interface{}{{"integer"}},
		},
		{
			name:     "REQ-JSON-043_type_real",
			query:    `SELECT json_type('3.14')`,
			wantRows: [][]interface{}{{"real"}},
		},
		{
			name:     "REQ-JSON-044_type_text",
			query:    `SELECT json_type('"hello"')`,
			wantRows: [][]interface{}{{"text"}},
		},
		{
			name:     "REQ-JSON-045_type_null",
			query:    `SELECT json_type('null')`,
			wantRows: [][]interface{}{{"null"}},
		},
		{
			name:     "REQ-JSON-046_type_true",
			query:    `SELECT json_type('true')`,
			wantRows: [][]interface{}{{"true"}},
		},
		{
			name:     "REQ-JSON-047_type_at_path",
			query:    `SELECT json_type('{"a":[1,2]}', '$.a')`,
			wantRows: [][]interface{}{{"array"}},
		},
		{
			name:     "REQ-JSON-048_valid_object",
			query:    `SELECT json_valid('{"a":1}')`,
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-JSON-049_valid_invalid",
			query:    `SELECT json_valid('{bad}')`,
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-JSON-050_valid_null_input",
			query:    "SELECT json_valid(NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-JSON-051_valid_plain_string",
			query:    `SELECT json_valid('hello')`,
			wantRows: [][]interface{}{{int64(0)}},
		},
	}
}

// ---------------------------------------------------------------------------
// json_insert(), json_replace(), json_remove(), json_set()
// ---------------------------------------------------------------------------

func genJSONModifyTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-JSON-060_insert_new_key",
			query:    `SELECT json_insert('{"a":1}', '$.b', 2)`,
			wantRows: [][]interface{}{{`{"a":1,"b":2}`}},
		},
		{
			name:     "REQ-JSON-061_insert_existing_key_noop",
			query:    `SELECT json_insert('{"a":1}', '$.a', 99)`,
			wantRows: [][]interface{}{{`{"a":1}`}},
		},
		{
			name:     "REQ-JSON-062_replace_existing_key",
			query:    `SELECT json_replace('{"a":1}', '$.a', 99)`,
			wantRows: [][]interface{}{{`{"a":99}`}},
		},
		{
			name:     "REQ-JSON-063_replace_missing_key_noop",
			query:    `SELECT json_replace('{"a":1}', '$.b', 99)`,
			wantRows: [][]interface{}{{`{"a":1}`}},
		},
		{
			name:     "REQ-JSON-064_set_new_key",
			query:    `SELECT json_set('{"a":1}', '$.b', 2)`,
			wantRows: [][]interface{}{{`{"a":1,"b":2}`}},
		},
		{
			name:     "REQ-JSON-065_set_existing_key",
			query:    `SELECT json_set('{"a":1}', '$.a', 99)`,
			wantRows: [][]interface{}{{`{"a":99}`}},
		},
		{
			name:     "REQ-JSON-066_remove_key",
			query:    `SELECT json_remove('{"a":1,"b":2}', '$.a')`,
			wantRows: [][]interface{}{{`{"b":2}`}},
		},
		{
			name:     "REQ-JSON-067_remove_missing_key_noop",
			query:    `SELECT json_remove('{"a":1}', '$.b')`,
			wantRows: [][]interface{}{{`{"a":1}`}},
		},
		{
			name:     "REQ-JSON-068_remove_array_element",
			query:    `SELECT json_remove('[1,2,3]', '$[1]')`,
			wantRows: [][]interface{}{{"[1,3]"}},
		},
		{
			name:     "REQ-JSON-069_set_nested",
			query:    `SELECT json_set('{"a":{"b":1}}', '$.a.b', 42)`,
			wantRows: [][]interface{}{{`{"a":{"b":42}}`}},
		},
		{
			name:     "REQ-JSON-070_insert_into_array",
			query:    `SELECT json_insert('[1,2]', '$[2]', 3)`,
			wantRows: [][]interface{}{{"[1,2,3]"}},
		},
		{
			name:     "REQ-JSON-071_set_null_value",
			query:    `SELECT json_set('{"a":1}', '$.a', NULL)`,
			wantRows: [][]interface{}{{`{"a":null}`}},
		},
	}
}

// ---------------------------------------------------------------------------
// json_group_array(), json_group_object()
// ---------------------------------------------------------------------------

func genJSONTableTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE jt1(id INTEGER, name TEXT, val INTEGER)",
		"INSERT INTO jt1 VALUES(1, 'a', 10)",
		"INSERT INTO jt1 VALUES(2, 'b', 20)",
		"INSERT INTO jt1 VALUES(3, 'c', 30)",
	}
	return []sqlTestCase{
		{
			name:     "REQ-JSON-080_group_array_all",
			setup:    setup,
			query:    "SELECT json_group_array(val) FROM jt1",
			wantRows: [][]interface{}{{"[10,20,30]"}},
		},
		{
			name:     "REQ-JSON-081_group_array_filtered",
			setup:    setup,
			query:    "SELECT json_group_array(val) FROM jt1 WHERE id <= 2",
			wantRows: [][]interface{}{{"[10,20]"}},
		},
		{
			name:     "REQ-JSON-082_group_object_all",
			setup:    setup,
			query:    "SELECT json_group_object(name, val) FROM jt1",
			wantRows: [][]interface{}{{`{"a":10,"b":20,"c":30}`}},
		},
		{
			name:     "REQ-JSON-083_group_array_single",
			setup:    setup,
			query:    "SELECT json_group_array(val) FROM jt1 WHERE id=1",
			wantRows: [][]interface{}{{"[10]"}},
		},
		{
			name:     "REQ-JSON-084_group_array_strings",
			setup:    setup,
			query:    "SELECT json_group_array(name) FROM jt1",
			wantRows: [][]interface{}{{`["a","b","c"]`}},
		},
		{
			name:     "REQ-JSON-085_group_object_single",
			setup:    setup,
			query:    "SELECT json_group_object(name, val) FROM jt1 WHERE id=2",
			wantRows: [][]interface{}{{`{"b":20}`}},
		},
	}
}
