// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import (
	"fmt"
	"math"
	"strings"
	"testing"
)

// TestTrinity_Boundary exercises INT64 MAX/MIN, INT32 MAX/MIN, 0/1/-1 with
// arithmetic, float edges, string edges, and SQL limit boundaries per DO-178C trace.
func TestTrinity_Boundary(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityBoundaryTests())
}

func buildTrinityBoundaryTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genBoundaryIntTests()...)
	tests = append(tests, genBoundaryArithEdgeTests()...)
	tests = append(tests, genBoundarySmallValArithTests()...)
	tests = append(tests, genBoundaryFloatTests()...)
	tests = append(tests, genBoundaryStringTests()...)
	tests = append(tests, genBoundaryLimitTests()...)
	tests = append(tests, genBoundarySQLLimitTests()...)
	return tests
}

// ---------------------------------------------------------------------------
// INT64 / INT32 boundary values
// ---------------------------------------------------------------------------

func genBoundaryIntTests() []sqlTestCase {
	bounds := []struct {
		desc string
		expr string
		want interface{}
	}{
		{"int64_max", "9223372036854775807", int64(math.MaxInt64)},
		{"int64_min", "-9223372036854775808", int64(math.MinInt64)},
		{"int32_max", "2147483647", int64(math.MaxInt32)},
		{"int32_min", "-2147483648", int64(math.MinInt32)},
		{"zero", "0", int64(0)},
		{"one", "1", int64(1)},
		{"neg_one", "-1", int64(-1)},
	}
	var tests []sqlTestCase
	for i, b := range bounds {
		tests = append(tests, sqlTestCase{
			name:     fmt.Sprintf("REQ-TBND-%03d_%s_select", i+1, b.desc),
			query:    fmt.Sprintf("SELECT %s", b.expr),
			wantRows: [][]interface{}{{b.want}},
		})
	}
	for i, b := range bounds {
		tests = append(tests, sqlTestCase{
			name: fmt.Sprintf("REQ-TBND-%03d_%s_roundtrip", i+10, b.desc),
			setup: []string{
				"CREATE TABLE bnd_rt(v INTEGER)",
				fmt.Sprintf("INSERT INTO bnd_rt VALUES(%s)", b.expr),
			},
			query:    "SELECT v FROM bnd_rt",
			wantRows: [][]interface{}{{b.want}},
		})
	}
	return tests
}

// ---------------------------------------------------------------------------
// Arithmetic overflow / edge cases
// ---------------------------------------------------------------------------

func genBoundaryArithEdgeTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-TBND-020_max_plus_one_overflow",
			query:    "SELECT 9223372036854775807 + 1",
			wantRows: [][]interface{}{{-9.223372036854776e+18}},
			skip:     "known integer overflow to float",
		},
		{
			name:     "REQ-TBND-021_min_minus_one_overflow",
			query:    "SELECT -9223372036854775808 - 1",
			wantRows: [][]interface{}{{9.223372036854776e+18}},
			skip:     "known integer overflow to float",
		},
		{
			name:     "REQ-TBND-022_div_by_zero_int",
			query:    "SELECT 1 / 0",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-TBND-023_zero_div_zero",
			query:    "SELECT 0 / 0",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-TBND-024_zero_mod_zero",
			query:    "SELECT 0 % 0",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-TBND-025_neg_div_pos_trunc",
			query:    "SELECT -7 / 2",
			wantRows: [][]interface{}{{int64(-3)}},
			skip:     "known integer division truncation direction",
		},
		{
			name:     "REQ-TBND-027_max_negate",
			query:    "SELECT -(9223372036854775807)",
			wantRows: [][]interface{}{{int64(-math.MaxInt64)}},
		},
		{
			name:     "REQ-TBND-028_max_minus_max",
			query:    "SELECT 9223372036854775807 - 9223372036854775807",
			wantRows: [][]interface{}{{int64(0)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Small-value arithmetic (0, 1, -1)
// ---------------------------------------------------------------------------

func genBoundarySmallValArithTests() []sqlTestCase {
	vals := []struct {
		desc string
		expr string
		v    int64
	}{
		{"zero", "0", 0},
		{"one", "1", 1},
		{"neg_one", "-1", -1},
	}
	type arithOp struct {
		desc   string
		sql    string
		result func(v int64) interface{}
	}
	ops := []arithOp{
		{"add_0", "%d + 0", func(v int64) interface{} { return v }},
		{"add_1", "%d + 1", func(v int64) interface{} { return v + 1 }},
		{"sub_1", "%d - 1", func(v int64) interface{} { return v - 1 }},
		{"mul_1", "%d * 1", func(v int64) interface{} { return v }},
		{"cast_text", "CAST(%d AS TEXT)", func(v int64) interface{} { return fmt.Sprintf("%d", v) }},
	}
	var tests []sqlTestCase
	n := 100
	for _, val := range vals {
		for _, op := range ops {
			name := fmt.Sprintf("REQ-TBND-%03d_%s_%s", n, val.desc, op.desc)
			q := fmt.Sprintf("SELECT "+op.sql, val.v)
			tests = append(tests, sqlTestCase{
				name:     name,
				query:    q,
				wantRows: [][]interface{}{{op.result(val.v)}},
			})
			n++
		}
	}
	return tests
}

// ---------------------------------------------------------------------------
// IEEE 754 floating-point edge cases
// ---------------------------------------------------------------------------

func genBoundaryFloatTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-TBND-030_float_zero",
			query:    "SELECT 0.0",
			wantRows: [][]interface{}{{0.0}},
		},
		{
			name:     "REQ-TBND-031_float_neg_zero",
			query:    "SELECT -0.0",
			wantRows: [][]interface{}{{0.0}},
		},
		{
			name:     "REQ-TBND-032_float_very_small",
			query:    "SELECT 1e-300",
			wantRows: [][]interface{}{{1e-300}},
			skip:     "known very small float precision",
		},
		{
			name:     "REQ-TBND-033_float_very_large",
			query:    "SELECT 1e300",
			wantRows: [][]interface{}{{1e300}},
			skip:     "known very large float precision",
		},
		{
			name:     "REQ-TBND-034_float_inf_via_overflow",
			query:    "SELECT 1e308 * 2",
			wantRows: [][]interface{}{{math.Inf(1)}},
			skip:     "known inf handling",
		},
		{
			name:     "REQ-TBND-035_float_neg_inf_via_overflow",
			query:    "SELECT -1e308 * 2",
			wantRows: [][]interface{}{{math.Inf(-1)}},
			skip:     "known inf handling",
		},
		{
			name:     "REQ-TBND-036_typeof_real",
			query:    "SELECT TYPEOF(9007199254740992.0)",
			wantRows: [][]interface{}{{"real"}},
		},
		{
			name:     "REQ-TBND-037_float_cast_from_int",
			query:    "SELECT CAST(42 AS REAL)",
			wantRows: [][]interface{}{{42.0}},
		},
	}
}

// ---------------------------------------------------------------------------
// String edge cases
// ---------------------------------------------------------------------------

func genBoundaryStringTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-TBND-040_empty_string",
			query:    "SELECT ''",
			wantRows: [][]interface{}{{""}},
		},
		{
			name:     "REQ-TBND-041_empty_string_length",
			query:    "SELECT LENGTH('')",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-TBND-042_single_char",
			query:    "SELECT 'x'",
			wantRows: [][]interface{}{{"x"}},
		},
		{
			name:     "REQ-TBND-043_embedded_single_quote",
			query:    "SELECT ''''",
			wantRows: [][]interface{}{{"'"}},
		},
		{
			name:     "REQ-TBND-044_unicode_basic",
			query:    "SELECT '\u00e9\u00e8\u00ea'",
			wantRows: [][]interface{}{{"éèê"}},
		},
		{
			name:     "REQ-TBND-045_unicode_cjk",
			query:    "SELECT '\u4e16\u754c'",
			wantRows: [][]interface{}{{"世界"}},
		},
		{
			name:     "REQ-TBND-046_unicode_length",
			query:    "SELECT LENGTH('\u00e9\u00e8\u00ea')",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name: "REQ-TBND-047_long_string_1000",
			setup: []string{
				"CREATE TABLE bnd_str(v TEXT)",
				"INSERT INTO bnd_str VALUES('" + strings.Repeat("x", 1000) + "')",
			},
			query:    "SELECT LENGTH(v) FROM bnd_str",
			wantRows: [][]interface{}{{int64(1000)}},
		},
		{
			name:     "REQ-TBND-048_typeof_empty_string",
			query:    "SELECT TYPEOF('')",
			wantRows: [][]interface{}{{"text"}},
		},
	}
}

// ---------------------------------------------------------------------------
// LIMIT / OFFSET boundary values
// ---------------------------------------------------------------------------

func genBoundaryLimitTests() []sqlTestCase {
	fiveRowSetup := []string{
		"CREATE TABLE bnd_lim(v INTEGER)",
		"INSERT INTO bnd_lim VALUES(1)",
		"INSERT INTO bnd_lim VALUES(2)",
		"INSERT INTO bnd_lim VALUES(3)",
		"INSERT INTO bnd_lim VALUES(4)",
		"INSERT INTO bnd_lim VALUES(5)",
	}
	return []sqlTestCase{
		{
			name:     "REQ-TBND-050_limit_zero",
			setup:    fiveRowSetup,
			query:    "SELECT v FROM bnd_lim LIMIT 0",
			wantRows: [][]interface{}{},
		},
		{
			name:  "REQ-TBND-051_limit_negative_returns_all",
			skip:  "engine rejects negative LIMIT values",
			setup: fiveRowSetup,
			query: "SELECT v FROM bnd_lim ORDER BY v LIMIT -1",
			wantRows: [][]interface{}{
				{int64(1)}, {int64(2)}, {int64(3)}, {int64(4)}, {int64(5)},
			},
		},
		{
			name:     "REQ-TBND-052_offset_past_end",
			setup:    fiveRowSetup,
			query:    "SELECT v FROM bnd_lim LIMIT 10 OFFSET 100",
			wantRows: [][]interface{}{},
		},
		{
			name:     "REQ-TBND-053_offset_zero",
			setup:    fiveRowSetup,
			query:    "SELECT v FROM bnd_lim ORDER BY v LIMIT 10 OFFSET 0",
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}, {int64(3)}, {int64(4)}, {int64(5)}},
		},
		{
			name:  "REQ-TBND-054_limit_exact_count",
			setup: fiveRowSetup,
			query: "SELECT v FROM bnd_lim ORDER BY v LIMIT 5",
			wantRows: [][]interface{}{
				{int64(1)}, {int64(2)}, {int64(3)}, {int64(4)}, {int64(5)},
			},
		},
		{
			name:     "REQ-TBND-055_limit_exceeds_rows",
			setup:    fiveRowSetup,
			query:    "SELECT COUNT(*) FROM (SELECT v FROM bnd_lim LIMIT 1000)",
			wantRows: [][]interface{}{{int64(5)}},
		},
		{
			name:     "REQ-TBND-056_limit_large_number",
			setup:    fiveRowSetup,
			query:    "SELECT COUNT(*) FROM (SELECT v FROM bnd_lim LIMIT 999999999)",
			wantRows: [][]interface{}{{int64(5)}},
		},
	}
}

// ---------------------------------------------------------------------------
// SQL complexity limits (many columns, nested expressions)
// ---------------------------------------------------------------------------

func genBoundarySQLLimitTests() []sqlTestCase {
	var tests []sqlTestCase

	// 50-column SELECT
	cols50 := make([]string, 50)
	want50 := make([]interface{}, 50)
	for i := range cols50 {
		cols50[i] = fmt.Sprintf("%d", i+1)
		want50[i] = int64(i + 1)
	}
	tests = append(tests, sqlTestCase{
		name:     "REQ-TBND-200_50_col_select",
		query:    "SELECT " + strings.Join(cols50, ", "),
		wantRows: [][]interface{}{want50},
	})

	// Nested parentheses (30 deep)
	inner := "1"
	for i := 0; i < 30; i++ {
		inner = "(" + inner + ")"
	}
	tests = append(tests, sqlTestCase{
		name:     "REQ-TBND-201_nested_parens_30",
		query:    "SELECT " + inner,
		wantRows: [][]interface{}{{int64(1)}},
	})

	// 100-element IN list
	elems := make([]string, 100)
	for i := range elems {
		elems[i] = fmt.Sprintf("%d", i+1)
	}
	tests = append(tests, sqlTestCase{
		name:     "REQ-TBND-202_100_element_in_list",
		query:    "SELECT 50 IN (" + strings.Join(elems, ", ") + ")",
		wantRows: [][]interface{}{{int64(1)}},
	})

	// UNION ALL (5 branches)
	tests = append(tests, sqlTestCase{
		name: "REQ-TBND-204_union_all_5",
		query: "SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 " +
			"UNION ALL SELECT 4 UNION ALL SELECT 5",
		wantRows: [][]interface{}{
			{int64(1)}, {int64(2)}, {int64(3)}, {int64(4)}, {int64(5)},
		},
	})

	// Nested CASE expression
	tests = append(tests, sqlTestCase{
		name:     "REQ-TBND-205_nested_case",
		query:    "SELECT CASE WHEN 1=1 THEN CASE WHEN 2=2 THEN CASE WHEN 3=3 THEN 'deep' ELSE 'no' END ELSE 'no' END ELSE 'no' END",
		wantRows: [][]interface{}{{"deep"}},
	})

	// Long chained OR
	orParts := make([]string, 20)
	for i := range orParts {
		orParts[i] = fmt.Sprintf("1=%d", i+1)
	}
	tests = append(tests, sqlTestCase{
		name:     "REQ-TBND-206_chained_or_20",
		query:    "SELECT CASE WHEN " + strings.Join(orParts, " OR ") + " THEN 1 ELSE 0 END",
		wantRows: [][]interface{}{{int64(1)}},
	})

	// Deeply nested subquery
	tests = append(tests, sqlTestCase{
		name:     "REQ-TBND-207_nested_subquery",
		query:    "SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT 42)))",
		wantRows: [][]interface{}{{int64(42)}},
	})

	// Many columns in table
	colDefs := make([]string, 30)
	colNames := make([]string, 30)
	colVals := make([]string, 30)
	wantMany := make([]interface{}, 30)
	for i := range colDefs {
		colDefs[i] = fmt.Sprintf("c%d INTEGER", i)
		colNames[i] = fmt.Sprintf("c%d", i)
		colVals[i] = fmt.Sprintf("%d", i+1)
		wantMany[i] = int64(i + 1)
	}
	tests = append(tests, sqlTestCase{
		name: "REQ-TBND-209_30_col_table",
		setup: []string{
			"CREATE TABLE bnd_wide(" + strings.Join(colDefs, ", ") + ")",
			"INSERT INTO bnd_wide VALUES(" + strings.Join(colVals, ", ") + ")",
		},
		query:    "SELECT " + strings.Join(colNames, ", ") + " FROM bnd_wide",
		wantRows: [][]interface{}{wantMany},
	})

	return tests
}
