// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import "testing"

// TestTrinity_Index validates index creation and semantics per DO-178C trace.
func TestTrinity_Index(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityIndexTests())
}

func buildTrinityIndexTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genIndexBasicTests()...)
	tests = append(tests, genIndexUniqueTests()...)
	tests = append(tests, genIndexCompositeTests()...)
	tests = append(tests, genIndexPartialTests()...)
	tests = append(tests, genIndexDropTests()...)
	tests = append(tests, genIndexVerifyTests()...)
	return tests
}

// ---------------------------------------------------------------------------
// Basic index creation
// ---------------------------------------------------------------------------

func genIndexBasicTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-IDX-001_create_basic_index",
			setup:    []string{"CREATE TABLE ib1(a INTEGER, b TEXT)", "CREATE INDEX idx_ib1_a ON ib1(a)"},
			query:    "SELECT COUNT(*) FROM sqlite_master WHERE type='index' AND name='idx_ib1_a'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:    "REQ-IDX-002_create_duplicate_index_error",
			setup:   []string{"CREATE TABLE ib2(a INTEGER)", "CREATE INDEX idx_ib2_a ON ib2(a)"},
			exec:    "CREATE INDEX idx_ib2_a ON ib2(a)",
			wantErr: true,
			errLike: "already exists",
		},
		{
			name:    "REQ-IDX-003_create_index_if_not_exists",
			setup:   []string{"CREATE TABLE ib3(a INTEGER)", "CREATE INDEX idx_ib3_a ON ib3(a)"},
			exec:    "CREATE INDEX IF NOT EXISTS idx_ib3_a ON ib3(a)",
			wantErr: false,
		},
		{
			name:     "REQ-IDX-004_create_index_on_text",
			setup:    []string{"CREATE TABLE ib4(name TEXT)", "CREATE INDEX idx_ib4_name ON ib4(name)", "INSERT INTO ib4 VALUES('alice')", "INSERT INTO ib4 VALUES('bob')"},
			query:    "SELECT name FROM ib4 WHERE name='alice'",
			wantRows: [][]interface{}{{"alice"}},
		},
		{
			name:     "REQ-IDX-005_index_preserves_order",
			setup:    []string{"CREATE TABLE ib5(a INTEGER)", "INSERT INTO ib5 VALUES(3)", "INSERT INTO ib5 VALUES(1)", "INSERT INTO ib5 VALUES(2)", "CREATE INDEX idx_ib5_a ON ib5(a)"},
			query:    "SELECT a FROM ib5 ORDER BY a",
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}, {int64(3)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Unique indexes
// ---------------------------------------------------------------------------

func genIndexUniqueTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-IDX-010_unique_index_create",
			setup:    []string{"CREATE TABLE iu1(a INTEGER)", "CREATE UNIQUE INDEX idx_iu1_a ON iu1(a)"},
			query:    "SELECT COUNT(*) FROM sqlite_master WHERE type='index' AND name='idx_iu1_a'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:    "REQ-IDX-011_unique_index_rejects_dup",
			setup:   []string{"CREATE TABLE iu2(a INTEGER)", "CREATE UNIQUE INDEX idx_iu2_a ON iu2(a)", "INSERT INTO iu2 VALUES(1)"},
			exec:    "INSERT INTO iu2 VALUES(1)",
			wantErr: true,
			errLike: "UNIQUE constraint",
		},
		{
			name:     "REQ-IDX-012_unique_index_allows_distinct",
			setup:    []string{"CREATE TABLE iu3(a INTEGER)", "CREATE UNIQUE INDEX idx_iu3_a ON iu3(a)", "INSERT INTO iu3 VALUES(1)", "INSERT INTO iu3 VALUES(2)"},
			query:    "SELECT COUNT(*) FROM iu3",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name:     "REQ-IDX-013_unique_index_null_allowed",
			setup:    []string{"CREATE TABLE iu4(a INTEGER)", "CREATE UNIQUE INDEX idx_iu4_a ON iu4(a)", "INSERT INTO iu4 VALUES(NULL)", "INSERT INTO iu4 VALUES(NULL)"},
			query:    "SELECT COUNT(*) FROM iu4",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name:    "REQ-IDX-014_unique_index_multi_col_dup",
			setup:   []string{"CREATE TABLE iu5(a INTEGER, b INTEGER)", "CREATE UNIQUE INDEX idx_iu5_ab ON iu5(a, b)", "INSERT INTO iu5 VALUES(1, 1)"},
			exec:    "INSERT INTO iu5 VALUES(1, 1)",
			wantErr: true,
			errLike: "UNIQUE constraint",
		},
		{
			name:     "REQ-IDX-015_unique_index_multi_col_partial_dup",
			setup:    []string{"CREATE TABLE iu6(a INTEGER, b INTEGER)", "CREATE UNIQUE INDEX idx_iu6_ab ON iu6(a, b)", "INSERT INTO iu6 VALUES(1, 1)", "INSERT INTO iu6 VALUES(1, 2)"},
			query:    "SELECT COUNT(*) FROM iu6",
			wantRows: [][]interface{}{{int64(2)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Composite indexes
// ---------------------------------------------------------------------------

func genIndexCompositeTests() []sqlTestCase {
	setup := []string{
		"CREATE TABLE ic1(a INTEGER, b TEXT, c REAL)",
		"CREATE INDEX idx_ic1_ab ON ic1(a, b)",
		"INSERT INTO ic1 VALUES(1, 'x', 1.0)",
		"INSERT INTO ic1 VALUES(1, 'y', 2.0)",
		"INSERT INTO ic1 VALUES(2, 'x', 3.0)",
		"INSERT INTO ic1 VALUES(2, 'y', 4.0)",
	}
	return []sqlTestCase{
		{
			name:     "REQ-IDX-020_composite_index_exists",
			setup:    setup,
			query:    "SELECT COUNT(*) FROM sqlite_master WHERE type='index' AND name='idx_ic1_ab'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-IDX-021_composite_index_filter_both",
			setup:    setup,
			query:    "SELECT c FROM ic1 WHERE a=1 AND b='x'",
			wantRows: [][]interface{}{{1.0}},
		},
		{
			name:     "REQ-IDX-022_composite_index_filter_first",
			setup:    setup,
			query:    "SELECT COUNT(*) FROM ic1 WHERE a=1",
			wantRows: [][]interface{}{{int64(2)}},
		},
		{
			name:     "REQ-IDX-023_composite_index_order",
			setup:    setup,
			query:    "SELECT a, b FROM ic1 ORDER BY a, b",
			wantRows: [][]interface{}{{int64(1), "x"}, {int64(1), "y"}, {int64(2), "x"}, {int64(2), "y"}},
		},
		{
			name:     "REQ-IDX-024_composite_three_col",
			setup:    []string{"CREATE TABLE ic2(a INTEGER, b INTEGER, c INTEGER)", "CREATE INDEX idx_ic2_abc ON ic2(a,b,c)", "INSERT INTO ic2 VALUES(1,2,3)", "INSERT INTO ic2 VALUES(1,2,4)"},
			query:    "SELECT c FROM ic2 WHERE a=1 AND b=2 ORDER BY c",
			wantRows: [][]interface{}{{int64(3)}, {int64(4)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Partial indexes
// ---------------------------------------------------------------------------

func genIndexPartialTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-IDX-030_partial_index_create",
			setup:    []string{"CREATE TABLE ip1(a INTEGER, active INTEGER)", "CREATE INDEX idx_ip1_active ON ip1(a) WHERE active=1"},
			query:    "SELECT COUNT(*) FROM sqlite_master WHERE type='index' AND name='idx_ip1_active'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name: "REQ-IDX-031_partial_index_query",
			setup: []string{
				"CREATE TABLE ip2(a INTEGER, status TEXT)",
				"CREATE INDEX idx_ip2_status ON ip2(a) WHERE status='open'",
				"INSERT INTO ip2 VALUES(1, 'open')",
				"INSERT INTO ip2 VALUES(2, 'closed')",
				"INSERT INTO ip2 VALUES(3, 'open')",
			},
			query:    "SELECT a FROM ip2 WHERE status='open' ORDER BY a",
			wantRows: [][]interface{}{{int64(1)}, {int64(3)}},
		},
		{
			name: "REQ-IDX-032_partial_index_gt_zero",
			setup: []string{
				"CREATE TABLE ip3(val INTEGER)",
				"CREATE INDEX idx_ip3_pos ON ip3(val) WHERE val > 0",
				"INSERT INTO ip3 VALUES(-1)",
				"INSERT INTO ip3 VALUES(0)",
				"INSERT INTO ip3 VALUES(1)",
				"INSERT INTO ip3 VALUES(2)",
			},
			query:    "SELECT val FROM ip3 WHERE val > 0 ORDER BY val",
			wantRows: [][]interface{}{{int64(1)}, {int64(2)}},
		},
		{
			name: "REQ-IDX-033_partial_index_not_null",
			setup: []string{
				"CREATE TABLE ip4(a INTEGER, b TEXT)",
				"CREATE INDEX idx_ip4_nn ON ip4(a) WHERE b IS NOT NULL",
				"INSERT INTO ip4 VALUES(1, 'yes')",
				"INSERT INTO ip4 VALUES(2, NULL)",
				"INSERT INTO ip4 VALUES(3, 'also')",
			},
			query:    "SELECT a FROM ip4 WHERE b IS NOT NULL ORDER BY a",
			wantRows: [][]interface{}{{int64(1)}, {int64(3)}},
		},
	}
}

// ---------------------------------------------------------------------------
// DROP INDEX
// ---------------------------------------------------------------------------

func genIndexDropTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-IDX-040_drop_index",
			setup:    []string{"CREATE TABLE id1(a INTEGER)", "CREATE INDEX idx_id1_a ON id1(a)", "DROP INDEX idx_id1_a"},
			query:    "SELECT COUNT(*) FROM sqlite_master WHERE type='index' AND name='idx_id1_a'",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:    "REQ-IDX-041_drop_nonexistent_error",
			exec:    "DROP INDEX idx_nonexistent",
			wantErr: true,
			errLike: "index not found",
		},
		{
			name:    "REQ-IDX-042_drop_if_exists",
			exec:    "DROP INDEX IF EXISTS idx_nonexistent",
			wantErr: false,
		},
		{
			name: "REQ-IDX-043_drop_index_data_preserved",
			setup: []string{
				"CREATE TABLE id4(a INTEGER)",
				"CREATE INDEX idx_id4_a ON id4(a)",
				"INSERT INTO id4 VALUES(1)",
				"INSERT INTO id4 VALUES(2)",
				"DROP INDEX idx_id4_a",
			},
			query:    "SELECT COUNT(*) FROM id4",
			wantRows: [][]interface{}{{int64(2)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Verify index correctness
// ---------------------------------------------------------------------------

func genIndexVerifyTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name: "REQ-IDX-050_verify_index_correct_after_insert",
			setup: []string{
				"CREATE TABLE iv1(a INTEGER, b TEXT)",
				"CREATE INDEX idx_iv1_a ON iv1(a)",
				"INSERT INTO iv1 VALUES(3, 'c')",
				"INSERT INTO iv1 VALUES(1, 'a')",
				"INSERT INTO iv1 VALUES(2, 'b')",
			},
			query:    "SELECT b FROM iv1 WHERE a=2",
			wantRows: [][]interface{}{{"b"}},
		},
		{
			name: "REQ-IDX-051_verify_index_after_delete",
			setup: []string{
				"CREATE TABLE iv2(a INTEGER, b TEXT)",
				"CREATE INDEX idx_iv2_a ON iv2(a)",
				"INSERT INTO iv2 VALUES(1, 'a')",
				"INSERT INTO iv2 VALUES(2, 'b')",
				"INSERT INTO iv2 VALUES(3, 'c')",
				"DELETE FROM iv2 WHERE a=2",
			},
			query:    "SELECT b FROM iv2 WHERE a >= 1 ORDER BY a",
			wantRows: [][]interface{}{{"a"}, {"c"}},
		},
		{
			name: "REQ-IDX-052_verify_index_after_update",
			setup: []string{
				"CREATE TABLE iv3(a INTEGER, b TEXT)",
				"CREATE INDEX idx_iv3_a ON iv3(a)",
				"INSERT INTO iv3 VALUES(1, 'old')",
				"UPDATE iv3 SET b='new' WHERE a=1",
			},
			query:    "SELECT b FROM iv3 WHERE a=1",
			wantRows: [][]interface{}{{"new"}},
		},
		{
			name: "REQ-IDX-053_verify_range_scan",
			setup: []string{
				"CREATE TABLE iv4(a INTEGER)",
				"CREATE INDEX idx_iv4_a ON iv4(a)",
				"INSERT INTO iv4 VALUES(10)",
				"INSERT INTO iv4 VALUES(20)",
				"INSERT INTO iv4 VALUES(30)",
				"INSERT INTO iv4 VALUES(40)",
				"INSERT INTO iv4 VALUES(50)",
			},
			query:    "SELECT a FROM iv4 WHERE a BETWEEN 20 AND 40 ORDER BY a",
			wantRows: [][]interface{}{{int64(20)}, {int64(30)}, {int64(40)}},
		},
		{
			name: "REQ-IDX-054_verify_null_in_index",
			setup: []string{
				"CREATE TABLE iv5(a INTEGER)",
				"CREATE INDEX idx_iv5_a ON iv5(a)",
				"INSERT INTO iv5 VALUES(1)",
				"INSERT INTO iv5 VALUES(NULL)",
				"INSERT INTO iv5 VALUES(2)",
			},
			query:    "SELECT COUNT(*) FROM iv5 WHERE a IS NULL",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name: "REQ-IDX-055_verify_index_large_insert",
			setup: []string{
				"CREATE TABLE iv6(a INTEGER)",
				"CREATE INDEX idx_iv6_a ON iv6(a)",
				"INSERT INTO iv6 VALUES(50)", "INSERT INTO iv6 VALUES(40)", "INSERT INTO iv6 VALUES(30)",
				"INSERT INTO iv6 VALUES(20)", "INSERT INTO iv6 VALUES(10)", "INSERT INTO iv6 VALUES(5)",
				"INSERT INTO iv6 VALUES(15)", "INSERT INTO iv6 VALUES(25)", "INSERT INTO iv6 VALUES(35)",
				"INSERT INTO iv6 VALUES(45)",
			},
			query:    "SELECT MIN(a), MAX(a), COUNT(*) FROM iv6",
			wantRows: [][]interface{}{{int64(5), int64(50), int64(10)}},
		},
	}
}
