// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
// Code generated by cmd/trinitygen. DO NOT EDIT.

//go:build trinity || alltests

package driver

import (
	"fmt"
	"testing"
)

func TestTrinity_Expr(t *testing.T) {
	runSQLTestsFreshDB(t, buildTrinityExprTests())
}

func buildTrinityExprTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genBinaryArithTests()...)
	tests = append(tests, genBinaryConcatTests()...)
	tests = append(tests, genBinaryCompareTests()...)
	tests = append(tests, genBinaryLogicTests()...)
	tests = append(tests, genBinaryISTests()...)
	tests = append(tests, genUnaryTests()...)
	tests = append(tests, genSpecialExprTests()...)
	return tests
}

// ---------------------------------------------------------------------------
// Binary arithmetic: +, -, *, /, %
// ---------------------------------------------------------------------------

func genBinaryArithTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genArithIntInt()...)
	tests = append(tests, genArithIntFloat()...)
	tests = append(tests, genArithFloatFloat()...)
	tests = append(tests, genArithNullOperand()...)
	tests = append(tests, genArithStringCoerce()...)
	tests = append(tests, genArithDivisionEdge()...)
	return tests
}

func genArithIntInt() []sqlTestCase {
	type arithCase struct {
		op   string
		a, b int
		want interface{}
	}
	cases := []arithCase{
		{"+", 3, 4, int64(7)},
		{"+", -5, 10, int64(5)},
		{"+", 0, 0, int64(0)},
		{"+", 2147483647, 1, int64(2147483648)},
		{"-", 10, 3, int64(7)},
		{"-", 0, 5, int64(-5)},
		{"-", -3, -7, int64(4)},
		{"*", 6, 7, int64(42)},
		{"*", -3, 4, int64(-12)},
		{"*", 0, 999, int64(0)},
		{"/", 10, 3, int64(3)},
		{"/", 7, 2, int64(3)},
		{"/", -9, 2, int64(-4)},
		{"%", 10, 3, int64(1)},
		{"%", 7, 2, int64(1)},
		{"%", 8, 4, int64(0)},
	}
	tests := make([]sqlTestCase, len(cases))
	for i, c := range cases {
		tests[i] = sqlTestCase{
			name:     fmt.Sprintf("REQ-EXPR-001_arith_int_int/%d%s%d", c.a, c.op, c.b),
			query:    fmt.Sprintf("SELECT %d %s %d", c.a, c.op, c.b),
			wantRows: [][]interface{}{{c.want}},
		}
	}
	return tests
}

func genArithIntFloat() []sqlTestCase {
	type af struct {
		op   string
		a    int
		b    float64
		want float64
	}
	cases := []af{
		{"+", 1, 2.5, 3.5},
		{"-", 10, 3.5, 6.5},
		{"*", 4, 2.5, 10.0},
		{"/", 7, 2.0, 3.5},
		{"+", 0, 0.0, 0.0},
		{"*", 0, 1.5, 0.0},
		{"-", -3, 1.5, -4.5},
	}
	tests := make([]sqlTestCase, len(cases))
	for i, c := range cases {
		tests[i] = sqlTestCase{
			name:     fmt.Sprintf("REQ-EXPR-002_arith_int_float/%d%s%.1f", c.a, c.op, c.b),
			query:    fmt.Sprintf("SELECT %d %s %f", c.a, c.op, c.b),
			wantRows: [][]interface{}{{c.want}},
		}
	}
	return tests
}

func genArithFloatFloat() []sqlTestCase {
	type ff struct {
		op   string
		a, b float64
		want float64
	}
	cases := []ff{
		{"+", 1.5, 2.5, 4.0},
		{"-", 5.5, 2.0, 3.5},
		{"*", 2.5, 4.0, 10.0},
		{"/", 7.5, 2.5, 3.0},
		{"+", -1.5, -2.5, -4.0},
		{"*", -2.0, 3.0, -6.0},
	}
	tests := make([]sqlTestCase, len(cases))
	for i, c := range cases {
		tests[i] = sqlTestCase{
			name:     fmt.Sprintf("REQ-EXPR-003_arith_float_float/%.1f%s%.1f", c.a, c.op, c.b),
			query:    fmt.Sprintf("SELECT %f %s %f", c.a, c.op, c.b),
			wantRows: [][]interface{}{{c.want}},
		}
	}
	return tests
}

func genArithNullOperand() []sqlTestCase {
	ops := []string{"+", "-", "*", "/", "%"}
	tests := make([]sqlTestCase, 0, len(ops)*2)
	for _, op := range ops {
		tests = append(tests, sqlTestCase{
			name:     fmt.Sprintf("REQ-EXPR-004_arith_null_left/NULL%s1", op),
			query:    fmt.Sprintf("SELECT NULL %s 1", op),
			wantRows: [][]interface{}{{nil}},
		})
		tests = append(tests, sqlTestCase{
			name:     fmt.Sprintf("REQ-EXPR-004_arith_null_right/1%sNULL", op),
			query:    fmt.Sprintf("SELECT 1 %s NULL", op),
			wantRows: [][]interface{}{{nil}},
		})
	}
	return tests
}

func genArithStringCoerce() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-005_arith_string_coerce/string_plus_int",
			query:    "SELECT '10' + 5",
			wantRows: [][]interface{}{{int64(15)}},
		},
		{
			name:     "REQ-EXPR-005_arith_string_coerce/string_times_int",
			query:    "SELECT '3' * 4",
			wantRows: [][]interface{}{{int64(12)}},
		},
		{
			name:     "REQ-EXPR-005_arith_string_coerce/non_numeric_string",
			query:    "SELECT 'abc' + 1",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-005_arith_string_coerce/partial_numeric_string",
			skip:     "engine does not extract leading digits from partial numeric strings",
			query:    "SELECT '5abc' + 1",
			wantRows: [][]interface{}{{int64(6)}},
		},
	}
}

func genArithDivisionEdge() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-006_division_by_zero/int",
			query:    "SELECT 1 / 0",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-EXPR-006_division_by_zero/mod",
			query:    "SELECT 1 % 0",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-EXPR-006_division_by_zero/float",
			query:    "SELECT 1.0 / 0.0",
			wantRows: [][]interface{}{{nil}},
		},
	}
}

// ---------------------------------------------------------------------------
// String concatenation: ||
// ---------------------------------------------------------------------------

func genBinaryConcatTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-010_concat/str_str",
			query:    "SELECT 'hello' || ' ' || 'world'",
			wantRows: [][]interface{}{{"hello world"}},
		},
		{
			name:     "REQ-EXPR-010_concat/str_int",
			query:    "SELECT 'val=' || 42",
			wantRows: [][]interface{}{{"val=42"}},
		},
		{
			name:     "REQ-EXPR-010_concat/int_str",
			query:    "SELECT 42 || ' items'",
			wantRows: [][]interface{}{{"42 items"}},
		},
		{
			name:     "REQ-EXPR-010_concat/str_float",
			query:    "SELECT 'pi=' || 3.14",
			wantRows: [][]interface{}{{"pi=3.14"}},
		},
		{
			name:     "REQ-EXPR-010_concat/str_null",
			query:    "SELECT 'hello' || NULL",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-EXPR-010_concat/null_str",
			query:    "SELECT NULL || 'world'",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-EXPR-010_concat/empty_strings",
			query:    "SELECT '' || ''",
			wantRows: [][]interface{}{{""}},
		},
		{
			name:     "REQ-EXPR-010_concat/int_int",
			query:    "SELECT 1 || 2",
			wantRows: [][]interface{}{{"12"}},
		},
	}
}

// ---------------------------------------------------------------------------
// Comparison operators: =, !=, <, >, <=, >=, <>
// ---------------------------------------------------------------------------

func genBinaryCompareTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genCompareIntTests()...)
	tests = append(tests, genCompareStringTests()...)
	tests = append(tests, genCompareNullTests()...)
	tests = append(tests, genCompareMixedTests()...)
	return tests
}

func genCompareIntTests() []sqlTestCase {
	type cmpCase struct {
		op   string
		a, b int
		want int64
	}
	cases := []cmpCase{
		{"=", 1, 1, 1}, {"=", 1, 2, 0},
		{"!=", 1, 2, 1}, {"!=", 1, 1, 0},
		{"<>", 1, 2, 1}, {"<>", 1, 1, 0},
		{"<", 1, 2, 1}, {"<", 2, 1, 0}, {"<", 1, 1, 0},
		{">", 2, 1, 1}, {">", 1, 2, 0}, {">", 1, 1, 0},
		{"<=", 1, 2, 1}, {"<=", 1, 1, 1}, {"<=", 2, 1, 0},
		{">=", 2, 1, 1}, {">=", 1, 1, 1}, {">=", 1, 2, 0},
	}
	tests := make([]sqlTestCase, len(cases))
	for i, c := range cases {
		tests[i] = sqlTestCase{
			name:     fmt.Sprintf("REQ-EXPR-020_compare_int/%d%s%d", c.a, c.op, c.b),
			query:    fmt.Sprintf("SELECT %d %s %d", c.a, c.op, c.b),
			wantRows: [][]interface{}{{c.want}},
		}
	}
	return tests
}

func genCompareStringTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-021_compare_str/equal",
			query:    "SELECT 'abc' = 'abc'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-021_compare_str/not_equal",
			query:    "SELECT 'abc' = 'def'",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-021_compare_str/less_than",
			query:    "SELECT 'abc' < 'def'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-021_compare_str/greater_than",
			query:    "SELECT 'def' > 'abc'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-021_compare_str/case_sensitive",
			query:    "SELECT 'ABC' = 'abc'",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-021_compare_str/empty_vs_nonempty",
			query:    "SELECT '' < 'a'",
			wantRows: [][]interface{}{{int64(1)}},
		},
	}
}

func genCompareNullTests() []sqlTestCase {
	ops := []string{"=", "!=", "<", ">", "<=", ">="}
	tests := make([]sqlTestCase, 0, len(ops)*2)
	for _, op := range ops {
		tests = append(tests, sqlTestCase{
			name:     fmt.Sprintf("REQ-EXPR-022_compare_null/NULL%s1", op),
			query:    fmt.Sprintf("SELECT NULL %s 1", op),
			wantRows: [][]interface{}{{nil}},
		})
		tests = append(tests, sqlTestCase{
			name:     fmt.Sprintf("REQ-EXPR-022_compare_null/1%sNULL", op),
			query:    fmt.Sprintf("SELECT 1 %s NULL", op),
			wantRows: [][]interface{}{{nil}},
		})
	}
	return tests
}

func genCompareMixedTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-023_compare_mixed/int_eq_float",
			query:    "SELECT 1 = 1.0",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-023_compare_mixed/int_lt_float",
			query:    "SELECT 1 < 1.5",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-023_compare_mixed/str_vs_int",
			query:    "SELECT '9' > 10",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-023_compare_mixed/float_eq_int",
			query:    "SELECT 2.0 = 2",
			wantRows: [][]interface{}{{int64(1)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Logic: AND, OR, NOT with TRUE/FALSE/NULL
// ---------------------------------------------------------------------------

func genBinaryLogicTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genLogicANDTests()...)
	tests = append(tests, genLogicORTests()...)
	tests = append(tests, genLogicNOTTests()...)
	return tests
}

func genLogicANDTests() []sqlTestCase {
	type logicCase struct {
		a, b string
		want interface{}
	}
	cases := []logicCase{
		{"1", "1", int64(1)},
		{"1", "0", int64(0)},
		{"0", "1", int64(0)},
		{"0", "0", int64(0)},
		{"1", "NULL", nil},
		{"NULL", "1", nil},
		{"0", "NULL", int64(0)},
		{"NULL", "0", int64(0)},
		{"NULL", "NULL", nil},
	}
	tests := make([]sqlTestCase, len(cases))
	for i, c := range cases {
		tests[i] = sqlTestCase{
			name:     fmt.Sprintf("REQ-EXPR-030_logic_and/%s_AND_%s", c.a, c.b),
			query:    fmt.Sprintf("SELECT %s AND %s", c.a, c.b),
			wantRows: [][]interface{}{{c.want}},
		}
	}
	return tests
}

func genLogicORTests() []sqlTestCase {
	type logicCase struct {
		a, b string
		want interface{}
	}
	cases := []logicCase{
		{"1", "1", int64(1)},
		{"1", "0", int64(1)},
		{"0", "1", int64(1)},
		{"0", "0", int64(0)},
		{"1", "NULL", int64(1)},
		{"NULL", "1", int64(1)},
		{"0", "NULL", nil},
		{"NULL", "0", nil},
		{"NULL", "NULL", nil},
	}
	tests := make([]sqlTestCase, len(cases))
	for i, c := range cases {
		tests[i] = sqlTestCase{
			name:     fmt.Sprintf("REQ-EXPR-031_logic_or/%s_OR_%s", c.a, c.b),
			query:    fmt.Sprintf("SELECT %s OR %s", c.a, c.b),
			wantRows: [][]interface{}{{c.want}},
		}
	}
	return tests
}

func genLogicNOTTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-032_logic_not/NOT_1",
			query:    "SELECT NOT 1",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-032_logic_not/NOT_0",
			query:    "SELECT NOT 0",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-032_logic_not/NOT_NULL",
			query:    "SELECT NOT NULL",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-EXPR-032_logic_not/NOT_42",
			query:    "SELECT NOT 42",
			wantRows: [][]interface{}{{int64(0)}},
		},
	}
}

// ---------------------------------------------------------------------------
// IS / IS NOT NULL
// ---------------------------------------------------------------------------

func genBinaryISTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-040_is/NULL_IS_NULL",
			query:    "SELECT NULL IS NULL",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-040_is/1_IS_NULL",
			query:    "SELECT 1 IS NULL",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-040_is/0_IS_NULL",
			query:    "SELECT 0 IS NULL",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-040_is/empty_str_IS_NULL",
			query:    "SELECT '' IS NULL",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-041_is_not/NULL_IS_NOT_NULL",
			query:    "SELECT NULL IS NOT NULL",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-041_is_not/1_IS_NOT_NULL",
			query:    "SELECT 1 IS NOT NULL",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-041_is_not/str_IS_NOT_NULL",
			query:    "SELECT 'hello' IS NOT NULL",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-042_is/1_IS_1",
			query:    "SELECT 1 IS 1",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-042_is/1_IS_2",
			query:    "SELECT 1 IS 2",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-042_is/1_IS_NOT_2",
			query:    "SELECT 1 IS NOT 2",
			wantRows: [][]interface{}{{int64(1)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Unary operators: -, +, NOT, ~
// ---------------------------------------------------------------------------

func genUnaryTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genUnaryMinusTests()...)
	tests = append(tests, genUnaryPlusTests()...)
	tests = append(tests, genUnaryBitwiseNotTests()...)
	return tests
}

func genUnaryMinusTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-050_unary_minus/int",
			query:    "SELECT -42",
			wantRows: [][]interface{}{{int64(-42)}},
		},
		{
			name:     "REQ-EXPR-050_unary_minus/float",
			query:    "SELECT -3.14",
			wantRows: [][]interface{}{{float64(-3.14)}},
		},
		{
			name:     "REQ-EXPR-050_unary_minus/zero",
			query:    "SELECT -0",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-050_unary_minus/null",
			query:    "SELECT -NULL",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-EXPR-050_unary_minus/double_neg",
			query:    "SELECT -(-5)",
			wantRows: [][]interface{}{{int64(5)}},
		},
		{
			name:     "REQ-EXPR-050_unary_minus/string_coerce",
			query:    "SELECT -'10'",
			wantRows: [][]interface{}{{int64(-10)}},
		},
	}
}

func genUnaryPlusTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-051_unary_plus/int",
			query:    "SELECT +42",
			wantRows: [][]interface{}{{int64(42)}},
		},
		{
			name:     "REQ-EXPR-051_unary_plus/float",
			query:    "SELECT +3.14",
			wantRows: [][]interface{}{{float64(3.14)}},
		},
		{
			name:     "REQ-EXPR-051_unary_plus/null",
			query:    "SELECT +NULL",
			wantRows: [][]interface{}{{nil}},
		},
	}
}

func genUnaryBitwiseNotTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-052_bitwise_not/zero",
			query:    "SELECT ~0",
			wantRows: [][]interface{}{{int64(-1)}},
		},
		{
			name:     "REQ-EXPR-052_bitwise_not/one",
			query:    "SELECT ~1",
			wantRows: [][]interface{}{{int64(-2)}},
		},
		{
			name:     "REQ-EXPR-052_bitwise_not/neg_one",
			query:    "SELECT ~(-1)",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-052_bitwise_not/null",
			query:    "SELECT ~NULL",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-EXPR-052_bitwise_not/255",
			query:    "SELECT ~255",
			wantRows: [][]interface{}{{int64(-256)}},
		},
	}
}

// ---------------------------------------------------------------------------
// Special expressions: BETWEEN, IN, LIKE, GLOB, CASE, CAST, EXISTS, COALESCE
// ---------------------------------------------------------------------------

func genSpecialExprTests() []sqlTestCase {
	var tests []sqlTestCase
	tests = append(tests, genBetweenTests()...)
	tests = append(tests, genInTests()...)
	tests = append(tests, genLikeTests()...)
	tests = append(tests, genGlobTests()...)
	tests = append(tests, genCaseWhenTests()...)
	tests = append(tests, genCastTests()...)
	tests = append(tests, genExistsTests()...)
	return tests
}

func genBetweenTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-060_between/in_range",
			query:    "SELECT 5 BETWEEN 1 AND 10",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-060_between/at_lower",
			query:    "SELECT 1 BETWEEN 1 AND 10",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-060_between/at_upper",
			query:    "SELECT 10 BETWEEN 1 AND 10",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-060_between/below_range",
			query:    "SELECT 0 BETWEEN 1 AND 10",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-060_between/above_range",
			query:    "SELECT 11 BETWEEN 1 AND 10",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-060_between/not_between",
			query:    "SELECT 5 NOT BETWEEN 1 AND 10",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-060_between/string",
			query:    "SELECT 'b' BETWEEN 'a' AND 'c'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-060_between/null_value",
			query:    "SELECT NULL BETWEEN 1 AND 10",
			wantRows: [][]interface{}{{nil}},
		},
	}
}

func genInTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-061_in/found",
			query:    "SELECT 3 IN (1, 2, 3, 4, 5)",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-061_in/not_found",
			query:    "SELECT 6 IN (1, 2, 3, 4, 5)",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-061_in/string",
			query:    "SELECT 'b' IN ('a', 'b', 'c')",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-061_in/not_in",
			query:    "SELECT 3 NOT IN (1, 2, 4, 5)",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-061_in/null_in_list",
			query:    "SELECT 1 IN (1, NULL)",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-061_in/null_not_found",
			query:    "SELECT 2 IN (1, NULL)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-EXPR-061_in/subquery",
			setup:    []string{"CREATE TABLE t_in(v INTEGER)", "INSERT INTO t_in VALUES(10),(20),(30)"},
			query:    "SELECT 20 IN (SELECT v FROM t_in)",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-061_in/subquery_not_found",
			setup:    []string{"CREATE TABLE t_in2(v INTEGER)", "INSERT INTO t_in2 VALUES(10),(20),(30)"},
			query:    "SELECT 99 IN (SELECT v FROM t_in2)",
			wantRows: [][]interface{}{{int64(0)}},
		},
	}
}

func genLikeTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-062_like/percent_match",
			query:    "SELECT 'hello world' LIKE 'hello%'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-062_like/percent_no_match",
			query:    "SELECT 'hello world' LIKE 'goodbye%'",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-062_like/underscore_match",
			query:    "SELECT 'abc' LIKE 'a_c'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-062_like/underscore_no_match",
			query:    "SELECT 'abbc' LIKE 'a_c'",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-062_like/exact_match",
			query:    "SELECT 'hello' LIKE 'hello'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-062_like/case_insensitive",
			query:    "SELECT 'Hello' LIKE 'hello'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-062_like/not_like",
			query:    "SELECT 'hello' NOT LIKE 'world%'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-062_like/null_pattern",
			query:    "SELECT 'hello' LIKE NULL",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-EXPR-062_like/null_value",
			query:    "SELECT NULL LIKE 'hello%'",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-EXPR-062_like/escape_percent",
			skip:     "LIKE ESCAPE clause not yet supported by parser",
			query:    "SELECT '10%' LIKE '10\\%%' ESCAPE '\\'",
			wantRows: [][]interface{}{{int64(1)}},
		},
	}
}

func genGlobTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-063_glob/star_match",
			query:    "SELECT 'hello world' GLOB 'hello*'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-063_glob/star_no_match",
			query:    "SELECT 'hello world' GLOB 'goodbye*'",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-063_glob/question_mark",
			query:    "SELECT 'abc' GLOB 'a?c'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-063_glob/case_sensitive",
			query:    "SELECT 'Hello' GLOB 'hello'",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-063_glob/bracket_range",
			skip:     "GLOB bracket ranges not yet implemented",
			query:    "SELECT 'a' GLOB '[a-z]'",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-063_glob/bracket_no_match",
			skip:     "GLOB bracket ranges not yet implemented",
			query:    "SELECT 'A' GLOB '[a-z]'",
			wantRows: [][]interface{}{{int64(0)}},
		},
	}
}

func genCaseWhenTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-064_case/simple_when_true",
			query:    "SELECT CASE WHEN 1=1 THEN 'yes' ELSE 'no' END",
			wantRows: [][]interface{}{{"yes"}},
		},
		{
			name:     "REQ-EXPR-064_case/simple_when_false",
			query:    "SELECT CASE WHEN 1=2 THEN 'yes' ELSE 'no' END",
			wantRows: [][]interface{}{{"no"}},
		},
		{
			name:     "REQ-EXPR-064_case/multi_when",
			query:    "SELECT CASE WHEN 1=2 THEN 'a' WHEN 2=2 THEN 'b' ELSE 'c' END",
			wantRows: [][]interface{}{{"b"}},
		},
		{
			name:     "REQ-EXPR-064_case/no_else_null",
			query:    "SELECT CASE WHEN 1=2 THEN 'yes' END",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-EXPR-064_case/simple_form",
			query:    "SELECT CASE 2 WHEN 1 THEN 'one' WHEN 2 THEN 'two' WHEN 3 THEN 'three' END",
			wantRows: [][]interface{}{{"two"}},
		},
		{
			name:     "REQ-EXPR-064_case/simple_form_else",
			query:    "SELECT CASE 99 WHEN 1 THEN 'one' ELSE 'other' END",
			wantRows: [][]interface{}{{"other"}},
		},
		{
			name:     "REQ-EXPR-064_case/nested",
			query:    "SELECT CASE WHEN 1=1 THEN CASE WHEN 2=2 THEN 'nested' END END",
			wantRows: [][]interface{}{{"nested"}},
		},
	}
}

func genCastTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-065_cast/int_to_text",
			query:    "SELECT CAST(42 AS TEXT)",
			wantRows: [][]interface{}{{"42"}},
		},
		{
			name:     "REQ-EXPR-065_cast/text_to_int",
			query:    "SELECT CAST('123' AS INTEGER)",
			wantRows: [][]interface{}{{int64(123)}},
		},
		{
			name:     "REQ-EXPR-065_cast/text_to_real",
			query:    "SELECT CAST('3.14' AS REAL)",
			wantRows: [][]interface{}{{float64(3.14)}},
		},
		{
			name:     "REQ-EXPR-065_cast/real_to_int",
			query:    "SELECT CAST(3.9 AS INTEGER)",
			wantRows: [][]interface{}{{int64(3)}},
		},
		{
			name:     "REQ-EXPR-065_cast/int_to_real",
			query:    "SELECT CAST(42 AS REAL)",
			wantRows: [][]interface{}{{float64(42.0)}},
		},
		{
			name:     "REQ-EXPR-065_cast/null_to_text",
			query:    "SELECT CAST(NULL AS TEXT)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-EXPR-065_cast/null_to_int",
			query:    "SELECT CAST(NULL AS INTEGER)",
			wantRows: [][]interface{}{{nil}},
		},
		{
			name:     "REQ-EXPR-065_cast/blob_to_text",
			query:    "SELECT CAST(X'48454C4C4F' AS TEXT)",
			wantRows: [][]interface{}{{"HELLO"}},
		},
		{
			name:     "REQ-EXPR-065_cast/text_to_blob",
			query:    "SELECT typeof(CAST('hello' AS BLOB))",
			wantRows: [][]interface{}{{"blob"}},
		},
	}
}

func genExistsTests() []sqlTestCase {
	return []sqlTestCase{
		{
			name:     "REQ-EXPR-066_exists/true",
			setup:    []string{"CREATE TABLE t_exist(x INTEGER)", "INSERT INTO t_exist VALUES(1)"},
			query:    "SELECT EXISTS(SELECT 1 FROM t_exist)",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name:     "REQ-EXPR-066_exists/false",
			setup:    []string{"CREATE TABLE t_exist2(x INTEGER)"},
			query:    "SELECT EXISTS(SELECT 1 FROM t_exist2)",
			wantRows: [][]interface{}{{int64(0)}},
		},
		{
			name:     "REQ-EXPR-066_exists/not_exists_true",
			setup:    []string{"CREATE TABLE t_exist3(x INTEGER)"},
			query:    "SELECT NOT EXISTS(SELECT 1 FROM t_exist3)",
			wantRows: [][]interface{}{{int64(1)}},
		},
		{
			name: "REQ-EXPR-066_exists/correlated",
			setup: []string{
				"CREATE TABLE t_outer(id INTEGER, val TEXT)",
				"CREATE TABLE t_inner(ref INTEGER, data TEXT)",
				"INSERT INTO t_outer VALUES(1,'a'),(2,'b'),(3,'c')",
				"INSERT INTO t_inner VALUES(1,'x'),(3,'y')",
			},
			query:    "SELECT val FROM t_outer WHERE EXISTS(SELECT 1 FROM t_inner WHERE t_inner.ref = t_outer.id) ORDER BY id",
			wantRows: [][]interface{}{{"a"}, {"c"}},
		},
	}
}
