// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

// emitFile writes a single _test.go file for a module.
func emitFile(outputDir string, spec ModuleSpec, dryRun bool) error {
	var buf bytes.Buffer
	writeHeader(&buf)
	writeImports(&buf, spec)
	writeTestFunc(&buf, spec)
	writeBuildFunc(&buf, spec)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt %s: %w\nraw:\n%s", spec.Module, err, buf.String())
	}

	if dryRun {
		fmt.Printf("--- %s ---\n%s\n", fileName(spec.Module), string(formatted))
		return nil
	}

	path := filepath.Join(outputDir, fileName(spec.Module))
	return os.WriteFile(path, formatted, 0600)
}

func fileName(module string) string {
	return fmt.Sprintf("trinity_%s_test.go", module)
}

func writeHeader(buf *bytes.Buffer) {
	buf.WriteString("// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)\n")
	buf.WriteString("// Code generated by cmd/trinitygen. DO NOT EDIT.\n\n")
	buf.WriteString("//go:build trinity\n\n")
	buf.WriteString("package driver\n\n")
}

func writeImports(buf *bytes.Buffer, spec ModuleSpec) {
	imports := make([]string, 0, 4)
	if spec.NeedsFmt {
		imports = append(imports, `"fmt"`)
	}
	if spec.NeedsMath {
		imports = append(imports, `"math"`)
	}
	if spec.NeedsString {
		imports = append(imports, `"strings"`)
	}
	imports = append(imports, `"testing"`)
	if len(imports) == 1 {
		fmt.Fprintf(buf, "import %s\n\n", imports[0])
		return
	}
	buf.WriteString("import (\n")
	for _, imp := range imports {
		fmt.Fprintf(buf, "\t%s\n", imp)
	}
	buf.WriteString(")\n\n")
}

func writeTestFunc(buf *bytes.Buffer, spec ModuleSpec) {
	if spec.Comment != "" {
		fmt.Fprintf(buf, "// %s\n", spec.Comment)
	}
	fmt.Fprintf(buf, "func %s(t *testing.T) {\n", spec.TestFunc)
	fmt.Fprintf(buf, "\trunSQLTestsFreshDB(t, %s())\n", spec.BuildFunc)
	buf.WriteString("}\n\n")
}

func writeBuildFunc(buf *bytes.Buffer, spec ModuleSpec) {
	fmt.Fprintf(buf, "func %s() []sqlTestCase {\n", spec.BuildFunc)
	if len(spec.SubFuncs) > 0 {
		buf.WriteString("\tvar tests []sqlTestCase\n")
		for _, sf := range spec.SubFuncs {
			fmt.Fprintf(buf, "\ttests = append(tests, %s()...)\n", sf.Name)
		}
		buf.WriteString("\treturn tests\n")
	} else {
		buf.WriteString("\treturn []sqlTestCase{\n")
		for _, tc := range spec.Tests {
			emitTestCase(buf, tc)
		}
		buf.WriteString("\t}\n")
	}
	buf.WriteString("}\n")
}

// emitTestCase writes a single sqlTestCase struct literal.
func emitTestCase(buf *bytes.Buffer, tc TestSpec) {
	fmt.Fprintf(buf, "\t\t{name: %q", tc.Name)
	emitSetup(buf, tc.Setup)
	emitExecOrQuery(buf, tc)
	emitWantRows(buf, tc.WantRows)
	emitFlags(buf, tc)
	buf.WriteString("},\n")
}

func emitSetup(buf *bytes.Buffer, setup []string) {
	if len(setup) == 0 {
		return
	}
	buf.WriteString(",\n\t\t\tsetup: []string{")
	for i, s := range setup {
		if i > 0 {
			buf.WriteString(", ")
		}
		fmt.Fprintf(buf, "%q", s)
	}
	buf.WriteString("}")
}

func emitExecOrQuery(buf *bytes.Buffer, tc TestSpec) {
	if tc.Exec != "" {
		fmt.Fprintf(buf, ",\n\t\t\texec: %q", tc.Exec)
	}
	if tc.Query != "" {
		fmt.Fprintf(buf, ",\n\t\t\tquery: %q", tc.Query)
	}
}

func emitWantRows(buf *bytes.Buffer, rows [][]Value) {
	if len(rows) == 0 {
		return
	}
	buf.WriteString(",\n\t\t\twantRows: [][]interface{}{")
	for _, row := range rows {
		buf.WriteString("{")
		for j, v := range row {
			if j > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString(v.GoLiteral)
		}
		buf.WriteString("}")
	}
	buf.WriteString("}")
}

func emitFlags(buf *bytes.Buffer, tc TestSpec) {
	if tc.WantErr {
		buf.WriteString(",\n\t\t\twantErr: true")
	}
	if tc.ErrLike != "" {
		fmt.Fprintf(buf, ",\n\t\t\terrLike: %q", tc.ErrLike)
	}
	if tc.Skip != "" {
		fmt.Fprintf(buf, ",\n\t\t\tskip: %q", tc.Skip)
	}
}
