// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
package main

import (
	"fmt"
	"os"
	"path/filepath"
)

const compareHelpers = `// Code generated by go generate; DO NOT EDIT.
// SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later OR CC0-1.0 OR BSD-3-Clause)
package driver

import (
	"bytes"
	"math"
	"reflect"
)

func driverValueEqual(got, want interface{}) bool {
	if got == nil || want == nil {
		return got == nil && want == nil
	}

	if equal, ok := driverValueEqualBytes(got, want); ok {
		return equal
	}

	if equal, ok := driverValueEqualNumbers(got, want); ok {
		return equal
	}

	return reflect.DeepEqual(got, want)
}

func driverValueEqualBytes(got, want interface{}) (bool, bool) {
	switch gv := got.(type) {
	case []byte:
		switch wv := want.(type) {
		case []byte:
			return bytes.Equal(gv, wv), true
		case string:
			return string(gv) == wv, true
		}
	case string:
		switch wv := want.(type) {
		case []byte:
			return gv == string(wv), true
		case string:
			return gv == wv, true
		}
	}

	return false, false
}

func driverValueEqualNumbers(got, want interface{}) (bool, bool) {
	gotNum, ok := driverToFloat64(got)
	if !ok {
		return false, false
	}

	wantNum, ok := driverToFloat64(want)
	if !ok {
		return false, false
	}

	return gotNum == wantNum, true
}

func driverFloatCloseEnough(got interface{}, want float64) bool {
	gotNum, ok := driverToFloat64(got)
	if !ok {
		return false
	}

	if math.IsNaN(want) {
		return math.IsNaN(gotNum)
	}
	if math.IsInf(want, 1) {
		return math.IsInf(gotNum, 1)
	}
	if math.IsInf(want, -1) {
		return math.IsInf(gotNum, -1)
	}

	return math.Abs(gotNum-want) <= 0.001
}

func driverToFloat64(v interface{}) (float64, bool) {
	switch x := v.(type) {
	case int:
		return float64(x), true
	case int64:
		return float64(x), true
	case float32:
		return float64(x), true
	case float64:
		return x, true
	default:
		return 0, false
	}
}
`

func main() {
	wd, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	out := filepath.Join(wd, "test_compare_helpers_test.go")
	if err := os.WriteFile(out, []byte(compareHelpers), 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("wrote %s\n", out)
}
